### ISSUE TITLE
[Fix Available] Holding CTRL before selecting brush

### ISSUE THREAD

**Issue by jhinton2** [LogicalError/realtime-CSG-for-unity#10]
In Object mode If you hold CTRL(for snapping) and then select a brush(or anything) it just cancels the selection. You have to select it first and then press CTRL currently.

**Comment by LogicalError** [comment]
Ok, I'll look into this. In the mean time, you do know you can enable snapping by default in the bottom bar, right?

**Comment by LogicalError** [comment]
I uploaded a version on the beta site that fixes this (version 1.206)

**Comment by LogicalError** [comment]
This fix is now on the version that's on the asset store (1.207)
