### ISSUE TITLE
[Bug] Generating an object -> extruding it -> Undo throws a Null reference error

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#105]
Submitted in forum by pvloon: https://forum.unity3d.com/threads/released-realtime-csg-level-design-for-unity.427601/#post-2852128

**Comment by LogicalError** [comment]
I can't seem to reproduce this .. on what version of unity / realtime-CSG does this happen?
does it always happen, or just sometimes?

**Comment by pvloon** [comment]
Was on 1.312 unity 5.4. I've been working for a while in 1.318 and now 1.328 and 5.5 for a while and haven't had it there at all. Might have been fixed in an intermediate version

**Comment by LogicalError** [comment]
Ah ok, then I'll just close this ticket. Let me know if it happens again ;)
