### ISSUE TITLE
[Implemented] Feature Request: Physics Collider Options

### ISSUE THREAD

**Issue by jhinton2** [LogicalError/realtime-CSG-for-unity#11]
On the CSG_Model script can we get access to the rest of the physics collider options (physics material and concave).

**Comment by LogicalError** [comment]
I'm not sure what you mean with "concave"? If you mean the "Convex" flag on colliders there is a "Set Collider to Convex" flag that's been added in version 1.205.
Setting a default physics material per model is going to be part of 1.206 (I'll upload it later today)

**Comment by LogicalError** [comment]
Version 1.206 is now uploaded

**Comment by LogicalError** [comment]
This change is now in the version that's on the asset store (1.207)
