### ISSUE TITLE
[1.338] Support the scale tool in Mesh / surfaces mode

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#113]
Requested in forum by pvloon: https://forum.unity3d.com/threads/released-realtime-csg-level-design-for-unity.427601/#post-2852128

**Comment by otdavies** [comment]
I'd like to second this feature request, I really miss it in my work flow. I can't make cylinders like /\ easily without it. It is incredibly difficult to do by hand and is glitchy with the different grid scales required to achieve it properly. I hope this will be available at somepoint! It will complete my work flow!

**Comment by LogicalError** [comment]
I've written a forum post to get some feedback on this
https://prenominal.nl/forum/viewtopic.php?pid=22#p22

**Comment by LogicalError** [comment]
version 1.334 has experimental support for scaling polygons by dragging the center point of a mesh while holding shift+alt

**Comment by otdavies** [comment]
Awesome! You could also just associate being in the "scale mode" to scaling faces. It seems right now it just exclaims you can't scale in mesh mode. I am sure that will come in time though!

**Comment by pvloon** [comment]
Agreed! The scaling works awesome, just as I had hoped, but would feel more natural just being used when selecting the unity scale tool. Shift-alt is a slightly confusing shortcut + seems like real estate better reserved for other actions

**Comment by LogicalError** [comment]
Implemented in version 1.338. Which can be downloaded from https://prenominal.nl/updates/
This ticket will be closed when this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available on the asset store so this ticket can be closed
