### ISSUE TITLE
[1.328] Realtime GI breaks when entering play mode

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#116]
What I did:
- Set a CSG model to "Lightmap static" but not its brushes.
- Observed that realtime GI computed correctly ([screenshot](http://imgur.com/Cs71TA3)).
- Entered Play mode, observed that the GI mapping instantly appears to break ([screenshot](http://imgur.com/BHaiEoC)).
- Upon exiting play mode GI disappears entirely, and needs to be re-built.

Problem occurs on GI built via both "auto" and manual build.

Unity version: 5.4.0f3
Platform: iOS
GI Direction Mode: Non-Directional
Realtime CSG versions tested: 1.312 and 1.317

**Comment by LogicalError** [comment]
yikes, could you sent me a test scene? (email address can be found in top right corner of https://logicalerror.github.io/ )
thanks

**Comment by AlexanderOcias** [comment]
Sure thing, I've sent it through.

**Comment by LogicalError** [comment]
Got it, thanks!

**Comment by LogicalError** [comment]
This is fixed in 1.328! 
You can download it at the update site https://prenominal.nl/updates/
Once this version is available from the asset store, I'll close this ticket

**Comment by LogicalError** [comment]
Apparently lightmaps weren't working correctly after all!
I fixed this in version 1.362, sorry for this

**Comment by sonygod** [comment]
this is very important !
