### ISSUE TITLE
[1.338] Error when closing a scene

### ISSUE THREAD

**Issue by pvloon** [LogicalError/realtime-CSG-for-unity#118]
After closing a scene with a CSG in it:

Destroying object multiple times. Don't use DestroyImmediate on the same object in OnDisable or OnDestroy.
UnityEngine.Object: DestroyImmediate(Object)
RealtimeCSG.CSGSceneManager:OnDestroyed(CSGModel) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/CSGSceneManager.cs:974)
InternalRealtimeCSG.CSGSceneManagerInstance:OnDestroyed(CSGModel) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/CSGSceneManagerInstance.cs:23)
RealtimeCSG.CSGModel:OnDestroy() (at Assets/Plugins/RealtimeCSG/Runtime/Scripts/Components/CSGModel.cs:69)
UnityEditor.SceneManagement.EditorSceneManager:CloseScene(Scene, Boolean)

**Comment by LogicalError** [comment]
Strange error .. I'll investigate, thanks for reporting this!

**Comment by LogicalError** [comment]
This is fixed in version 1.321, which is available on the update site https://prenominal.nl/updates/
Once this version is available on the asset store, I will close this ticket

**Comment by pvloon** [comment]
Mmh, I still seem to be getting this in version 1.335! Same stack trace as above

**Comment by LogicalError** [comment]
Really? Ok, I'll investigate

**Comment by LogicalError** [comment]
What Unity version are you seeing this on?

**Comment by LogicalError** [comment]
Fixed in version 1.338. Which can be downloaded from https://prenominal.nl/updates/
This ticket will be closed when this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available on the asset store so this ticket can be closed
