### ISSUE TITLE
[1.320] 'Shadow only' model doesn't draw texture

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#119]
What I did:
- Made a new model with Cast Shadows set to 'Shadow only'.
- Made sure "Show Shadow Only Surfaces" is on.

What happened:
- in both edit and play mode, the model disappears, while its shadow remains cast ([screenshot](http://imgur.com/UV0w1lO)).

What I expected:
- In edit mode, the model to render with the "Shadow Only" texture, then to go invisible in play mode.

Platform: OSX
Unity version: 5.4.0f3 personal
RCSG version: 1.319

**Comment by LogicalError** [comment]
So the bug is that the model isn't showing the "shadow only" texture in the editor?

**Comment by AlexanderOcias** [comment]
Yep!

**Comment by LogicalError** [comment]
This issue is fixed in version 1.320, which is available on the update site https://prenominal.nl/updates/
 I'll close this ticket when this version is available on the asset store
