### ISSUE TITLE
[Bug] OSX Error sound constantly plays while holding down hotkey

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#120]
What happened:
- I held down "B" to draw a box, once I clicked and started dragging the mouse, the system error sound played continuously until I let go of the "B" key.
- The same issue happens with the "D" hotkey, "C" hotkey, "V" hotkey etc.
- This happens every time.

Platform: OSX
Unity version: 5.4.0f3 personal
RCSG version: 1.319

**Comment by LogicalError** [comment]
I'm just using the unity event system here, not doing anything which should make any sound play?
This is odd

**Comment by AlexanderOcias** [comment]
Yeah, weird. I do know Probuilder has similar [a long-standing similar bug with the event system](http://www.protoolsforunity3d.com/forum/index.php?/topic/1181-are-the-probuilder-hotkeys-a-little-funky-in-osx/#entry5774).

**Comment by AlexanderOcias** [comment]
Just noticed this problem does not occur with the Z key.

**Comment by LogicalError** [comment]
uhm ..that's weird

**Comment by LogicalError** [comment]
I think this is an Unity bug, I'm going to see if I can make a repro for Unity so they can fix this
