### ISSUE TITLE
[1.320] Dragging on extrusion arrow jumps extrusion point

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#121]
What I did:
- Drew a cylinder base
- Clicked on one of the extrusion arrows to start increasing its height

What happened:
- The height point instantly jumped to the position of the mouse ([screen capture](http://imgur.com/zEv0e1q))

What I expected:
- The point on the arrow I clicked would be the 0-height point, and dragging would increase/decrease the height from there.

Platform: OSX
Unity version: 5.4.0f3 personal
RCSG version: 1.319

**Comment by LogicalError** [comment]
This issue is fixed in version 1.320, which is available on the update site https://prenominal.nl/updates/
 I'll close this ticket when this version is available on the asset store
