### ISSUE TITLE
[1.326] Deleting brushes leaves floating invisible surfaces behind

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#122]
What I did:
- Made two brushes that touch on a face
- Deleted the brushes

What happened:
- An 'invisible' surface was left behind where the two brushes touched ([screen capture](http://imgur.com/bgk2Udn))

Platform: OSX
Unity version: 5.4.0f3 personal
RCSG version: 1.319

**Comment by LogicalError** [comment]
Ok, Thanks for reporting this, I'll investigate

**Comment by LogicalError** [comment]
This is now fixed in version 1.326!
It can be downloaded from https://prenominal.nl/updates/
I'll close this ticket once this version is available on the asset store
