### ISSUE TITLE
[1.320] "Receive Shadows" checkbox is off by default + has no effect

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#123]
What happened:
- Made a new CSG model
- The "Receive shadows" checkbox appears to be off by default.
- The model is receiving shadows anyway.
- Toggling the receive shadows checkbox does nothing. ([screenshot](http://imgur.com/3meN6GV))

**Comment by LogicalError** [comment]
allright, I'll look into it
Thanks for reporting this!

**Comment by LogicalError** [comment]
This issue is fixed in version 1.320, which is available on the update site https://prenominal.nl/updates/
 I'll close this ticket when this version is available on the asset store
