### ISSUE TITLE
[1.321] Put clones below their parents in the hierarchy

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#124]
- Currently dragged brush clones (D-drag) go above their source in the hierarchy.
- This is inconsistent with copy-paste behaviour which puts copies at the bottom of the hierarchy.
- A clone above in the hierarchy isn't useful since it means your (likely) intended subtract or intersect won't take effect (until you rearrange the hierarchy)
- I think maybe the clone should go below the source (or maybe at the bottom altogether, as with copy-paste)

**Comment by LogicalError** [comment]
I'll look into this, thanks

**Comment by LogicalError** [comment]
It actually doesn't put the clones above their source, it just leaves the source selected.
I'll fix this

**Comment by LogicalError** [comment]
This is improved in version 1.321, which is available on the update site https://prenominal.nl/updates/
Once this version is available on the asset store, I will close this ticket
