### ISSUE TITLE
[1.321] Rotation mode mouse position dashed line appears in wrong position

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#127]
What happened:
- Rotating any brush
- A yellow UI dashed line appears in a seemingly unrelated position
- That's supposed to be between the centre point and the mouse position, I assume?
- [Screen Recording Here](http://imgur.com/bOxVJBl)

Other possibly important info:
Platform: OSX with HiDPI/retina UI
Unity version: 5.4.0f3 personal
RCSG version: 1.319 and 1.320

**Comment by LogicalError** [comment]
Yes, that's wrong.. thanks for reporting this

**Comment by LogicalError** [comment]
This is fixed in version 1.321, which is available on the update site https://prenominal.nl/updates/
Once this version is available on the asset store, I will close this ticket
