### ISSUE TITLE
[1.326] Area-selecting brushes always uses global bounds

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#128]
What I did:
- Was in local object mode
- Made a brush
- Rotated it
- Attempted to area-select it by click-dragging to encompass its bounds
- [Screen recording](http://imgur.com/Ov07hGy)

What happened:
- The brush was not selected until I tried again and made my area-selection encompass the global bounds of the brush

What I expected:
- Area select would select the brush when it encompassed its local bounds

Other info:
Platform: OSX 10.11.6
Unity version: 5.4.0f3 personal
RCSG version: 1.320

**Comment by LogicalError** [comment]
Hmm .. ok, I'll look into this. Thanks for reporting this

**Comment by LogicalError** [comment]
This is now fixed in version 1.326!
It can be downloaded from https://prenominal.nl/updates/
I'll close this ticket once this version is available on the asset store
