### ISSUE TITLE
[1.327] Way to disable Realtime CSG

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#129]
- It appears Realtime CSG and its GUI and hotkeys are permanently active across any scene in a project it's imported to, even if there are no Realtime CSG objects present.
- This is a problem when you other packages that the Realtime CSG GUI or hotkeys interfere with, (for example, SabreCSG, which I've got in all my existing scenes).
- You can't disable it by closing it, since it just alternates between the HUD and tab mode.
- Maybe Realtime CSG should be off until you select a Realtime CSG model or brush?
- Alternatively, some menu option to temporarily close as required rather than just toggle tab vs GUI?

**Comment by LogicalError** [comment]
That's probably a good idea, I'll look into this

**Comment by LogicalError** [comment]
related to #114

**Comment by LogicalError** [comment]
This is implemented in version 1.327, which is available on the update site https://prenominal.nl/updates/
Once this version is available on the asset store, I will close this ticket
