### ISSUE TITLE
[FIX AVAILABLE] Creating "U" or "E" shape with Free-Draw brush results in error

### ISSUE THREAD

**Issue by JingleFett** [LogicalError/realtime-CSG-for-unity#13]
Hi I noticed the following issue with the Draw Brush. If you create a U shape using the draw brush, when you click on the green arrow to extrude it, it results in "NullReferenceException: Object reference not set to an instance of an object". If you create an E shape and drag on the green arrow, the same error appears or sometimes instead the message "Could not create brush from given 2D shape" appears and then you can't move the view until you press any button in the Realtime CSG window (like pressing Cylinder or Object buttons). Here's a picture of what the U shape looks like (the E shape is similar) http://i.imgur.com/eiA6I7Y.jpg

For reference, I'm using version 1.210 but had the same issue in 1.208 and I'm on Unity 5.3.5f1

**Comment by LogicalError** [comment]
Thanks for submitting your bug! I'll take a look at it

**Comment by LogicalError** [comment]
Hi! This issue is fixed in version 1.211 which is available on the beta site
Once this is on the asset store I'll close this bug

**Comment by JingleFett** [comment]
oh wow that was fast, thank you!

**Comment by LogicalError** [comment]
np! Also, fix available on the asset store!
