### ISSUE TITLE
[Request] Snap meshes to grid while dragging

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#130]
What I did:
- Dragged a prefab from my project onto my CSG model.
- [(Screen recording)](http://imgur.com/0nlhNCq).

What happened:
- No snapping.

What I expected:
- The prefab's pivot to snap to the surface of the CSG model, as it does with other meshes.

Other info:
Platform: OSX 10.11.6
Unity version: 5.4.0f3 personal
RCSG version: 1.320

**Comment by LogicalError** [comment]
This is a mesh that you're dragging, not a brush?

**Comment by AlexanderOcias** [comment]
Yep.

**Comment by LogicalError** [comment]
Ah ok, that's not a bug then. That was never part of realtime-CSG.
There is another feature request for this however: #100

**Comment by AlexanderOcias** [comment]
Wait a sec, I'm not trying to snap the meshes to the grid, I'm trying to snap the pivot to the *surface* of the CSG model during the initial drag-in, the same way it does with the mesh on the right in my screen recording - just default unity behaviour, nothing to do with any grid.

**Comment by LogicalError** [comment]
Ok, I'll look into it, thanks for clarifying this

**Comment by LogicalError** [comment]
Related to #62

**Comment by LogicalError** [comment]
This is implemented in version 1.406, which can be found on the support website ( https://prenominal.nl/updates/ )
I will close this ticket once this version is available from the asset store
