### ISSUE TITLE
[1.324] Invisible and discarded surfaces do not draw

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#131]
What happened:
- Installed RCSG v1.323 to address issue #125 and found that invisible and discarded surfaces no longer appear at all.
- They sometimes flicker briefly when hovering over the RCSG GUI. ([screen recording](http://imgur.com/zGZ2rHP))
- They DO appear when Unity is in the background.
- A bunch of bracketed gameobjects now appear in the hierarchy ([screenshot](http://imgur.com/Y8gOr4r)), maybe related? Maybe another bug?

Other info:
Platform: OSX 10.11.6
Unity version: 5.4.0f3 personal
RCSG version: 1.323

**Comment by LogicalError** [comment]
That's weird .. hmm .. are you using deferred or forwarded lighting?

**Comment by AlexanderOcias** [comment]
Forward lighting. I just tried swapping to deferred, and it didn't make any difference unfortunately.

**Comment by LogicalError** [comment]
I fixed this in 1.324, apparently something changed between Unity versions which caused this to not work in 5.4 and up :-/
You can find this on the update site https://prenominal.nl/updates/
I will close this ticket once it's available from the asset store
