### ISSUE TITLE
[1.326] Dimension arrows/lines are skewed

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#132]
- The dimension arrows/lines/indicator UI on the sides of a brush are offset in 2D-space, and appear skewed in 3D space
- You can see in this [screenshot](http://imgur.com/a/zIxAP) the Z-axis length indicator crosses over the gridline, shouldn't it be parallel to the line? ie. parallel the brush's edge in 3D space, not 2D space?

**Comment by LogicalError** [comment]
I'll look into this. It has to do with scaling the arrows according to the distance to camera

**Comment by LogicalError** [comment]
This is now fixed in version 1.326!
It can be downloaded from https://prenominal.nl/updates/
I'll close this ticket once this version is available on the asset store
