### ISSUE TITLE
[Request] Option to composite an additive and subtractive brush into a single additive brush

### ISSUE THREAD

**Issue by otdavies** [LogicalError/realtime-CSG-for-unity#137]
I am finding that I often have complicated operations made up of a single additive basic shape with several subtractive brushes cutting into it. I am wondering if it is possible to convert it into a single additive shape with all of the subtractions applied. This would be helpful in the situation where I know I won't be changing the additive+subtraction going forward, but I still want to easily duplicate the operation as a whole and rescale it, etc. It could be a second click operation when selecting any number of brushes that affect each other, to "simplify". I also know your half-edge algorithm doesn't allow odd manifold shapes etc, so I know there would be limitations of what it could achieve. If it isn't possible I understand.

Example (hierarchy):
_-Operation
---additive brush
---subtractive brush
---subtractive brush_

would become:

_-Operation
---additive brush (having applied the subtractions to it)_

An alternative solution would be that you could lock an operation and couldn't select its children, so it is easier to work with. I often select the children of the operation by accident while working in the scene and it is relatively frustrating.

I know you can actually export it as a separate model currently, but that means I cannot edit the resulting shape or clip it etc.

Hopefully this request makes sense! 

All the best,
Oliver

**Comment by LogicalError** [comment]
Hi!
Grouping multiple brushes into one object is not possible at the moment, it would require some major refactoring which would take a lot of time to implement... so I won't be able to do that in the short term

However, the alternative solution you mentioned actually already exists: 
<img width="259" alt="select_on_child" src="https://cloud.githubusercontent.com/assets/157976/20664372/344e3f36-b55b-11e6-8529-b2a3df328bf3.PNG">
If you toggle the "select on child" checkbox, then every time you select one of the child brushes of an operation, you select them all.
Is that what you meant?

**Comment by otdavies** [comment]
Ah, I understand the composite brush issue, no worries! I wasn't 100% sure what that option did, I'll try it!

I appreciate all of your hard work!

**Comment by LogicalError** [comment]
👍

**Comment by LogicalError** [comment]
related to #34

**Comment by LogicalError** [comment]
I'm going to close this issue considering that you can use operations to combine brushes, and ticket #34 would solve any remaining use cases
