### ISSUE TITLE
[1.329] Organise all files under one root folder 

### ISSUE THREAD

**Issue by pvloon** [LogicalError/realtime-CSG-for-unity#138]
For project organisation and when upgrading versions it would be very convenient to have all realtime CSG files under the same file root. I understand the reasons for putting things in editor default resources (code convenience, making sure people don't reference it from their game folder). However, the same could be accomplished by keeping these files in an Editor folder and using AssetDatabase.LoadAssetAtPath.

Unity 5.5 and up also allows you to put Resources folder in an editor folder and have assets excluded at build time. (https://docs.unity3d.com/550/Documentation/Manual/UpgradeGuide55.html)

Based on discussion over at: https://forum.unity3d.com/threads/released-realtime-csg-level-design-for-unity.427601/#post-2852128

Thanks :)

**Comment by otdavies** [comment]
I second this suggestion!

**Comment by LogicalError** [comment]
Sure, I'll take a look at this

**Comment by LogicalError** [comment]
This is implemented in version 1.329!
which you can download from the update site: https://prenominal.nl/updates/
Once this version is available from the asset store I will close this ticket
