### ISSUE TITLE
[Bug] Disabling static flag on model still sets static flag on generated mesh GameObject

### ISSUE THREAD

**Issue by pvloon** [LogicalError/realtime-CSG-for-unity#139]
When disabling the static flag on the CSG model, the generated mesh is still marked as static. This prevents creating movable objects

**Comment by LogicalError** [comment]
Oh, that shouldn't happen. Thanks for reporting this, I'll investigate

**Comment by LogicalError** [comment]
I can't seem to reproduce this .. can you give me more details / a repro?
what version of realtime-CSG and Unity are you using?

**Comment by pvloon** [comment]
Mmmh, trying it now I can't reproduce either. Seems to be PEBKAC, sorry about that!

**Comment by LogicalError** [comment]
Odd .. well let me know if you encounter it again

**Comment by LogicalError** [comment]
I'm closing this issue, if this happens again, let me know and I'll look at it again
