### ISSUE TITLE
 [Feature Request] Generate Rectangular Cube [Available in 1.300]

### ISSUE THREAD

**Issue by JingleFett** [LogicalError/realtime-CSG-for-unity#14]
In addition to the ability to generate brushes using Free-Draw and Cylinder, I think it'd be pretty useful to be able to generate box primitive shapes using a rectangular marquee. If you're making interior levels, rooms are often box shaped so a feature like this would speed things up (as opposed to making 4-sided cylinders or using Free-Draw).

**Comment by LogicalError** [comment]
Yes, you're right that's very useful. It was actually on my todo-list .. and you've just increased the priority;)

**Comment by JingleFett** [comment]
awesome, I'm looking forward to it!

**Comment by LogicalError** [comment]
Version 1.300, which is available on the beta site, now has a box edit mode! :)
I'll close this feature request when it's on the asset store

**Comment by LogicalError** [comment]
This feature is now available on the version that's on the asset store!
