### ISSUE TITLE
[Request] Move pivot of CSG model

### ISSUE THREAD

**Issue by pvloon** [LogicalError/realtime-CSG-for-unity#140]
When constructing CSG models the original pivot of the transform isn't really shown or used but for organisation & for constructing dynamic models it can be important to position this in some specific location of the mesh

**Comment by LogicalError** [comment]
Yes, that's a very useful idea. This was actually on my todo list, just hadn't gotten to it yet, you've just made it more important though

**Comment by LogicalError** [comment]
mental note: would be nice to make it look like https://i.stack.imgur.com/fXA1C.png

**Comment by LogicalError** [comment]
This is fixed in version 1.355!
see https://prenominal.nl/forum3/showthread.php?tid=46 and https://prenominal.nl/forum3/showthread.php?tid=45
You can download this from the update site!
I'll close this ticket once this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available from the asset store, so I'm closing this ticket
