### ISSUE TITLE
[Bug] When moving parent of CSG model the model doesn't update

### ISSUE THREAD

**Issue by pvloon** [LogicalError/realtime-CSG-for-unity#141]
When moving a normal unity parent GameObject of the CSG model the model doesn't update.

Could be solved by either rebuilding when hierarchy changes - or ideally the generated-meshes would actually be a child of the main csg model so the behaviour would match with the generated model when built (+would save some editor performance)

**Comment by LogicalError** [comment]
Hi, what version are you on? I can't reproduce it on 1.329 ..

**Comment by pvloon** [comment]
Grump grump - updated to 1.329 and it's gone! 

I think here's what happened: while upgrading I got an error message about the DLL being in. Manually deleting it after closing unity and then upgrading worked. I think I must have foregone this last time and got stuck on some hybrid 1.312 & 1.328 version, hence some weird behaviors... 

So, warning to people upgrading, be sure to close unity and delete the realtime CSG folder manually first.

**Comment by LogicalError** [comment]
Yeah this is an anoying artifact of not being able to overwrite a dll when it's in use by unity .. yet you can't unload it either :-/
I guess it's ok to close this ticket then?

**Comment by pvloon** [comment]
Fine with me :) Will be careful about my upgrades from now on

**Comment by LogicalError** [comment]
👍
