### ISSUE TITLE
[1.331] When Reenabling a CSG model the model does not update

### ISSUE THREAD

**Issue by pvloon** [LogicalError/realtime-CSG-for-unity#142]
When disabling and reenabling a CSG model it does not rebuild automatically. Either by manually disabling/enabling or using shift-H. Brushes & sub operations do work fine!

Version: 1.329

**Comment by LogicalError** [comment]
Ok, thanks for reporting this I'll look into it

**Comment by LogicalError** [comment]
This is fixed in version 1.331, which is available on the update site https://prenominal.nl/updates/
I will close this ticket once it's available from the asset store
