### ISSUE TITLE
[Bug] Panning camera by arrows key isn't working properly when in Surfaces mode

### ISSUE THREAD

**Issue by CodeCaster28** [LogicalError/realtime-CSG-for-unity#143]
I get use to panning 3d view by using arrows keys and/or arrows key+shift to move it faster, but somehow it's really laggy when working in surfaces mode.

**Comment by LogicalError** [comment]
I'll look into it, thanks for reporting this

**Comment by LogicalError** [comment]
I'm not seeing any lag on my macbook, and that's pretty terrible hardware ;p
Can you give me some more information? Is it always? Only in a specific scene or specific scenes? Are you selecting lots of surfaces? What Unity version and what version of Realtime CSG?
Thanks

**Comment by CodeCaster28** [comment]
Unity version: 5.4.2f1 (64-bit) Windows 7
Realtime CSG version: 1.318 (Nov 28, 2016)

It happens in a new scene, and new project as well. Always when I enters Surface (Texturing) mode and pressing arrows keys to pan the camera, the editor moves camera but after a few-seconds delay. When I exit this mode, the camera starts responding good again.. well almost, the camera moves in some random direction very fast infinitely, unless I press move key again to recover control over it. It seems that only camera view is lagging, I can do any other action w/o problem, I can even rotate camera, it only lags when I'm panning camera with arrow keys.

Unfortunately I can't download a beta version, it says the order key is incorrect (I'm sure it is correct).

**Comment by LogicalError** [comment]
Ah, 1.318 is quite old by now .. I'll try to reproduce it
Can you sent me your key through email (top right corner of https://logicalerror.github.io/ ) so I can check why downloads don't work for you? Thanks

**Comment by CodeCaster28** [comment]
Okay, I updated plugin to the newest version and problem still persist, you need to select a surface first, then try to move around.

**Comment by LogicalError** [comment]
could this be related to #148  ?

**Comment by CodeCaster28** [comment]
Hmm rather not. It's freezes when panning the camera anyway, also I found out that this happen when I put a cursor over any CSG surface. As long as I keep cursor away from surface the problem is not showing up.

**Comment by LogicalError** [comment]
Oh, ok that might help me to track this down, thanks!

**Comment by LogicalError** [comment]
Fixed in version 1.351. Which can be downloaded from https://prenominal.nl/updates/
This ticket will be closed when this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available from the asset store, so I'm closing this ticket
