### ISSUE TITLE
[Question] Copying texture offsets from one surface to another.

### ISSUE THREAD

**Issue by CodeCaster28** [LogicalError/realtime-CSG-for-unity#144]
Is it possible to "copy" texture offsests/rotation and "paste" them into another surface? Or select all surfaces with differently oriented textures and "group" their offsets?

**Comment by CodeCaster28** [comment]
Oh sorry just found this feature, I didn't know it was this "G" hold key, and how to use it at a first time but found it in index page. Can be closed :)

**Comment by LogicalError** [comment]
Glad you found it :) 👍
