### ISSUE TITLE
[Request] Create a guide for creating prefabs

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#146]
Apparently it's not entirely clear from the outset how to create a good prefab.
A guide would be nice

**Comment by LogicalError** [comment]
https://logicalerror.github.io/getstarted.html has a bit more information about prefabs.

**Comment by Petethegoat** [comment]
Prefab creation definitely isn't clear.

I assumed you'd either create a prefab out of a model or operation, but trying to drag it into the scene view onto a model just puts it way out in space away from my model.

Definitely needs a 30 second video or an explicit set of instructions on how to make a basic prefab.

**Comment by LogicalError** [comment]
Hi @Petethegoat , I'm not entirely sure what you mean with offset changes?

**Comment by LogicalError** [comment]
I'll try to make a tutorial video somewhere next week

**Comment by LogicalError** [comment]
Hi, I create a prefab video here: https://www.youtube.com/watch?v=bChuOnELDvQ
Let me know what you think!

**Comment by Petethegoat** [comment]
Illuminating. Thank you!

**Comment by LogicalError** [comment]
You're welcome!
