### ISSUE TITLE
[1.335] Very low editor frame rate when using both Realtime CSG and lots of your own models

### ISSUE THREAD

**Issue by CodeCaster28** [LogicalError/realtime-CSG-for-unity#148]
It is obvious that editor slows down when you have thousands of you own models in your scene. However even with ~300 models my editor works just fine, I always could temporarily turn off models so editor works like a charm so I might do other stuff w/o lags. However importing Realtime CSG plugin into this very scene makes it very hard to work with editor (low fps when rotating camera, a little more when only panning it). Disabling models by unticking their checkboxes doesn't help very much, only if you delete those models gradually from scene makes editors recovers it's normal fps.

I think there is an issue with CSG editor script(s). I looked into the Profiler to see more details about this issue, I listed possible scenarios with profiler report:

- with models turned on:
    40fps when not moving view, 17fps when rotating view
    Time (ms): scripts 8, rendering 15 when not moving view
                      scripts 65, rendering 16 when rotating view

- with models turned off:
    65fps when not moving view, 18fps when rotating view,  
    Time (ms): scripts 8, rendering 5 when not moving view
                      scripts 45, rendering 5 when rotating view

-with models removed:
    >200fps when not moving view, 100-200fps when rotating view,  
    Time (ms): scripts 2, rendering 1 when not moving view
                      scripts 6, rendering 1 when rotating view

-after pressed undo to retrieve deleted models, situation gets even worse don't know why:
    17fps when not moving view, 5-10fps when rotating view,  
    Time (ms): scripts 34, rendering 24 when not moving view
                      scripts 56, rendering 25 when rotating view

-finally I removed Realtime CSG and tested again with models turned ON:
    90fps when not moving view, 40fps when rotating view,  
    Time (ms): rendering and script close to 0 when not moving view
                      scripts 4, rendering 18 when rotating view

So I'm sure there is some conflict between Realtime CSG and models imported to scene. The scripts takes most of CPU usage, the DockArea.OnGui() command to be precise, it's almost 100% of scripts usage, and 60% to 90% of whole CPU.
![przechwytywanie](https://cloud.githubusercontent.com/assets/16106194/21021395/9544220e-bd78-11e6-8afa-2f08fe8355f8.JPG)

Other info that may be useful:

1) If I remove all others assets from scene and project files leaving just models and textures plus RCSG the bug still persists. So this must be a conflict with my meshes and RCSG plugin.

2) When opening a new scene after opening the project the issue is not occurring, but when I go into scene with lot of models then go back again into that empty scene, strangely the issue still persists.

3) It is not required to put any CSG brushes on a scene, the problem starts when I import RCSG or open the editor with already imported RCSG. Clearing Liblary folder isn't working.

4) Models are in FBX format, the way editor imports them lets me edit different part of the models separately (maybe this counts as even more models).

4) Game FPS is very high, so issue is not affecting a gameplay itself.

6) Other things I tried to do to fix the issue:
- removing Library folder in Project folder
- removing navigation meshes, light data or switching lightning realtime to baked e.t.c.
- copying assets into new scene
- testing on older version of RCSG

Maybe CSG scripts uses meshes from my scene to compute something? All tests above I made w/o placing single CSG brush on scene, problem starts when editor loads plugin. No error messages/warnings are shown.

Tested at Windows 7, Unity version 5.4.2f, Realtime CSG version 1.333

**Comment by LogicalError** [comment]
When you say "models", do you mean CSG models? or unity meshes? .. just making sure

**Comment by LogicalError** [comment]
Ok .. I just created a scene that contains Realtime-CSG and created 780 meshes (390 fbx models, all the same one) and it was still fine on my computer ... so I need some more information to figure out what's going on :-/
There must be a factor that's different for you somehow ...

**Comment by CodeCaster28** [comment]
It's about 300 unity meshes made from fbx models.
Tried reenabling and reimporting, no luck on that.

**Comment by LogicalError** [comment]
Can you check if you see any performance difference between having the tools in the scene and if the tool windows are docked? (control-F2 to switch between them)

**Comment by CodeCaster28** [comment]
Amazing, yes this is the cause, why I didn't tried it before :D, so I "undocked" UI elements and fps rises to stable 60 again, profiler says the same thing.

**Comment by LogicalError** [comment]
cool, then I'm confident that I know what was going on .. 

I was using a particular function to find the current window .. 
and apparently it goes through ALL the assets in a project, and it's _really_ slow .

I didn't notice since I don't have as many assets in my projects .... :-/

I wrote a workaround: version 1.335 , which you can find at https://prenominal.nl/updates/

**Comment by CodeCaster28** [comment]
I'm surprised you found and fixed this issue that fast. I thought this is meshes issue cause removing any other assets brings no fix for this. Thank you very much for this I can get back to level design :)

**Comment by LogicalError** [comment]
You're welcome :)

**Comment by LogicalError** [comment]
this version is available on the asset store, so I'm closing this ticket!
