### ISSUE TITLE
[1.336] Make mesh invisible but with collision enabled.

### ISSUE THREAD

**Issue by CodeCaster28** [LogicalError/realtime-CSG-for-unity#149]
Is it possible to create a mesh that is not rendered but still collides with environment? Tried to use "Do not Render" and "Generate Collider" both selected but it didn't work, also tried enabling/disabling "Create RigidBody" but still nothing. Did I miss something?

**Comment by LogicalError** [comment]
This was a bug, this is fixed in 1.336 that you can download here https://prenominal.nl/updates/
I'll close this ticket once it's available on the asset store
Let me know if you run into anything else!

**Comment by LogicalError** [comment]
This version is now available on the asset store so this ticket can be closed
