### ISSUE TITLE
[1.337] Add Generated meshes to 'proper' CSG model

### ISSUE THREAD

**Issue by pvloon** [LogicalError/realtime-CSG-for-unity#151]
When drawing new brushes on existing surfaces the brush seems to be attached the 'current active' CSG model (not sure based on what). It would be great if instead if would be placed into the hierarchy of the CSG model it was drawn on.

Additionally if it could figure out a 'good' spot in the hierarchy to place itself that would be neat! I imagine something like 'after all brushes that generated the surface(s) the model was drawn on' should work in most cases.

**Comment by LogicalError** [comment]
Ok, t sounds like it would be a good thing to do w/ choosing the model, thanks for the suggestion :)
As for placing brushes in the hierarchy, this is complicated by the fact that your newly generated brush might be removed by another brush if it's not added at the end of the hierarchy .. which would be completely confusing if that happens :-/

**Comment by LogicalError** [comment]
This has been fixed in version 1.337 that is available on the update site https://prenominal.nl/updates/
I'll close this ticket once this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available on the asset store so this ticket can be closed
