### ISSUE TITLE
[1.337] Deleting vertices in free-draw mode producing an error.

### ISSUE THREAD

**Issue by CodeCaster28** [LogicalError/realtime-CSG-for-unity#152]
When you generating a mesh in free-draw mode you can select and move vertices which is very handy. However you can also delete those vertices making an error. After you trying to extrude the same shape to final mesh console logs an error message (IndexOutOfRangeException: Array index is out of range), and you cannot really do anything but cancel it and start making new shape.

**Comment by LogicalError** [comment]
I'll take a look, thanks

**Comment by LogicalError** [comment]
This has been fixed in version 1.337 that is available on the update site https://prenominal.nl/updates/
I'll close this ticket once this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available on the asset store so this ticket can be closed
