### ISSUE TITLE
[1.338] Brush geometry not generated/invisible after building scene

### ISSUE THREAD

**Issue by EStallings** [LogicalError/realtime-CSG-for-unity#154]
In-editor, all appears fine. Nominal test scene to demonstrate problem: 1 regular default cube gameobject, 1 brush object, 1 default cube with a rigidbody (to fall onto the brush).

Scene view:
http://i.imgur.com/AA2nIlL.png

In-editor through Game view after hitting play:
http://i.imgur.com/b6zlG6F.png

After building and running:
http://i.imgur.com/HeoPOGv.png

I did the physics test to ensure it wasn't just a shader issue (although I also tested other shader/materials and got the same result), and that the geometry isn't being generated at all, not merely invisible. Sure enough, the physics cube falls straight through where the brush should be.

Happy to help in any way I can!

**Comment by LogicalError** [comment]
Hi, could you sent me that scene so I can take a look at it? my email adress is on the top right corner of https://logicalerror.github.io/
thanks

**Comment by CodeCaster28** [comment]
I have the same issue. After Rebuilding the game all CSG brushes are gone.

**Comment by LogicalError** [comment]
Yeah I can confirm that the issue happens all the time .. really annoying that playing in the editor behaves differently than building the game in Unity :-/
Anyway I have a fix, I'll get it out later today

**Comment by CodeCaster28** [comment]
Thank you. Realtime CSG is not alone though, some others plugins or even normal models sometimes have problems to be build into the game. Hope some day Unity will get rid of it's annoying disfunctionalities.

**Comment by LogicalError** [comment]
Fixed in version 1.338. Which can be downloaded from https://prenominal.nl/updates/
This ticket will be closed when this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available on the asset store so this ticket can be closed
