### ISSUE TITLE
I want to know if this asset is capable of in game real time terrain/object deformation like the red faction 1 game.

### ISSUE THREAD

**Issue by zoice** [LogicalError/realtime-CSG-for-unity#155]
I want to buy this asset if it is capable.  If I could be pointed in the right direction that would be amazing.
Here is a link to how redfaction's GeoMod works.

https://web.archive.org/web/20100109011210/http://john.slagel.com/Geomods.html

**Comment by LogicalError** [comment]
Hi @zoice !
At the moment realtime-CSG does not have runtime support yet (but it's planned to be added eventually).
I want to make sure that the editor side of things is more complete first + have a good editor side API first.

Strictly speaking realtime-CSG should be able to do everything that red faction did, except that calculations are not spread out over multiple frames and that realtime-CSG does not do runtime path updates (which is not strange considering that there's no runtime support yet)

It's definitely fast enough for this, and I think it should be possible to make it 5-10x faster still. For example, currently it's only running on one thread and adding multi-threading shouldn't be too hard (just haven't gotten around to it and other things had higher priority)

![sphere_csg](https://cloud.githubusercontent.com/assets/157976/21605951/9deff4da-d1ac-11e6-95be-c7b61cf836e2.gif)

**Comment by zoice** [comment]
Thank you so much for getting back to me. :) . Honestly as soon as this has
runtime support, I am going to buy it sooooo fast. Also in order to further
understand and create my own runtime csg system such as the geomod, what
would you recommend learning or researching first to last? This is
something I want so badly. Ill take the steps to figure it out.

**Comment by LogicalError** [comment]
Well I developed my own algorithm from scratch .. 
I blogged about an ancient version of my algorithm here http://sandervanrossen.blogspot.dk/2009/12/realtime-csg-part-1.html

**Comment by aughey** [comment]
I'd like to second the request for runtime CSG support.  I have already purchased realtime CSG, in part, to be honest, because the name implied that it might be usable during gameplay.  I find it useful without that, but my real need is for CSG operations during runtime.

**Comment by LogicalError** [comment]
Hi @aughey, there have been many people who requested runtime support, and it's definitely a plan of mine to implement this!
I just haven't gotten around to do this, yet

But since you've brought it up, what platforms would you want to use runtime support on? (I need to figure out which platforms would be the most important for runtime support, so I ask everyone who brings it up)

**Comment by sonygod** [comment]
android and ios

**Comment by aughey** [comment]
Windows.  Maybe ultimately android, but to prove out some concepts I would start with Windows to see if my ideas are viable.  

The entirety of realtime CSG wouldn't be needed with respect to the UI controls and additional features, but being able to manipulate the tree and attributes would be awesome.  The simplest would be to be able to add prefabs that do cutting operations such as your window prefab on to a wall that was previously solid.
