### ISSUE TITLE
[Request] Post build/Pre-play callbacks in script

### ISSUE THREAD

**Issue by HilariousCow** [LogicalError/realtime-CSG-for-unity#157]
Hi Sander,
I'm new to RealtimeCSG, but have been using SabreCSG in the past. It has this lovely feature of being able to use an attribute to do a callback when the build is finished.

https://github.com/sabresaurus/SabreCSG/blob/master/Scripts/CallbackEvents.cs

I used this to trigger off lots of custom scripts (things like swapping out physics materials, compiling meshes into one, before triggering a navmesh build etc).

I'm not sure if something like this already exists, but it'd be amazing to have a few of these to tap into, so that I can save our level designers the hassle of setting up every level in the project with things that our game play requires.

So, I propose Callbacks/Attributes for:

- When the CSG completes a rebuild
- When the player hits play and CSG has changed since last time the unity user hit Play.
- And/or, just a way to check if the CSG has changed since the last time the unity user hit Play.

I hope this is not too much of a big deal!

And thanks, the editor is working out really well for us so far! Very impressed at the build speed.

**Comment by LogicalError** [comment]
Hi! I added some functionality for this in version 1.344 which can be found on the update site here: https://prenominal.nl/updates/

There's also a very rudementary, WIP editor API documentation page here:
https://logicalerror.github.io/editor-api.html

**Comment by LogicalError** [comment]
this version is available from the asset store, so I'll close this ticket

**Comment by LogicalError** [comment]
(adding this here for clarity, so I can point other people to this ticket)
an example:
	[CSGModelModifiedEvent]
	static void OnCSGModelModified(CSGModel model, GameObject[] modifiedMeshes)
	{
	}

public static class CSGModelManager was added and has these helper methods
	
	// rebuilds all the meshes for all the models in the current scene(s)
	public static void ForceRebuild();		
	
	// ensures that all models are up to date and rebuild if changed.
	public static void EnsureBuildFinished(); 
	
	// returns all the GameObjects for a model that contain MeshRenderers and/or MeshColliders
	public static GameObject[] GetModelMeshes(CSGModel model); 
	
	// returns all the current models in the current scene(s)
	public static CSGModel[] GetAllModel();

	Both of these methods will call generate CSGModelModifiedEvents (see above) if anything has changed
