### ISSUE TITLE
[Bug] Extruding a shape on top of a subtracted surface will pick the wrong operation

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#159]
When you draw a shape (box, free-draw, cylinder etc.) on top of a surface that's generated from a subtractive brush, it'll pick the wrong operation (subtractive/additive)

**Comment by LogicalError** [comment]
This has been fixed in version 1.350. Which can be downloaded from https://prenominal.nl/updates/
This ticket will be closed when this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available from the asset store, so I'm closing this ticket

**Comment by Skylar1146** [comment]
This issue appears to have regressed in version 1.546

**Comment by LogicalError** [comment]
![extrusion](https://user-images.githubusercontent.com/157976/56128155-30757480-5f7f-11e9-89d4-3f761096ee70.gif)
![extrusion2](https://user-images.githubusercontent.com/157976/56128298-84805900-5f7f-11e9-998f-7442dc28dedb.gif)
I can't seem to reproduce it, could you provide some more details on what you're seeing, how I can reproduce it?

**Comment by Skylar1146** [comment]
If the brush is subtractive, extruding it will result in an additive brush. Expected result is it would extrude a brush of the same type. This is especially relevant in Inverted-World workflows
![ShapeExt](https://user-images.githubusercontent.com/13981956/56136477-7c60f300-5f58-11e9-9320-7a73e0e35a3c.gif)

**Comment by LogicalError** [comment]
In an inverted workflow it makes sense that this extract brush would subtractive, if the original brush you're extruding from is additive. 
This situation .. I'm not sure if this make sense, to extrude a subtractive brush into empty space?

**Comment by LogicalError** [comment]
Ok, I discovered if you move the other sides of a cube in that situation the extrusion would choose the wrong operation .. fixing that makes the above situation behave like you wanted to & it makes it more consistent. Working on a new version to release this fix

**Comment by LogicalError** [comment]
Fixed in 1.549!

**Comment by Skylar1146** [comment]
Hate to say, but seems bugged now. It will extrude as subtractive, but once you finalize the shape it reverts back to additive.
![ShapeExt2](https://user-images.githubusercontent.com/13981956/56163156-40974f00-5f93-11e9-8135-1a240adcb713.gif)

**Comment by LogicalError** [comment]
Oops, I guess I never actually committed those brushes when testing.
I have a new version up 1.549B that fixes this
