### ISSUE TITLE
[Implemented] Assign Materials on Brushes

### ISSUE THREAD

**Issue by Cyber2017** [LogicalError/realtime-CSG-for-unity#16]
Hello, I must say this Realtime CSG has truly helped me with my New Game... K, I mentioned in my review about Assigning Materials to the brushes before performing A:

Subtraction/Addition to the Model!!

EX: I used this Asset that when it cut's out the Shape; it leaves the Material there.. Like Holy! Molly!
(Boolean Ops)
Link: https://www.assetstore.unity3d.com/en/#!/content/18544

I really like this Asset but, I really don't like trying to select a surface between my Stone blocks... In fact I'm "Disappointed with the Surface Feature".. :(
:D / On a positive Note, the Modelling ability with Realtime CSG is Above! Anything that I know of... But, please!! make the Adding materials easier... Ty!

O.k. I'm better now.. But really I tried to select a brush; hoping I could Assign Material that way. Well, no not happening..

**Comment by LogicalError** [comment]
Hi!
I'm a bit confused with what you're saying.. 

You can assign materials to your models any time you want .. before or after performing CSG with your brushes.. 

You can just drag & drop your materials onto the surfaces you want to change. 

I haven't tried the asset you've linked there, but judging from the screenshots & videos it looks like it does exactly what realtime-CSG is doing, material wise ... am I missing something?

**Comment by Cyber2017** [comment]
About the Materials...  Actually what I meant was 2 different ways,  so yes both before and after perform CSG on brushes.. Anyhow my biggest problem was trying to drag my material onto the brush, for some reason it hasn't been working (not without pulling hair out lol) 

The other Way (before CSG subtract ex:) 

Let's say that my brush has a green metallic material already on it,  so after I perform a subtraction,  I  want that material cut out of the  model.. Perhaps if you try boolean ops; you'll see what I mean..

**Comment by Cyber2017** [comment]
Also, if there's a trick to drag material from my unity_Materials folder onto a brush..  Let me know, TY! 
OH,  and yes I found the Scale by enter #,  ex: 3, 6, etc..  I appreciate that :D

**Comment by Cyber2017** [comment]
I'll try to explain better about this.. K, so if I pick a brush from the "Hierarchy" (NOT! From the Scene View)
/ I would than pick a Material from my _Materials folder
/ Drag the Material onto the same brush I selected in the "Hierarchy" (Why?) Cause it's easier & no fuss like trying to pick by using the scene clicking in or whatever.. Anyway I tried to do this and I get a "block" symbol over my mouse pointer... Or, if I try to drag material onto your Surface window it just Vanishes..

**Comment by LogicalError** [comment]
Ah ok, now I understand, you want:
1. to be able to drag & drop a material onto the brush in the hierarchy window
2. to be able to drag & drop a material onto the surface window
correct?

**Comment by Cyber2017** [comment]
I almost forgot, when I meant drag onto brush..  I meant when I select brush in the Hie

**Comment by Cyber2017** [comment]
Sorry about that,  I clicked close issue by mistake ..  OK,  yes exactly correct.  I find it easier to dabble with materials early, that way you can always change them later, simple and a quick way to prototype.

**Comment by Cyber2017** [comment]
Now,  not saying that your implemented way of doing this isn't effective but rather in alot of my stuff,  it's better to coat the brush right away than Ex: carve intricate shapes out of your model (surfaces) coated straight away.

**Comment by LogicalError** [comment]
Almost forgot: if you drag & drop a material on a brush while holding shift it'll assign the material to all surfaces on the brush..
I'll look into the other drag & drop thingies :)
thanks for the feedback :)

**Comment by Cyber2017** [comment]
For example, I'm working on a maze block and I want to carve out grooves (To give that protruded stone block) look..  But,  as I have no way that I know yet to coat the carving brush lol... 
I have to click in the scene, try somehow to select amongst the stuff to hopefully get that whole area that I just carved out :D
Anyhow,  I  appreciate again the effort you've put into this Excellent tool!

**Comment by Cyber2017** [comment]
"Almost forgot: if you drag & drop a material on a brush while holding shift it'll assign the material to all surfaces on the brush.."

K, trying that now. Seems to pick only the outside brush but not the brush I "Subtracted"
EX: I'll Attach a pic of a test Model that shows the "Shift" drag over brush 1 /perfect
it did texture brush 1

Problem now, is picking brush 1,2
![capture](https://cloud.githubusercontent.com/assets/22611869/19092691/a52f9d8e-8a3c-11e6-8543-e2c3d347d40d.PNG)

**Comment by LogicalError** [comment]
Well you are dragging over the brush in the sceneview, right? I'm not sure how you can only get brush1 getting picked .. unless you mean this is just an example and you're trying to illustrate that when brushes overlap it's impossible to assign materials to the brush, then sure ... 

I am going to look into this, but I'll be away the rest of the week so it'll be after that

**Comment by Cyber2017** [comment]
Hi..  Yes very true,  as I noticed that you can only drag the material into the Scene view; onto the brush
/ however I disable brush 1 in the hierarchy like you would normally for any other game object.. This makes it so I can actually select either brush 2 or 3..
The pictures are just an example of me playing around with the brushes, I was inventing ways to expose only the brush of interest,  so I could assign materials.. 
There is definitely a problem in the scene view trying to isolate the inner brush by dragging a material over the inner brush (see the photo)

**Comment by Cyber2017** [comment]
I had no problem dragging my material over the large box but,  as soon as I tried to drag the material over the other two brushes; no luck ever.. Very frustrating indeed!
I think if you can implement a way for us to actually drag our material from our_materials folder / onto any brush in the Hierarchy (Not in Scene window) 
This would be a 100% improvement in the Surfaces methods :D

**Comment by Cyber2017** [comment]
Again,  with all that aside... I really enjoy this incredible!!  CSG Asset package. I'm actually re- modelling every single Maze block in my New Game :)  I also noticed that you update your betas quickly which shows me serious commitment to your Asset..

**Comment by LogicalError** [comment]
Version 1.303 that's available on the beta site allows you to drag & drop materials on brushes in the hierarchy! 
... and glad to hear that you like Realtime-CSG ;)
I'll add dragging to surface window later, so won't close the ticket until that's done.

**Comment by Cyber2017** [comment]
Awesome TY! yes it's much easier now to Assign Materials onto the brushes. :D I'm also using the Newest Version 1.307

**Comment by LogicalError** [comment]
This has been completed in version 1.350 (can now drag on material in surface tool). Which can be downloaded from https://prenominal.nl/updates/
This ticket will be closed when this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available from the asset store, so I'm closing this ticket
