### ISSUE TITLE
Compiling warnings in Version 1.351 on Unity 5.5.0f2

### ISSUE THREAD

**Issue by mrkool55** [LogicalError/realtime-CSG-for-unity#162]
After installing realtime-CSG-for-unity, and selecting "I Made A Backup, Go Ahead!" on the "API Update Required" dialog.  I get these errors:

Assets/Plugins/RealtimeCSG/Editor/Scripts/Helpers/TooltipUtility.cs(52,17): error CS0649: Warning as Error: Field `RealtimeCSG.TooltipContentState.currentToolTipTitleArea' is never assigned to, and will always have its default value

Assets/Plugins/RealtimeCSG/Editor/Scripts/Helpers/TooltipUtility.cs(53,17): error CS0649: Warning as Error: Field `RealtimeCSG.TooltipContentState.currentToolTipContentsArea' is never assigned to, and will always have its default value

Assets/Plugins/RealtimeCSG/Editor/Scripts/Helpers/TooltipUtility.cs(54,17): error CS0649: Warning as Error: Field `RealtimeCSG.TooltipContentState.currentToolTipKeyCodesArea' is never assigned to, and will always have its default value

To fix these I made this change to TooltipUtility.cs after line 366

				currentState.tooltipArea = newArea;

				currentState.currentToolTipTitleArea = newArea;
				currentState.currentToolTipContentsArea = newArea;
				currentState.currentToolTipKeyCodesArea = newArea;

so those Rect's had a value.  I don't know if this is right, but it allows me to run the tool now.

MrKool55

**Comment by LogicalError** [comment]
Ah ok, I'll take a look at it. The auto upgrade is apparently because something changed between 5.5.0 and 5.5.0p2. Thanks for reporting this

**Comment by LogicalError** [comment]
This has been fixed in version 1.352 which can be downloaded from the update site: https://prenominal.nl/updates/
I'll close this ticket once this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available from the asset store, so I'm closing this ticket
