### ISSUE TITLE
Snapping don't work with brush

### ISSUE THREAD

**Issue by TimNedvyga** [LogicalError/realtime-CSG-for-unity#163]
Snapping only works with created brush, but it's not while I generate new brush.
[Here the video](https://www.dropbox.com/s/2yq769l0yhz8x27/Unity%205.5.0f3%20Personal%20%2864bit%29%20-%20Scene.unity%20-%20Modeling%20-%20PC%2C%20Mac%20%26%20Linux%20Standalone_%20_DX11_%2024.01.2017%2013_10_43.mp4?dl=0)

**Comment by LogicalError** [comment]
This should be fixed in Realtime CSG 1.357! Let me know if it didn't fix this. You can find the updates here: https://prenominal.nl/updates/
