### ISSUE TITLE
Texture lock

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#165]
One feature I really love from the Hammer world editor is the texture lock button. By default texture UVs are calculated from the objects world position, or you can use this button to lock the texture UVs when moving a brush (which is by default how RealtimeCSGs UVs are calculated?). The majority of the time I would prefer UVs to be aligned to the world like in the image below:

![hammer_tl](https://cloud.githubusercontent.com/assets/22818547/22338971/88210f18-e3e0-11e6-9986-a87c465ed14a.gif)

**Comment by LogicalError** [comment]
I realized I didn't write a response ;) I'm working on it, so should be part of next version

**Comment by LogicalError** [comment]
This has been implemented in version 1.358 which is available from the update site:
https://prenominal.nl/updates/
More information can be found here
https://prenominal.nl/forum3/showthread.php?tid=49
When this version is available from the asset store I'll close this ticket

**Comment by Drexen** [comment]
Thanks for getting this implemented. It would be great if this was a global setting and not per-object. The majority of the time I would like to build with texture lock disabled for all faces.

**Comment by LogicalError** [comment]
This is a bit tricky because to be able to turn off the texture lock all surfaces of all brushes need to be modified to go from one texturing mode to another ..
Maybe it makes sense to add some functionality to select all surfaces on all brushes, so you can set/unset the lock that way?

**Comment by LogicalError** [comment]
How about a default "texture lock" value? So that every time you build a brush, the texture lock is turned off by default? Would that work for you?
