### ISSUE TITLE
Grid snapping not working when generating meshes

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#166]
[RealtimeCSG Grid Snapping](https://www.youtube.com/watch?v=_Q285OHPs5I)

Or am I missing something?

**Comment by LogicalError** [comment]
I think that was a bug in 1.356 that should be fixed in 1.357 .. can you try 1.357 and see if that fixes this for you?

**Comment by Drexen** [comment]
You are correct. That fixed it.
