### ISSUE TITLE
Split geometry & textures

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#167]
![csg_split](https://cloud.githubusercontent.com/assets/22818547/22404621/a9f83744-e62c-11e6-902b-0591fa881dee.jpg)

When you split a piece of geometry the new faces automatically apply the RealtimeCSG dev material. It would be nice if it would take a material that is already being used on the geometry.

**Comment by LogicalError** [comment]
Well if you have multiple materials it might pick the wrong one .. It would be somewhat random
Maybe it could pick the material of the side you draw the split plane on? Or maybe something like, it would pick the last selected material in unity?

**Comment by Drexen** [comment]
![hammer_active_texture](https://cloud.githubusercontent.com/assets/22818547/22424237/9728764e-e6ed-11e6-8d21-8d1bb3d73cfe.jpg)

Again back to SourceSDK, they have a pane showing your active texture. Something like that might be nice.

**Comment by LogicalError** [comment]
That sounds like a good idea :)

**Comment by LogicalError** [comment]
Setting the default texture is now implemented in 1.402!
I will close this ticket once that version is on the asset store

**Comment by LogicalError** [comment]
This version is now available on the asset store, so I'm closing this ticket
