### ISSUE TITLE
Trigger remains visible after hiding (full rebuild fixes it)

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#169]
[Video](https://www.youtube.com/watch?v=3k1fNtspmsY)

Quite simple. Hiding a trigger model causes the brush to remain visible, requiring a rebuild to hide it properly.

**Comment by LogicalError** [comment]
I'll investigate, thanks for reporting!

**Comment by LogicalError** [comment]
This is fixed in Realtime CSG 1.359! 
You can find the updates here: https://prenominal.nl/updates/
There is some more information here: https://prenominal.nl/forum3/showthread.php?tid=52
