### ISSUE TITLE
[Request] More primitive shapes... 

### ISSUE THREAD

**Issue by Cyber2017** [LogicalError/realtime-CSG-for-unity#17]
If possible,  Add pyramid and other cool shapes.. The Box shape and Cylinder are working very well :)

**Comment by LogicalError** [comment]
I'll see what I can do. I'm definitely planning on enhancing the shapes over time. For example, I want to add the ability to create curves w/ the free-draw shape + extrude squares, cylinders and free-draw shapes over a curve instead of just in one direction.

**Comment by Cyber2017** [comment]
Thanks, Ya that would be cool.  At least we can cut shapes from other brushes which helps.  :)

**Comment by LogicalError** [comment]
related to #112
