### ISSUE TITLE
Deselecting 'Create Rigidbody' does not remove component

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#170]
![realtimecsg_create_body](https://cloud.githubusercontent.com/assets/22818547/22428313/7fffc4c0-e6fe-11e6-8736-175dc106123d.jpg)

Deselecting 'Create Rigidbody' does not remove the Rigidbody component from the game object

**Comment by LogicalError** [comment]
I guess this is a bit of a misnomer .. "Create RigidBody" is more like .. "Automatically create rigidbody"
When you deselect it, you can still add or remove your own ..

**Comment by LogicalError** [comment]
I changed this so that there is an option that's called "Auto Rigidbody" which automatically creates or destroys the rigidbody and updates it's settings. If you turn it off you can do it manually
