### ISSUE TITLE
[Request] Triangle Primitive

### ISSUE THREAD

**Issue by FirefightGI** [LogicalError/realtime-CSG-for-unity#171]
I would love to see a triangular prism primitive! I have been using the clip tool to cut off corners, but it would be so much easier to keep cuts the same size and even make corners if I had a triangle primitive that I could generate.

Also any thought about a mirror/symmetry mode?

Thanks!

**Comment by LogicalError** [comment]
Prism primitive could be useful .. although strictly speaking the cylinder could be set to 3 sides and that would already be a prism?

What exactly do you mean with mirror mode? To me it sounds like the clip tool, only that you mirror over the plane instead of clipping with it?

**Comment by FirefightGI** [comment]
I didn't realize you could set the number of sides on the cylinder (hadn't used it yet), that will work just fine.

By mirror I meant have something like the clip tool mark an area and have anything you do on one side happen on the other side symmetrically yes.

**Comment by LogicalError** [comment]
Hmm, that is a bit more involved.. I was talking about selecting objects and then mirroring them over a plane. I think you're talking about editing objects and mirroring them over a plane at the same time

**Comment by LogicalError** [comment]
I've made a seperate ticket for the mirroring, to avoid confusion https://github.com/LogicalError/realtime-CSG-for-unity/issues/182
