### ISSUE TITLE
How to make a hole by hollowing in the cylinder

### ISSUE THREAD

**Issue by KuniyasuYakusiji** [LogicalError/realtime-CSG-for-unity#172]
I could arrange two cylinders and cut through the inside, but when placed on the Cube, the inside of the cylinder will not be transmitted. I would like to make something like a "hole" placed on the Cube. It is like falling if things go into the hole. Please tell me how to penetrate through the hole.
Thanks.

**Comment by LogicalError** [comment]
This depends on the order of both cylinders and the cube.
Imagine that all the adds and subtractions happen in order from top to bottom in the hierarchy.
So in this case, you'd want the subtractive cylinder be below the cube in the hierarchy.
Does that help?

**Comment by KuniyasuYakusiji** [comment]
Hi.

Problem solved with Mesh Collider. Thank you very much.

Kuniyasu

**Comment by LogicalError** [comment]
Oh you where talking about collision detection!
Sorry, I misunderstood
Good to hear you figured it out :)
