### ISSUE TITLE
'Z' key doesn't change movement axis anymore

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#179]
Hey Sander, just trialling your tool again after a couple of months, so I'm not sure when exactly this started being an issue, but the hold-Z-to-move-on-Y-axis function isn't working. The D-duplicate key works fine though.

Platform: OSX
Unity version: 5.5.2p4 Personal
RCSG Version: 1.403

**Comment by LogicalError** [comment]
Hi, I kind of removed it since it seemed to confused users .. (not to mention that the Z key conflicted with a built in unity function)
I replaced with being able to use the standard unity move gizmo if you select something
Is this a big problem for you?

**Comment by AlexanderOcias** [comment]
That makes sense. Honestly neither method is great, the Z-key way is a confusing hassle, and the manipulator way requires pressing a hotkey to go to translate mode, then precisely press a narrow arrow on top of that, neither is fast and intuitive.

I do think this is an important area though, the fast and reliable rate of manipulating brushes using dragging in SabreCSG is one of the main reasons it's still my primary tool for laying out spaces, I really think Sabre's kind of view-based automatic axis selection is the best solution I've seen.

**Comment by LogicalError** [comment]
I'll check out SabreCSG's solution then
