### ISSUE TITLE
[Fix Available 1.304] Multi-scene additive loading

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#18]
Can you confirm if loading multiple scenes additively each with their own CSG brushwork (CSG Model) works correctly? Additionally does realtime lighting work with a lights across different scenes.
Thanks.

**Comment by LogicalError** [comment]
I haven't tried it, but I see no reason why it shouldn't work .. each scene would have it's own model and the brushes will only interact with the brushes in the same model ..
I'll check it out, but I'll be gone next week and probably won't have time until after ...

**Comment by Drexen** [comment]
Here is the test setup I have currently. CSG brushwork from the scene 'test2' is not rendering.

![Scene view](http://i.imgur.com/2p1cBTa.png)
![Game view](http://i.imgur.com/3X6PrIq.png)

I am fairly new to unity so I might be missing something simple here. Thanks for your time.

**Comment by LogicalError** [comment]
Okay, that doesn't seem right. I'll take a look, thanks for reporting this

**Comment by LogicalError** [comment]
Could you sent me your test scene? that would help a lot

**Comment by Drexen** [comment]
I've created a new test project. Hopefuly this zip contains all the files required for you to load the project. It features two scenes that should load on play and another scene that is loaded additively to the game on load.

[CSGMultiSceneTest.zip](https://github.com/LogicalError/realtime-CSG-for-unity/files/529331/CSGMultiSceneTest.zip)

**Comment by LogicalError** [comment]
Ok thanks

**Comment by LogicalError** [comment]
Had to delete that zip file since it included realtime-CSG! ;p

**Comment by Drexen** [comment]
Oh, my bad. Did not realise I would be distributing it's code as well. I presume you can still use that project to test?

**Comment by LogicalError** [comment]
Yeah I downloaded it before I deleted your comment w/ the zip ;p

**Comment by LogicalError** [comment]
Fixed in version 1.304! which is available on the update site ( http://prenominal.nl/updates/index.php )
I'll close this ticket once this version is available on the asset store
