### ISSUE TITLE
Hierarchy icons display wrong color on personal edition

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#180]
<img width="232" alt="screen shot 2017-04-30 at 7 24 42 pm" src="https://cloud.githubusercontent.com/assets/1585507/25563230/c6b77c1e-2dda-11e7-856f-eb7f96d41122.png">

Other info: I have Enhanced Hierarchy installed (but disabled).

Platform: OSX
Unity version: 5.5.2p4 Personal
RCSG Version: 1.403

**Comment by LogicalError** [comment]
Hmm, that's strange .. it shows up correct for me?
Does it still show up wrong after restarting Unity?
Maybe some settings aren't reset when changing the skin?

**Comment by AlexanderOcias** [comment]
Yep, fresh project and restarting Unity, same issue.

I don't have plus/pro, so I can't change the skin.

**Comment by LogicalError** [comment]
Okay, this is getting mysterious. 
I started up the exact same version of Unity, with the exact same version of realtime-CSG and it shows up correctly for me. 
The part of the code that decides which version of the Icon to show literally calls a Unity method to check if it should show the pro or personal version of the icon ...?

**Comment by AlexanderOcias** [comment]
Investigated this a bit:
- Does not occur on Unity 2017.1.0b1
- Appears to be an issue with the alpha channel being ignored for some reason (not related to Personal/Pro skins)
- Switching the compression setting on the icons to "High Quality" fixes the issue (but causes some other annoyances of course)

**Comment by LogicalError** [comment]
huh .. so it could be the texture settings that *somehow* are different in your installation compared to when I installed it locally .. that's weird
thanks for the feedback, I'll see if I can figure out what might've gone wrong
