### ISSUE TITLE
Consider avoiding F-keys for default hotkeys on OSX

### ISSUE THREAD

**Issue by AlexanderOcias** [LogicalError/realtime-CSG-for-unity#181]
Just noticing some very common functions are bound to F-keys (Edit mode switching, turning RCSG on/off). This is pretty unusable on Macs, and most users will need to re-bind. Mac keyboards have F-keys hidden behind an Fn key layer, and even then more system shortcuts tend to be bound to the F-keys themselves, so it's very unusual to see software that uses them.

It might be worth thinking about changing those default bindings, at least for Mac installations.

Platform: OSX
Unity version: 5.5.2p4 Personal
RCSG Version: 1.403

**Comment by LogicalError** [comment]
Hmm .. well that's a bit of a problem since the keyboard is getting rather crowded at the moment. So many keys are already used by unity and other realtime-CSG functionality
I'm assuming, since you mention re-binding, that you know that you can change the keys in the preference menu? If you changed these keys, what did you set them to?

**Comment by AlexanderOcias** [comment]
Yep, I do know about the preference menu, but no, I haven't investigated what to change them to at this stage.

**Comment by LogicalError** [comment]
Turning RCSG on/off at the very least also has a menu, edit mode switching is trickier.. 
What about 'command + number' as an alternative to function keys?

**Comment by AlexanderOcias** [comment]
If possible it would be pretty good, but although I've never used the combo, Command + number is used for giving focus to a particular panel by Unity defaults. (sorry about the late reply)

**Comment by LogicalError** [comment]
So what key combo would you like to have then? ;p
