### ISSUE TITLE
Add uniform scaling in object mode

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#183]
"Uniform scaling would be nice since there's no easy way to achieve given the current controls. It'd be nice to be able to shift-click on a side and have it scale along that axis uniformly. Shift-click a corner for two axes maybe have a center point appear for 3 axes scaling which would be useful for indicating a mode change. This shift to change behavior would be in line with what you have for chamfering edges and verts"

**Comment by Kerfuffles** [comment]
This can now be done using the Rect Transform tool
