### ISSUE TITLE
Problems when using 'native' API

### ISSUE THREAD

**Issue by ArthurBrussee** [LogicalError/realtime-CSG-for-unity#184]
This issue is a little different so thanks for baring with me in advance :)

Some backstory: I'm working on a game called Manifold Garden (http://manifold.garden/). Most of the levels are laid out already so we don't need CSG for workflow purposes.

Instead levels are laid out as a _lot_ of boxes (essentially). I'm sure that was convenient at the time. The problem now is that there are many hidden faces and vertices that are just wasting performance.

Therefore, the idea was to use CSG to take all these boxes, take them through CSG and have it spit out an optimised mesh!

To avoid the overhead of spawning thousands of brushes and such I'm instead trying to interface with the C++ interface directly to generate a mesh. After some modifications to make some things public I can access this API fine! Going over the normal code I have tried to recreate the code path a 'normal' CSG model would go through. 

I must be missing some stuff however - I get either a mesh with 0 vertices or just a hard crash. I've attached a file of the  current script which is trying to use the API. I'm sure I must be misunderstanding how the C++ interface works.

Any help would be super appreciated! Especially since I understand this isn't a usual request ;)

[LevelBuildPrepCSG.zip](https://github.com/LogicalError/realtime-CSG-for-unity/files/1069192/LevelBuildPrepCSG.zip)

**Comment by LogicalError** [comment]
Well the native part was never designed to be used directly by users .. 
I'd like to be able to modify the native code interface any time I need to, if people start using this that makes this a lot harder .. 

Just quickly looking at the code I noticed that you're not setting the material count for the model
(InternalCSGModelManager.External.SetModelMaterialCount)

Is there a quick way to repro the crash you get?

Also keep in mind that the last return generated mesh contains the invisible polygons, which is only used internally. This is something in the native 'API' that will probably be reworked at some point.

**Comment by LogicalError** [comment]
Note that a runtime API would need support for something like this (generate code from code, without needing brushes), so _eventually_ I'll have proper support for this

**Comment by pvloon** [comment]
Thanks for quick reply! I totally understand that these functions are not supposed to be public and that I'm abusing the system a bit. It's just that four our particular niche use case that happens to be really convenient. But yeah, I don't expect official support for this. 

I've fiddled around with it some more (eg added the call to SetModelMaterialCount) and can get it to run beyond RebuildAll now. However, still no vertices are generated (and wihout a manual check for vertexCount == 0 before FillVertices unity crashes).

I've attached a project with necessary modifications and code. Open RandomCubes.unity and press play. 

I'm hoping I've just missed some obvious external calls, but if there is no good way to have CSG spit out meshes atm I'll have to find a way around.

Thanks again for taking a look!

[CSGTest.zip](https://github.com/LogicalError/realtime-CSG-for-unity/files/1069491/CSGTest.zip)

**Comment by LogicalError** [comment]
I removed the file from your comment because it contained Realtime CSG, please be careful with that!
I'll take a look

**Comment by LogicalError** [comment]
Ok, fixed crash in local version. Seems like you're also missing a call to ModelMeshNeedsUpdate, which counterintuitively actually generates the mesh .. 
like I said, this 'API' was never meant to be used by users ;p

**Comment by LogicalError** [comment]
Ok, a new version is up on the update site that fixes that crash you where having. Note that I noticed that the native 'API' has already changed compared to the code in file you sent me

**Comment by pvloon** [comment]
Woops you're right, sorry for posting that file, I'll be more careful.

And thanks again for all the help! The call to ModelMeshNeedsUpdate (and some other fixes) seem to have improved it a lot. It generates actual meshes now which seem alright!

On second glance however the meshes it now generate still aren't quite right:

![image](https://user-images.githubusercontent.com/7014262/27157828-e59d0f0c-5163-11e7-8db7-15d059dfa4d8.png)


Left are actual realtime CSG brushes, right is simple output if I run the code. It seems like it is not recognizing the brushes to be of the same hierarchy.

I have tried all kinds of combinations to calling  SetBrushHierarchy, UpdateNode, SetModelChildren ed but no luck so far. Any ideas as to why it's not picking up on the hierarchy?

Sorry I know this is a bit of an annoying 'feature request' but it could really potentially be amazing for the game. Thanks so much and let me know if you would like an updated version of the test and where I could send it.

**Comment by LogicalError** [comment]
Can you sent me what you have so far so I can debug it? (through email, see the top-right corner of https://logicalerror.github.io/)
It looks like somehow it thinks the cubes don't intersect

**Comment by LogicalError** [comment]
This should fix it for you
[LevelBuildPrepCSG.zip](https://github.com/LogicalError/realtime-CSG-for-unity/files/1080541/LevelBuildPrepCSG.zip)

The objectToPlaneSpace/planeToObjectSpace matrices weren't calculated correctly so the planes of a brush that cut the other brush weren't placed correctly and 'missed' the other brush. Also SetBrush had the objectToPlaneSpace/planeToObjectSpace parameters swizzled ;)

**Comment by LogicalError** [comment]
FYI; there's an official native API now in 1.517. It's a bit WIP, but it shouldn't change much.
