### ISSUE TITLE
[Bug] Cannot change the snapping settings when the "Edit modes" bar is a panel tab

### ISSUE THREAD

**Issue by Alcarendor** [LogicalError/realtime-CSG-for-unity#186]
Using the version 1.408, I cannot enter manually the numbers of the snapping settins while the "Edit Modes" bar/menu is in the "tab form". But I can  #still change the valors using the buttons.

**Comment by LogicalError** [comment]
Yeah Unity doesn't really play well with the scene-view "bottom bar".. 
That said, at a cursory glance, it works fine for me in Unity 5.4 .. what Unity version are you on?

**Comment by LogicalError** [comment]
I just realized you said that this happens when edit modes is in the "tab form". And yes, then it, somehow, doesn't show visual feedback that you've selected a numerical text field in the bottom bar ... you can still type numbers however .. it's just not colored differently for some reason
