### ISSUE TITLE
Add tessellation options for mesh generation

### ISSUE THREAD

**Issue by jhhoward** [LogicalError/realtime-CSG-for-unity#187]
It would be extremely useful to provide tessellation options for mesh generation to help shaders that rely on per-vertex calculations (e.g. Google Daydream renderer or simple vertex lit)

For example, an option to specify a maximum triangle edge length. A post process could be applied to the mesh which inspects the length of each triangle edge, and splits edges which are greater than the given maximum and generates extra triangles accordingly.

**Comment by LogicalError** [comment]
I'm not familiar with Google Daydream development, why does it need tesselation?

**Comment by jhhoward** [comment]
Google developed a set of shaders and lighting system that they call Daydream Renderer:
https://developers.google.com/vr/unity/renderer

To make it more efficient for mobile devices, some of the lighting calculations are done in the vertex shader or baked offline and stored in the mesh vertex color, and then interpolated across the triangle. If triangles are too large then there are noticeable errors in the lighting. 

You can see similar lighting errors / artifacts with Unity's built in vertex lighting shader too, where the problems are reduced with more tessellated meshes.

Ideally it would be best to only split up large triangles instead of subdividing every triangle in the mesh to provide an even mesh density.

**Comment by LogicalError** [comment]
Ok, thanks
Is it important if the subdivisions are axis aligned, or is the edge distance more important?

**Comment by jhhoward** [comment]
Good question. Axis aligned may give more uniform results for large planar surfaces so that might be preferable.
