### ISSUE TITLE
[Request] Moar tutorials!

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [LogicalError/realtime-CSG-for-unity#19]
Hey, just bought the tool.
Pretty easy and awesome, but I think it needs a bit more tutorials. For example, a page with all hotkeys or some videos with workflow & tips would be helpful.
Thanks!
Hey, just bought the tool.
Pretty easy and awesome, but I think it needs a bit more tutorials. For example, a page with all hotkeys or some videos with workflow & tips would be helpful.
Thanks!

**Comment by LogicalError** [comment]
Hi!
Pages with shortcuts & tips should be easy to do, workflow will take a bit more time I think. I'll see what I can do

**Comment by LogicalError** [comment]
I added https://logicalerror.github.io/tips.html and https://logicalerror.github.io/keyboardlayout.html to the website, I'll add more over time
