### ISSUE TITLE
Compiling Loop with VRTK Imported

### ISSUE THREAD

**Issue by NightHammer1000** [LogicalError/realtime-CSG-for-unity#192]
I have this Issue that Unity wont stop Compiling with Realtime CSG and VRTK in the same Project.

Problem is reproduceable. On 3 diffrent PCs with diffrent Unity Versions.

Testet are 2017.1.0f1 and 5.6.2f1

**Comment by LogicalError** [comment]
Oh, that's weird, I'll take a look but that sounds like a Unity bug?
Thanks for letting me know

**Comment by NightHammer1000** [comment]
Looks like it: https://issuetracker.unity3d.com/issues/changes-to-scripts-cause-infinite-compilation-times-after-playing-a-scene

**Comment by LogicalError** [comment]
Ah ok, well then there's nothing I can do about this then, sorry :-/
I'll close the ticket

**Comment by NightHammer1000** [comment]
Under 2017.2.0b5 i get the following Error in the same Scenario:

`Exception: Must set an output directory through SetCompileScriptsOutputDirectory before compiling
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.GetCompileScriptsOutputDirectory () (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:126)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.CreateScriptAssemblySettings (BuildTargetGroup buildTargetGroup, BuildTarget buildTarget, EditorScriptCompilationOptions options) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:572)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.CreateEditorScriptAssemblySettings (EditorScriptCompilationOptions options) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:584)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.GetAllScriptAssemblies (EditorScriptCompilationOptions options, UnityEditor.Scripting.ScriptCompilation.PrecompiledAssembly[] unityAssembliesArg, UnityEditor.Scripting.ScriptCompilation.PrecompiledAssembly[] precompiledAssembliesArg) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:773)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.GetAllMonoIslands (UnityEditor.Scripting.ScriptCompilation.PrecompiledAssembly[] unityAssembliesArg, UnityEditor.Scripting.ScriptCompilation.PrecompiledAssembly[] precompiledAssembliesArg, EditorScriptCompilationOptions options) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:784)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.GetAllMonoIslands () (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:779)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface.GetAllMonoIslands () (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:187)
UnityEditorInternal.InternalEditorUtility.GetMonoIslands () (at C:/buildslave/unity/build/Editor/Mono/InternalEditorUtility.cs:386)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.CompilationUnits (System.String method)
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.CompilationUnits ()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectSystem.UnitySolutionBuilder..ctor ()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectSystem.UnitySolutionBuilder.CreateSolutionFromAssetDatabase ()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilesGenerator.GenerateProject ()
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilePostprocessor.OnPreGeneratingCSProjectFiles ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.OnPreGeneratingCSProjectFiles () (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:61)
UnityEditor.VisualStudioIntegration.SolutionSynchronizer.Sync () (at C:/buildslave/unity/build/Editor/Mono/VisualStudioIntegration/SolutionSynchronizer.cs:186)
UnityEditor.SyncVS.SyncVisualStudioProjectIfItAlreadyExists () (at C:/buildslave/unity/build/Editor/Mono/SyncProject.cs:165)
UnityEditor.PlayerSettings:SetScriptingDefineSymbolsForGroup(BuildTargetGroup, String)
RealtimeCSG.SceneViewEventHandler:UpdateDefines() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/SceneViewEventHandler.cs:132)
RealtimeCSG.SceneViewEventHandler:Initialize() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/SceneViewEventHandler.cs:65)
RealtimeCSG.SceneViewEventHandler:.cctor() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/SceneViewEventHandler.cs:26)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()`

**Comment by LogicalError** [comment]
Well at least it's better than nothing .. still weird that this is happening at all :-/
