### ISSUE TITLE
[Bug] In playmode, all surfaces of one material disappear

### ISSUE THREAD

**Issue by Petethegoat** [LogicalError/realtime-CSG-for-unity#193]
I'm afraid I don't have too many details yet to share, and no repro case yet.

I have a very small project with a couple other assets imported (main one that I could potentially see interfering is Odin Inspector & Serializer, but idk), and all was working as expected. Randomly when I went into playmode all surfaces of one material disappeared. The material is just legacy bumped diffuse, nothing special.
Restarting Unity and reimporting all assets didn't help, and that material has consistently been missing, despite always showing up correctly in editor mode.
It is the actual geometry, collision and rendering, that is missing, by the way. It doesn't show up in the shadowmap either.

**Comment by Petethegoat** [comment]
![Editor mode](http://i.imgur.com/CQPMFmB.png)
![Play mode](http://i.imgur.com/oa1e3MU.png)

Editor and play mode from the scene view. Ignore the baked lightmaps, realtime lights don't show any geo.

**Comment by Petethegoat** [comment]
Oh, the one thing I've just noticed is the gate also disappears, despite being just a regular model, and totally unconnected to the CSG geo. This could be a Unity bug instead, but the gate and the wall don't share materials, so idk.

**Comment by Petethegoat** [comment]
Sorry for spamming comments. I noticed a disabled brush in my model. Deleting that seemed to fix the issue for me. Adding a new brush and disabling it didn't return the problem though.

I can still put some time towards trying to repro at some point, though.

**Comment by LogicalError** [comment]
Hi, yes a repro would be nice :)
That way I can make sure it doesn't happen again

sorry for the late reply, I was on vacation .. but I'm back!

**Comment by LogicalError** [comment]
Could it have been that that deleted brush had an Intersection operation? which would've removed all other brushes that didn't touch it?

**Comment by Petethegoat** [comment]
Unless I changed it to intersection accidentally, no.

In a more recent project on 1.500 I haven't had this issue show up yet.

**Comment by LogicalError** [comment]
Ok, well let me know if it re-surfaces ..
