### ISSUE TITLE
Warnings Post Asset Removal

### ISSUE THREAD

**Issue by FirefightGI** [LogicalError/realtime-CSG-for-unity#194]
Hello, I removed Real-time CSG from my Unity project (into another to keep main and art pipelines separate) and encountered 2 bugs:

1) When deleting the asset from inside the Unity project window I would get errors saying that some materials couldn't be deleted and the editor folder would be regenerated. I got around this by deleting it from my computers file browser while Unity was closed.

2) Now that Real-time CSG has been removed from the projects I get warnings in console when I press play that don't lead to a script or anything in the hierarchy when clicked. They seem to be related to Real-time CSG, I also don't have any CSG models in the scene.

I get 16 of these warnings:
The referenced script on this Behaviour is missing!
The referenced script on this Behaviour (Game Object '[model-mesh] Model') is missing!
The referenced script on this Behaviour (Game Object 'New Game Object') is missing!
(searches for [model-mesh] Model in the hierarchy find nothing) 

and there is no way to tell from the warnings themselves where they are coming from.

Can you try making some models in a scene, removing the asset then close and load Unity again, delete the models you made from the scene's hierarchy and see if you get the same warnings?

**Comment by FirefightGI** [comment]
I disabled all GameObjects in the scene and still get the warnings in console, could editor meta data cause warnings like this?

**Comment by LogicalError** [comment]
There are some hidden gameobjects in the scene that hold, for instance, all the generated meshes for the models. So if you load a scene with Realtime-CSG stuff in a project that doesn't contain Realtime-CSG it'll try to use certain scripts on those hidden gameobjects that don't exist in that project, and that's what you're running into at the moment. This is what causes the "behaviour is missing" things

I don't know what the material thing is about, I don't know how this is related to realtime-CSG? It sounds like it's something else..
