### ISSUE TITLE
assign material problem

### ISSUE THREAD

**Issue by tianbuliang** [LogicalError/realtime-CSG-for-unity#195]
hi，i know we can select the brush and set the material for each surface. But currently i build a level use about thousands of brushs using defualt material. And now i decide to change the material of them. each brush has the same material. set some of them  to white ,  set  some of themto black, set some of them to red for example. that's too much work. 

so what i want is to costomize the inspector of brush, i can select mutilple brushes drag and drop the material.  and they all be changed. it can save me a lot time.

**my question is how to set the material of exiting brushes using api?** i read the documentation, but not too much understand.

**Comment by LogicalError** [comment]
So if I understand correctly ..
In the inspector, you want to see all the materials of all the selected brushes.
And then be able to change those materials to something else?

There is no api support for modifying materials at the moment

**Comment by tianbuliang** [comment]
how to access brushfactory's method, even thought i use realtimecsg and internalrealtimecsg as namespace. still show the name "brushfactory" doesn't exist in current context.

**Comment by LogicalError** [comment]
It should be in Assets\Plugins\RealtimeCSG\Editor\Scripts\Helpers\BrushFactory.cs ...
