### ISSUE TITLE
Stitch UVs based on previous surface selection

### ISSUE THREAD

**Issue by DuckyDuckling** [LogicalError/realtime-CSG-for-unity#196]
This is something found in Source, and it makes it amazingly snappy to do your UVs with realtime previewing of your material work.

In SabreCSG you just hold control and shift, and then you can click onto the next face or surface, and it'll stitch the UVs making nice continuities for tiling textures.

In Source it's a control-combination aswell. 

Really hoping something like this can be added, because the UV tools as they are right now are borderline useless for actual production, unless you export and do your own UVs manually, which basically makes this package kind of void as you might aswell do your level geometry in a 3D package.

**Comment by Petethegoat** [comment]
Hold g in surface mode and click from your start point across all the faces you want the texture to flow over.
![smearing example](https://logicalerror.github.io/assets/dragtexgencopy.gif)

**Comment by DuckyDuckling** [comment]
Oh shit, I swear I looked through all of the documentation... Thank you so much though.

**Comment by LogicalError** [comment]
Hmm I probably should add a button to toggle this on and off ;p 
(besides the shortcut key obviously)
That would make it easier to find
