### ISSUE TITLE
Conflict with Unity Grid in 2017.2

### ISSUE THREAD

**Issue by TimNedvyga** [LogicalError/realtime-CSG-for-unity#197]
RealtimeCSG.Grid conflict with Unity grid.
![screen shot 2017-10-04 at 5 42 02 pm](https://user-images.githubusercontent.com/16063002/31182049-831c0084-a92b-11e7-9ea6-4ba1d15c8cea.png)

**Comment by LogicalError** [comment]
There's a hotfix for 1.413 that fixes that, see here: https://prenominal.nl/forum3/showthread.php?tid=87
