### ISSUE TITLE
Placing model inside model causes infinite mesh generation

### ISSUE THREAD

**Issue by VergilUa** [LogicalError/realtime-CSG-for-unity#198]
When I placed accidentaly CSGModel (GO + CSGModel script) inside another CSGModel in hierarchy, it started to generate meshes infinitely, and also caused multiple null-reference missing component exceptions in console. 

This happens on version 1_413_hotfix_2017_2 / Unity version - 2017.2.0f3;.
Worst part it's impossible to remove them without editor tools, since generated meshes are marked with non-editable flag; Had to implement script that deletes all hidden, non-editable gameobjects in editor;

It's great that I can always regenerate meshes via rebuild button after purging :)
But I guess it'll too punishing for someone encountering this one on their first try of RealtimeCSG.

It would be also nice to have some sort of script that allows to move non-model objects on grid, since it's impossible to put model inside model. 

E.g. I've got following hierarchy:

Root (non-CSGModel) + (GridObject)? <- Something to move on grid for this one
  | ___ CSGModel
             |__ Brush...
  | ___ CSGModel 
  | ___ ....
  | ___ CSGModel

It's a bit tedious, selecting all CSGModels inside just to move them properly. And it also messes up object's pivot in editor.

**Comment by LogicalError** [comment]
Hi, I have a fix for the model in model problem, thanks for reporting!
I've created a separate ticket for the "move non csg objects on grid" thing: #202 
I'll close this ticket when this version is downloadable from the asset store

PS. are you aware that there's a newer version available from https://realtimecsg.com/updates/ ?
It'll take a while before it shows up on the asset store

**Comment by VergilUa** [comment]
Woah, 1.5! I'll check it out! Thanks :)

**Comment by LogicalError** [comment]
I just uploaded version 1.502 that fixes the recursive error problem!
I'll close this ticket when this version is downloadable from the asset store
