### ISSUE TITLE
Model fails to set trigger property

### ISSUE THREAD

**Issue by VergilUa** [LogicalError/realtime-CSG-for-unity#199]
CSGModel fails to set "Is Trigger" property properly to generated meshes collider when toggled between "Do not render" flag. 

CSGModel parameters/Physics generation flags:
Generate collider, Is trigger, Convex, phys mat - none.

Version 1_413_hotfix_2017_2;
Unity version - 2017.2.0f3;

**Comment by LogicalError** [comment]
I have a fix in 1.502 which I'll release soon. I'll update this ticket when it's available for download

**Comment by LogicalError** [comment]
I just uploaded version 1.502 that fixes the recursive error problem!
I'll close this ticket when this version is downloadable from the asset store
