### ISSUE TITLE
Changing any brush proprety in one scene marks all scenes as dirty

### ISSUE THREAD

**Issue by VergilUa** [LogicalError/realtime-CSG-for-unity#201]
Title. This is really inconvienient when working in multiscene setup. 

Best solution would be to get GameObject.scene to determine where object is located, and mark only that scene as dirty.

**Comment by LogicalError** [comment]
Hi, this should be fixed in version 1.504 which has just been released on the website https://prenominal.nl/forum3/showthread.php?tid=93
You can download it here: https://realtimecsg.com/updates/
I'll close this ticket once this version is available from the asset store

**Comment by VergilUa** [comment]
Great! Thanks 👍

**Comment by VergilUa** [comment]
It's same behaviour in v1.504. E.g. if I move brush, or rotate it, or center the pivot, all scenes are getting marked as dirty.

Although it's not that important (since nothing changes in scenes, figured even vcs doesn't react to it), but Unity's promt is still asking to save them.

**Comment by LogicalError** [comment]
Ok, looks like there are more situations where this happens .. hmm
It seems that Unity marks all scenes as dirty when calling some of their functions, even when I don't actually change anything in those scenes.
