### ISSUE TITLE
v1.502 Assert Failed

### ISSUE THREAD

**Issue by VergilUa** [LogicalError/realtime-CSG-for-unity#203]
When I try to use v1.502 with previously created brushes I receive following error:
![image](https://user-images.githubusercontent.com/24496266/32979816-ba5bd8a6-cc64-11e7-99d6-876d26a7289d.png)

Also triggered on line 2066, and 2038. 
Can't use the new version because of the messages constantly popping out.

Did someone forget to remove assert? :)

**Comment by LogicalError** [comment]
Hi, no apparently I accidentally compiled in Debug mode instead of Release mode when switching computers. I released version 1.503 to fix this, thanks for letting me know
