### ISSUE TITLE
[Fix Available 1.305] Big points in edit mode

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [LogicalError/realtime-CSG-for-unity#21]
Looks like that dots are not scaling with distance properly:
<img width="586" alt="untitled" src="https://cloud.githubusercontent.com/assets/5061652/19370060/f52dee7c-91b1-11e6-8d71-8a2353d1b41a.png">
<img width="434" alt="untitled" src="https://cloud.githubusercontent.com/assets/5061652/19370072/087a0808-91b2-11e6-8eae-3dc4737e4188.png">

2K display, windows 10, any scaling (tested with 100% and 125%).

**Comment by LogicalError** [comment]
I have not seen this before .. are you zoomed in or out?

**Comment by MarisaLovesUsAll** [comment]
Yes, I'm zoomed in. Some screenshots:
<img width="435" alt="untitled" src="https://cloud.githubusercontent.com/assets/5061652/19380563/71d7b748-9200-11e6-82b6-f06e5ca53143.png">
<img width="446" alt="untitled" src="https://cloud.githubusercontent.com/assets/5061652/19380580/89430aae-9200-11e6-80a7-d80656845bdc.png">
<img width="496" alt="untitled" src="https://cloud.githubusercontent.com/assets/5061652/19380601/9b4b63c2-9200-11e6-845d-1670ba1bf920.png">

**Comment by LogicalError** [comment]
Fixed in version 1.305, which is available on the update site ( http://prenominal.nl/updates/index.php )
I will close this ticket once this is available on the asset store

**Comment by MarisaLovesUsAll** [comment]
Confirm fixed. Thanks!

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket
