### ISSUE TITLE
Add ability to subdivide surfaces

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#213]
see https://forum.unity.com/threads/released-realtime-csg-level-design-for-unity.427601/page-3#post-3124654

**Comment by LogicalError** [comment]
also see https://forum.unity.com/threads/released-realtime-csg-level-design-for-unity.427601/page-3#post-3130768

**Comment by Petethegoat** [comment]
This would also be useful for vertex painted materials, things like ground puddles or the bare bricks in this screenshot from CSGO:
![firefox_2017-11-27_22-17-47](https://user-images.githubusercontent.com/734762/33302345-ea9d8542-d3c0-11e7-8ebe-5261e6f4321c.png)

**Comment by LogicalError** [comment]
Oh I haven't considered vertex painting yet .. good point
