### ISSUE TITLE
[Fix Available 1.306] Selecting/Modifying Hidden Objects

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#22]
Currently it is possible to select and modify (I can apply different textures to) objects that are hidden in the scene view, i.e. hidden via the "Show X Surfaces". It would be ideal if it was not possible to select and modify objects that are hidden from the scene view.

**Comment by LogicalError** [comment]
Hmm .. that sounds like a bug, I'll see if I can reproduce what you're experiencing ... thanks for reporting

**Comment by Drexen** [comment]
More specifically I can select triggers in my level when "Show Trigger Surfaces" is not selected.

**Comment by LogicalError** [comment]
Ok thanks, that'll help me narrow it down 👍

**Comment by LogicalError** [comment]
Clicked wrong button ;)

**Comment by LogicalError** [comment]
Fixed in version 1.306, which is available on the update site ( https://logicalerror.github.io/ )
Once this version is on the asset store I'll close this bug.

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket
