### ISSUE TITLE
Possible to save/load CSG model for further editing

### ISSUE THREAD

**Issue by jmickle66666666** [LogicalError/realtime-CSG-for-unity#224]
Is it possible to add a feature for saving the CSG model in a format to reload for editing later?

I would like to be able to save and reload different models without having to save the scene separately.

**Comment by VergilUa** [comment]
You mean like... prefabs?

**Comment by LogicalError** [comment]
Yes, prefabs is the way to re-use parts of CSG scenes ... you could also use multi-scene editing perhaps, depending on your needs.
Prefabs can be drag & dropped into the scene w/ realtime feedback

**Comment by jmickle66666666** [comment]
Ah cool I'll do that, thank you both!
