### ISSUE TITLE
Rotation handles issue [v.1.509]

### ISSUE THREAD

**Issue by VergilUa** [LogicalError/realtime-CSG-for-unity#226]
In rotation (Unity's "E") object (RealtimeCSG Alt+F1) mode, rotation handles often doesn't appear when hovered mouse on the edge of object's wirebox. This started happening only in this version.

In this cases modified pivot of the model is not saved either.

RealtimeCSG - v.1.509
Unity v.2017.2.0f3

**Comment by VergilUa** [comment]
Upgraded to v2017.3, with Realtime CSG v1.509 for 2017.3, still same behaviour.

**Comment by LogicalError** [comment]
Ok thanks for letting me know, I'll take a look at this at the start of the new year (don't have time until then due to family obligations)

**Comment by LogicalError** [comment]
As a quick suggestion, note that you can rotate in both object and mesh mode, if it doesn't work in one mode, it might in the other mode?

**Comment by VergilUa** [comment]
I've just used default transform -> change value method. Haven't tested in mesh mode though.

**Comment by LogicalError** [comment]
I just released version 1.510, this problem should be fixed there!
I'll close this ticket when this version arrives on the asset store

**Comment by LogicalError** [comment]
and you can, of course, download it here in the meantime: I'll close this ticket once it arrives on the asset store, in the mean time you can download it here: https://realtimecsg.com/updates/
