### ISSUE TITLE
Use Rotation Pivot as FBX Center Point on export

### ISSUE THREAD

**Issue by otdavies** [LogicalError/realtime-CSG-for-unity#227]
Currently when I switch a creation into FBX, the pivot gets reset to center of mass. I'd prefer to use the rotation pivot (as an option?). This change will let me create mechanisms with custom pivots etc.

**Comment by LogicalError** [comment]
I'll take a look at what's going on, thanks for reporting

**Comment by LogicalError** [comment]
New functionality has been added to 1.510 that addresses this, it allows you to explicitly set the model centering behavior
I'll close this ticket once it arrives on the asset store, in the mean time you can download it here: https://realtimecsg.com/updates/
