### ISSUE TITLE
Incorrect operation when generating inside subtracted rooms with inverted world on

### ISSUE THREAD

**Issue by hunterhunted** [LogicalError/realtime-CSG-for-unity#229]
Similar to #159 but still present specifically for the Inverted world mode.
Issue present in several versions, including the latest 1.509

Replication:
With inverted world on, create a room (subtracts correctly),
Then, try to either extend (such as creating a doorway) or intrude (such as making a box in the room).
The automatically chosen Add/Subtract operation will be incorrect (Choosing subtract inside an already subtracted room, or add when pushing out into the already solid inverted world brush).

Possible fix/workaround:
Inside RealtimeCSG\Editor\Scripts\EditorWindows\BrushTools\Generators\ExtrudedGeneratorBase.cs

I changed the direction test of UpdateBrushOperations from
if ((Height > 0 || !planeOnGeometry) ^ invertedWorld)
to
if (invertedWorld? Height > 0 && planeOnGeometry : Height > 0 || !planeOnGeometry)

(simply removing invertedWorld fixes the room issue but has additive as the default when making new rooms from the background, so this also makes subtractive the default when not on geometry in inverted world)

**Comment by LogicalError** [comment]
Thanks :)
I'll include the fix in the next version

**Comment by LogicalError** [comment]
This should be fixed in version 1.510
I'll close this ticket once it arrives on the asset store, in the mean time you can download it here: https://realtimecsg.com/updates/
