### ISSUE TITLE
Ability to make displacements and do blend textures like in valves "Hammer"

### ISSUE THREAD

**Issue by ghost** [LogicalError/realtime-CSG-for-unity#230]
The tools are great but can be expanded upon a lot, There are 2 really big things I would like to see in Realtime CSG, 

- 1st, I would like to be able to do displacements (Which is sort of like terrain) Since its another way of making terrain (manipulating a number vertices on a plane) Which is great because of the subtractive feature you currently have (which would be good for making holes in the terrain) Displacements would also be good for easily making uneven ground or walls on your level, this could help with aesthetics as well as being good for games/levels that have a low poly aesthetics. Another reason why displacements are good is because they're easy to use and learn, it is as easy as moving vertices, Some tools that might help with these operations would be like a proportional editing tool (so it's more easier for moving vertices on the displacement)

- 2nd, I would also like to see blending textures (which is also in valves "Hammer") texture blending is two albedo textures on the one shader (that's how Hammer works) in which you can put the material on a face of a brush (or displacement if implemented) and paint the face like painting terrain, this helps alot when trying to make snowy levels, you can put the base texture of the wall then add the "blended" snow texture to either (for example) the bottom of walls or top, this applys to roofs as well. It would help sell the aesthetics of buildings based in a snowy environment and would be much better (and easier) than using decals. 

I'm not much of a programmer myself so I would have no clue on how you would do implement these tools into the plugin, though it would help me and a lot of others a lot too! This is also my first time for using GitHub so I'm sorry if I've put it in the wrong thread or anything! I would also like to thank you for making it easier for making maps / levels in unity, as I'm aware of ProBuilder, I just didn't like it and there was a pretty big price for a plugin that you can do the same stuff in blender and other 3d modelling software for free.

**Comment by LogicalError** [comment]
Hi @Constaneer !

Don't worry, you didn't make a mistake, this is the correct place to request features
I'm glad you like Realtime-CSG :)

1. This is something I'm working towards with the refactoring work I've been working on lately, once that refactoring work is done this shouldn't be too hard to implement

2. I haven't put much thought into this yet, but I have been thinking about adding support for vertex painting .. either directly in realtime-CSG or by supporting tools like https://assetstore.unity.com/packages/tools/painting/vertex-tools-pro-55649 to work with realtime-CSG (somehow) .. or both
But I won't be able to work on this until I've finished the mentioned refactoring work
