### ISSUE TITLE
Statistics calculated wrong

### ISSUE THREAD

**Issue by Heia-Samahi** [LogicalError/realtime-CSG-for-unity#233]
The total triangles calculation is wrong. 
![csg mini bug](https://user-images.githubusercontent.com/14238126/34789620-3d96292a-f63f-11e7-8205-5f6bb4c76d51.JPG)
It says 6. Like the last mesh. But it is 100.

**Comment by LogicalError** [comment]
Oh right, thanks for letting me know

**Comment by LogicalError** [comment]
This has been fixed in version 1.516 which can be downloaded here if you purchased realtime csg: 
https://realtimecsg.com/updates/
I'll close this ticket once it's available from the asset store

**Comment by LogicalError** [comment]
This fix is now available from the asset store, so I'll close this ticket!
