### ISSUE TITLE
Shader Painter

### ISSUE THREAD

**Issue by julesd** [LogicalError/realtime-CSG-for-unity#236]

**Comment by julesd** [comment]
I cannot get Shader Painter to work with RealTime CSG.

**Comment by julesd** [comment]
I cannot get Shader Painter to work with RealTime CSG.

**Comment by LogicalError** [comment]
Hi, can you give me some more information? What do you see happening when you try to paint?

**Comment by julesd** [comment]
I just cannot get it to show.Even if I add a Mesh Render, which helps me create the painting material, but still can not paint on CSG model. The paint brush just does not show up.It works fine with Probuilder.
