### ISSUE TITLE
Material preview spamming exceptions while assigning materials

### ISSUE THREAD

**Issue by f1ac** [LogicalError/realtime-CSG-for-unity#239]
Version 1.516, UNITY 2018.1.0B2 PACKAGE.
Unity 2018.1.0b6

I've got the following errors continuously spamming the console after several material assignments, '(got 1, have 1 mips)' part varies between 'got 1' - 'got 5':
`Graphics.CopyTexture called with invalid destination mip level (got 1, have 1 mips)
UnityEditor.MaterialEditor:OnPreviewGUI(Rect, GUIStyle)
RealtimeCSG.EditModeSurfaceGUI:OnGUIContentsMaterialImage(Rect, Material, Boolean, SelectedBrushSurface[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModes/EditMode.Surface.GUI.cs:225)
RealtimeCSG.EditModeSurfaceGUI:OnGUIContents(Rect, EditModeSurface) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModes/EditMode.Surface.GUI.cs:503)
RealtimeCSG.EditModeSurfaceGUI:OnSceneGUI(Rect, EditModeSurface) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModes/EditMode.Surface.GUI.cs:974)
RealtimeCSG.EditModeSurface:OnSceneGUI(Rect) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModes/EditMode.Surface.cs:1612)
RealtimeCSG.EditModeSelectionGUI:HandleSceneGUI(Int32) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeSelection.GUI.cs:55)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

**Comment by LogicalError** [comment]
This sounds like a Unity bug .. Graphics.Copy isn't called anywhere in RealtimeCSG ..
It could be that some behavior changed between versions ...

**Comment by f1ac** [comment]
According to stack trace it is called from UnityEditor.MaterialEditor:OnPreviewGUI() which is called from RCSG. Could be something related to SRPs.

**Comment by LogicalError** [comment]
Well I'm rendering a material using a Unity method, and that method then creates these errors .. which it doesn't on earlier versions (AFAIK)
If you're using SRP, then yeah, maybe it's related to that?

**Comment by f1ac** [comment]
Possibly, I will recheck with new versions of Unity and HD SRP. Maybe specific preview parameters cause this or this is just a temporary SRP bug and will go away. Beta is beta, I just worry for this to not become a final release feature :)

**Comment by LogicalError** [comment]
Right, well it'll help if you submit bug reports about this so at least they're aware of this edge case ;)

**Comment by LogicalError** [comment]
Looking at the current 2018.1 version and this doesn't seem to happen anymore (at least for me)
So I'm assuming this is fixed
