### ISSUE TITLE
[Fix Available 1.308] Realtime build doesn't work

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#24]
Realtime brush build doesn't work on new scene. Can't select brushes on Mesh mode and Surface mode.
If you build brushes yourself, start build brushes automatically.

Unity 5.4.2f1
Realtime CSG 1.305

**Comment by LogicalError** [comment]
Have you tried the rebuild button in the bottom right of your scene view? Does that fix things?

**Comment by LogicalError** [comment]
How bizarre .. I'm wondering ... do you notice a difference if you resize using the arrow or resize while dragging the green point (the start of the arrow)?

**Comment by LogicalError** [comment]
I suspect this is connected to issue #26

**Comment by Hisashimaru** [comment]
No difference between the arrow and the green point.

I've found how to reproduce this problem.
1. Make a brush
2. Open new scene
3. Make a brush
4. Slelect and unselect the brush a few times
5. You can't select the brush, and you need rebuild

**Comment by LogicalError** [comment]
in what edit mode? in all of them? Or just a specific one? I'm away until next Tuesday, I'll look at this when I get back

**Comment by Hisashimaru** [comment]
I selected a brush in object mode.

I recorded how to reproduce the problem, please check that when you get back.
https://www.youtube.com/watch?v=m1X-HD-j10s

**Comment by LogicalError** [comment]
thanks, that helps a lot :) I'm a bit confused how this is even possible, but I'll figure it out. thanks

**Comment by LogicalError** [comment]
That close issue button is really on the wrong position on the form :(

I'm back home and I'm looking at this bug .. I managed to reproduce it, still figuring out why this is happening

**Comment by Hisashimaru** [comment]
Welcome back!

I got a error log, it show when I open new scene after make the broken brush(no faces). I don't know the relation between the error logs and this problem, but I report this  just in case. 

```
NullReferenceException: Object reference not set to an instance of an object
RealtimeCSG.CSGSceneManager.UnregisterBrush (RealtimeCSG.CSGBrush brush) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/CSGSceneManager.cs:1356)
RealtimeCSG.CSGSceneManager.OnDestroyed (RealtimeCSG.CSGBrush component) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/CSGSceneManager.cs:772)
InternalRealtimeCSG.CSGSceneManagerInstance.OnDestroyed (RealtimeCSG.CSGBrush component) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/CSGSceneManagerInstance.cs:24)
RealtimeCSG.CSGBrush.OnDestroy () (at Assets/Plugins/RealtimeCSG/Runtime/Scripts/Components/CSGBrush.cs:40)
```

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket
