### ISSUE TITLE
unity crushes when i try the clip 

### ISSUE THREAD

**Issue by sarahabdalfatah** [LogicalError/realtime-CSG-for-unity#240]
everytime i try to use the clip, unity just crushes and closes,what should I do?

**Comment by LogicalError** [comment]
Hi!
What version of Realtime CSG and Unity are you using? Are you on windows/ mac?
Is it just the clip mode that's giving you problems? Does it crash all the time? Or just sometimes?

**Comment by LogicalError** [comment]
Also, please try the latest version at: 
https://realtimecsg.com/updates/

Your problem may have already been fixed

**Comment by LogicalError** [comment]
And please let me know if a newer version fixes this for you!
Thanks!

**Comment by LogicalError** [comment]
Do you still have problems with the latest version?
