### ISSUE TITLE
Unity 5.5.0 crashes when editing points of shapes

### ISSUE THREAD

**Issue by MarcoDoraz** [LogicalError/realtime-CSG-for-unity#241]
I'm loving this tool but can't edit meshes even in 
[2018-02-28 14-46-17.zip](https://github.com/LogicalError/realtime-CSG-for-unity/files/1767281/2018-02-28.14-46-17.zip)
empty scenes because unity crashes.

**Comment by MarcoDoraz** [comment]
the unity version i'm using is the 5.5.0f3 

i see there is an hotfix for the 5.5.5 so i'm downloading that one and maybe install it. to see if it helps.

**Comment by MarcoDoraz** [comment]
Another thing is it safe to install the Hotfix from 5.5.5 from your site on my unity 5.5.0 ?

**Comment by MarcoDoraz** [comment]
ok i did exactly that and on similar shapes with which i have encountered bugs it seems to be working now

**Comment by LogicalError** [comment]
Ok, great to hear that your problem has already been fixed :)

**Comment by MarcoDoraz** [comment]
Do i need to remove the older version of CSG in order to install a newer one or do i install the package without touching anything?
