### ISSUE TITLE
The tool is unstable on Unity 2018

### ISSUE THREAD

**Issue by rickomax** [LogicalError/realtime-CSG-for-unity#242]
I should CTRL+S pretty often as the tool is crashing Unity from time to time.
Also, sometimes the UV generator crashes, and the mesh won't be built again until I restart Unity, showing the following on the console:
![image](https://user-images.githubusercontent.com/12863984/36930269-1ddcf748-1e7c-11e8-84f8-51301301c9ce.png)

**Comment by MarcoDoraz** [comment]
[NOT a developer of this tool, just a random guy trying to help]

If you haven't done it:
go the their website and download the latest hot-fix. For Unity 2018 there should be one at the top of the list if i am not mistaken.

If you encounter errors of Freezes click any other object in the scene and then re-click the model or shape you were working on. Also try changing the model from static to non static ( although it depends on how you are building you game). i'm using direct lighting and fake Ambient Lighting so setting off Static Lighting and disabling UV regeneration was a must. 

If it really is a code-related problem then you have to either debug and fix it yourself or wait for them to look into it.

**Comment by LogicalError** [comment]
Hi @rickomax 
What version of realtime-CSG / Unity are you using?
And like @MarcoDoraz mentioned, please download the latest version at https://realtimecsg.com/updates/
please let me know if that solves your issues!

As for that error message, could you send me a scene that has that error? 
I'd like to take a closer look at it ..

Thanks!

**Comment by LogicalError** [comment]
Hi @rickomax I received a notification where you mentioned on a different ticket that your issues where fixed in the latest version .. but the comment seems to have been deleted? so have things been fixed for you, or do you still have issues?

**Comment by rickomax** [comment]
Yep, it's fixed. Ty!

**Comment by LogicalError** [comment]
👍
