### ISSUE TITLE
What's the pre-requisites to use CreateFromPlanes?

### ISSUE THREAD

**Issue by rickomax** [LogicalError/realtime-CSG-for-unity#244]
Hi. I've been trying to use CreateFromPlanes using planes extracted from a convex mesh quads, but I always get warning messages like: "polygon is duplicated", "no intersections" and in the end, the brush isn't generated at all. What's the pre-requisites to use this function?

**Comment by LogicalError** [comment]
polygon is duplicated usually means that the same plane exists more than once, so I'm guessing that's what's going on? When you say convex mesh quads .. I hope you don't mean that the brush is infinitely thin? Because a brush always needs to have volume
