### ISSUE TITLE
DllNotFoundException: RealtimeCSG[1.517]

### ISSUE THREAD

**Issue by DoofDilla** [LogicalError/realtime-CSG-for-unity#245]
Unity 2017.3.0f3

Version 1.517 throws "DllNotFoundException: RealtimeCSG[1.517]" error.

Version 1.516 is working fine.

**Comment by DoofDilla** [comment]
Tested it on another computer, same result:

![image](https://user-images.githubusercontent.com/9446999/37361174-943eedc8-26f2-11e8-8fc6-492a4aa2d6f7.png)

**Comment by LogicalError** [comment]
That is really weird. Are you using 1.517 or 1.517B? Are you on mac or windows?

**Comment by LogicalError** [comment]
Oh it's the evaluation version, it got compiled without the right flag. I'll fix it, hold on

**Comment by LogicalError** [comment]
This has been fixed in 1.518 which can be downloaded from https://realtimecsg.com !

**Comment by DoofDilla** [comment]
Once again, thank you very much for the very fast fix. Its always nice to see when a plugin is actively supported.
