### ISSUE TITLE
Assign a material by Undo

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#247]
Unity 2017.3.1f1
RealtimeCSG 1.519

1. Drag a material on a brush surface. Don't drop and assign the material this time.
2. Undoing then the surface changes the material.

**Comment by LogicalError** [comment]
Thanks for letting me know, I'll take a look and see whats going on

**Comment by LogicalError** [comment]
This has been fixed in 1.526, let me know if you run into any other issues! I'll close this ticket once this version ends up on the asset store
