### ISSUE TITLE
Brush selection order

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#250]
Sometimes difficult to select the desired brush in the Mesh mode, please fix it. 
Object mode's deep clicking is works, but not select the clicked brush first. Can you change the selection order by distance between the surface to the camera?
![gif](https://user-images.githubusercontent.com/7605365/38455810-151a18c2-3ab8-11e8-9883-dedb97402ad9.gif)

**Comment by LogicalError** [comment]
Thanks for reporting this, I'll take a look

**Comment by LogicalError** [comment]
This is fixed in version 1.535, I will close this ticket once this is available from the asset store
