### ISSUE TITLE
Completion of new features 

### ISSUE THREAD

**Issue by ghost** [LogicalError/realtime-CSG-for-unity#256]
It’s been quite a while since anything new has been added. What’s going on?

**Comment by LogicalError** [comment]
https://forum.unity.com/threads/released-realtime-csg-level-design-for-unity.427601/page-8#post-3514790

**Comment by Constaneer** [comment]
Oh Ok, I really understand why you would have been really stressed out with working on Realtime-CSG while working at Unity and well I thank you for that. You have done a tremendous job with it! And I am happy for your decision to work with unity now and put aside Realtime-CSG. You have really helped me out with Level Design and possibly many others is well! Don't want to sound like a asshole or anything but maybe it would be better to maybe integrate some of Realtime-CSG features in with SabreCSG, as your still getting your name out there and your helping others., it could also be better used as more and more people are using it now

**Comment by LogicalError** [comment]
Thanks :)
I'm still going to make sure that Realtime-CSG will keep working with the latest version of Unity etc.
I Just can't work on it as before.
I still haven't decided what to do with Realtime-CSG long term
