### ISSUE TITLE
Can't get rid of the dockable window outright

### ISSUE THREAD

**Issue by Candescence** [LogicalError/realtime-CSG-for-unity#257]
There are times when I don't want to/need to work with CSG and I'd like to get rid of the dockable window outright to make screen room, but I can't actually do that, which is annoying, and it's strange that this isn't doable.

**Comment by LogicalError** [comment]
I'm assuming you don't mean the window in the sceneview? (which you can close by pressing x, or by toggling realtime-CSG on/off with control-F3)
The unity panel that you can dock, which appears when you close the in-scene helper window .. 
you should just be able to close it like any other panel .. 
realtime-CSG is not doing anything that should prevent that? So I'm confused ..?

**Comment by Candescence** [comment]
Okay, so I somehow wasn't aware of the Ctrl+F3 command. I even went back to check the documentation, and, well, there it is. That's all on me, then, sorry! Consider the issue moot.

Though my other two issues are potential problems, still.
