### ISSUE TITLE
[Fix Available 1.308] Mesh detaches from its wireframe sometimes

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [LogicalError/realtime-CSG-for-unity#26]
Sometimes, when I resize an object, mesh detaches from its wireframe:
![untitled](https://cloud.githubusercontent.com/assets/5061652/19417763/e6b64a70-93bd-11e6-9fd6-6b3518595b75.png)
Afterwards I can't select any brushes via Scene View.
But if I click «Rebuild» button in bottom right corner, it is fixed.
Also, if I click Ctrl+Z it is fixed too.

Console contains no messages (except two messages for «Complete rebuild»).

Unity version: 5.4.1f1 Personal
Windows 10, display 2560x1440 with 125% scaling, CPU: Intel i7 4770k, GPU: Intel 4600 HD.

**Comment by LogicalError** [comment]
There's something going on there where it doesn't detect changes properly and doesn't update the mesh. It usually happens when starting a new scene, haven't seen it happen here though.
Does it happen to you every time? Can you easily reproduce this?

**Comment by MarisaLovesUsAll** [comment]
It happens once in ~10-30 minutes. Not that easily, but I think I can reproduce it.
I am also a programmer, maybe I can provide some debug info in case you're unable to reproduce the bug on your PC.

**Comment by LogicalError** [comment]
I suspect this is connected to issue #24

**Comment by LogicalError** [comment]
Ok, I'll take a look at this next Tuesday, after I get back from a trip

**Comment by LogicalError** [comment]
This issue should be fixed in version 1.308 which is available on the update site ( http://prenominal.nl/updates/index.php )
I will close this ticket when it's available on the asset store

Let me know if this solves your issues ..

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket
