### ISSUE TITLE
Unity crashes when selecting surface

### ISSUE THREAD

**Issue by mkapolka** [LogicalError/realtime-CSG-for-unity#261]
Almost always, when I select a surface using the "Surface" tool, Unity immediately crashes. This is with Unity 2018.2.1f1, RealtimeCSG[1_531][Unity2018_2_1f1], and Mac OSX 10.13.6

To reproduce: Use the generate tool to create a box of any size, click on the "Surface" tool, and select any surface.

**Comment by LogicalError** [comment]
This should be fixed in version 1.532 which has just been uploaded to the realtimecsg.com website (find the Updates page)
I'll close this ticket when this version is available from the asset store

**Comment by LogicalError** [comment]
This is available from the asset store, closing this ticket
