### ISSUE TITLE
Cannot export to fbx anymore with 2018.3b10

### ISSUE THREAD

**Issue by VergilUa** [LogicalError/realtime-CSG-for-unity#277]
Exporting any model to the fbx fails with the following errors:

> NullReferenceException: Object reference not set to an instance of an object
InternalRealtimeCSG.GeneratedMeshInstance.OnEnable () (at Assets/Plugins/RealtimeCSG/Runtime/Scripts/Components/GeneratedMeshInstance.cs:186)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
InternalRealtimeCSG.MeshInstanceManager:Export(CSGModel, ExportType, Boolean) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/MeshInstanceManager.Export.cs:113)
RealtimeCSG.CSGModelComponentInspectorGUI:OnInspectorGUI(Object[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/ComponentEditorWindows/CSGModelComponent.Inspector.GUI.cs:370)
RealtimeCSG.EditModeSelectionGUI:OnInspectorGUI(Editor, Object[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeSelection.GUI.cs:244)
EditModeToolWindowEditor:OnInspectorGUI() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs:15)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

> Mesh indices of Floor_1_Diffuse (1) are out of range!
UnityEditor.AssetDatabase:ImportAsset()
UnityFBXExporter.FBXExporter:ExportGameObjToFBX(GameObject, String, Boolean, Boolean, Boolean) (at Assets/Plugins/RealtimeCSG/Editor/Thirdparty/UnityFBXExporter/FBXExporter.cs:78)
InternalRealtimeCSG.MeshInstanceManager:Export(CSGModel, ExportType, Boolean) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/MeshInstanceManager.Export.cs:233)
RealtimeCSG.CSGModelComponentInspectorGUI:OnInspectorGUI(Object[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/ComponentEditorWindows/CSGModelComponent.Inspector.GUI.cs:370)
RealtimeCSG.EditModeSelectionGUI:OnInspectorGUI(Editor, Object[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeSelection.GUI.cs:244)
EditModeToolWindowEditor:OnInspectorGUI() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs:15)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

This is on 2018.3b10 & RealtimeCSG v1.540

Nothing too fancy on the model as well. It's plain cube with 20 verts. This happens to any model I try to export. Exporting produces empty fbx with 0 tris / verts.

**Comment by LogicalError** [comment]
Thanks for letting me know, I'll check it out

**Comment by LogicalError** [comment]
Fixed in 1.541! I'll close this ticket once this version is available from the asset store

**Comment by VergilUa** [comment]
Ummm, the error is gone, but generated mesh is still got 0 polys on it.

**Comment by LogicalError** [comment]
Ok, that sounds like the fbx importing code has changed .. I'll take a look to see if it's realtime-CSG's fault .. it might be a bug in unity though

**Comment by LogicalError** [comment]
Can you try exporting a non broken mesh?

<img width="528" alt="export_2" src="https://user-images.githubusercontent.com/157976/49069684-2b12ca00-f22a-11e8-9b89-9d31c68371fd.png">
<img width="527" alt="export_1" src="https://user-images.githubusercontent.com/157976/49069685-2b12ca00-f22a-11e8-8ed6-2c70741c8e2a.PNG">

Everything seems to work for me in 2018.3b11 .. at least for a simple mesh?

**Comment by VergilUa** [comment]
By broken I meant the one that doesn't export.

I was still on b10, will download b11 and see if it works there.

**Comment by LogicalError** [comment]
Ok, if that doesn't work for you can you send me the model that doesn't export? Then I can figure out what's going on here ..

**Comment by VergilUa** [comment]
Same behaviour on b11

**Comment by VergilUa** [comment]
This happens not only on cyllinder but on any model I have. Same applies for extremely simple ones, e.g. cubes.

**Comment by LogicalError** [comment]
Strange .. it seems to work for me .. the only issue I'm seeing is that the export fails when a material is missing .. but I assume you have materials applied to it?
Could it be prefab related? 
Are you seeing the same problems if you unpack the prefab before you export it?

**Comment by VergilUa** [comment]
I don't have it as a prefab, simply made it one for exporting.
No idea why it fails. Yeah, materials are not an issue. Any ideas what might help?

**Comment by LogicalError** [comment]
Can you try this in a clean project on 2018.3b11 w/ latest realtime csg version, no prefabs? 
Just want to rule out something *somehow* interfering with realtime-CSG

**Comment by VergilUa** [comment]
2018.3b11 & Realtime CSG 1.541, same behaviour in the clean project, except different error poped up:
ImportFBX Errors:
Internal FBXImporter error: normal count (0) doesn't match tangent (36) or/and binormal count (0).

UnityEditor.AssetDatabase:ImportAsset()
UnityFBXExporter.FBXExporter:ExportGameObjToFBX(GameObject, String, Boolean, Boolean, Boolean) (at Assets/Plugins/RealtimeCSG/Editor/Thirdparty/UnityFBXExporter/FBXExporter.cs:78)
InternalRealtimeCSG.MeshInstanceManager:Export(CSGModel, ExportType, Boolean) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/MeshInstanceManager.Export.cs:233)
RealtimeCSG.CSGModelComponentInspectorGUI:OnInspectorGUI(Object[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/ComponentEditorWindows/CSGModelComponent.Inspector.GUI.cs:370)
RealtimeCSG.EditModeSelectionGUI:OnInspectorGUI(Editor, Object[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeSelection.GUI.cs:244)
EditModeToolWindowEditor:OnInspectorGUI() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs:15)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Mesh indices of Wall (1) are out of range!

UnityEditor.AssetDatabase:ImportAsset()
UnityFBXExporter.FBXExporter:ExportGameObjToFBX(GameObject, String, Boolean, Boolean, Boolean) (at Assets/Plugins/RealtimeCSG/Editor/Thirdparty/UnityFBXExporter/FBXExporter.cs:78)
InternalRealtimeCSG.MeshInstanceManager:Export(CSGModel, ExportType, Boolean) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/MeshInstanceManager.Export.cs:233)
RealtimeCSG.CSGModelComponentInspectorGUI:OnInspectorGUI(Object[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/ComponentEditorWindows/CSGModelComponent.Inspector.GUI.cs:370)
RealtimeCSG.EditModeSelectionGUI:OnInspectorGUI(Editor, Object[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeSelection.GUI.cs:244)
EditModeToolWindowEditor:OnInspectorGUI() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs:15)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Produces same 0 polys model.

**Comment by LogicalError** [comment]
![export](https://user-images.githubusercontent.com/157976/49074736-99a95500-f235-11e8-9535-3e9a63c082df.gif)
this is what I'm seeing ..

**Comment by LogicalError** [comment]
(that's with the invalid material fix & changing the name of the mesh so it's easier to distinguish from the material in the fbx)

**Comment by LogicalError** [comment]
Could you record how you're doing the export etc. so I can do the same steps exactly like you're doing? There must be *something* that's different that's causing your problems ...

**Comment by VergilUa** [comment]
The model seems to be broken into parts, but it was completely solid and joined together. Weird.
Posted my test on the clean project above.

**Comment by LogicalError** [comment]
broken in parts, you mean in the animated gif? that's just aliasing because it was thin and far away .. the model is solid for me

**Comment by VergilUa** [comment]
Yeah, in gif. If it's solid then it's okay. No idea why exporting doesn't work in empty project though.

**Comment by LogicalError** [comment]
I've found it. It's a localization issue .. these fbx files are text files and the coordinates are stored differently depending on your locale ... so in this case 0.5 would be stored as 0,5 on your computer ...
now consider that coordinates are separated by , you get 0,5,0,5,0,5 instead of 0.5,0.5,0.5. One of these is 6 values, the other is 3 🙄
Easy to fix though. Just don't understand how this is possible .. either unity was automagically fixing this before, or it never actually worked in different locales?

**Comment by LogicalError** [comment]
I just uploaded version 1.542, can you check if this version fixes your issues? 
Thanks

**Comment by VergilUa** [comment]
Yeah, it works. Thanks! :)

**Comment by LogicalError** [comment]
This version is now available from the asset store so I'm closing it
