### ISSUE TITLE
Raycasting sometimes selects wrong surface

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#285]
https://cdn.discordapp.com/attachments/531079135737544705/534044194440871997/WallSelect.gif

**Comment by LogicalError** [comment]
turns out selection is correct, but the CSG algorithm is sometimes not removing the right surfaces when they're really close to each other

**Comment by Kerfuffles** [comment]
I haven't noticed this issue with more recent versions of RCSG. Can this be closed?

**Comment by alexjhetherington** [comment]
Unable to reproduce in 2019 LTS, 2021 LTS +1 for closing

**Comment by Appleguysnake** [comment]
Haven't had this problem with the latest versions and in Unity 2021, +1 close
