### ISSUE TITLE
CSG Brushed/Operations do not retain ray snapping behavior when changed with prefab window

### ISSUE THREAD

**Issue by Skylar1146** [LogicalError/realtime-CSG-for-unity#289]
When you create a prefab of an CSG operation and attempt to edit it's Ray Snapping behavior (Placement Or Front options), and exit the prefab view, the changes are not saved and are now back at default.

**Comment by LogicalError** [comment]
Thanks, I'll take a look

**Comment by LogicalError** [comment]
Fixed in version 1.545!
