### ISSUE TITLE
[Partially fixed 1.307] Performance issues (Ctrl-Z)

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [LogicalError/realtime-CSG-for-unity#29]
On an empty scene, Ctrl-Z is pretty fast:

![bug](https://cloud.githubusercontent.com/assets/5061652/19420818/26eaf04e-93fc-11e6-8a55-ae3bebc25532.gif)

But on a scene with ~500 brushes, it goes terribly slow (almost 2 sec for undo):

![bug2](https://cloud.githubusercontent.com/assets/5061652/19420832/6d135318-93fc-11e6-92a1-1067ab3ae606.gif)

Some stats:
![untitled](https://cloud.githubusercontent.com/assets/5061652/19420858/190c938c-93fd-11e6-8871-bb846d99c750.png)
Full hierarchy rebuild in 48.72 ms. Full CSG rebuild done in 74.85 ms. Mesh update done in 12.99 ms.

Unity version: 5.4.1f1 Personal, installed on HDD
Windows 10, display 2560x1440 with 100% scaling, 16 Gb RAM, CPU: Intel i7 4770k, GPU: Intel 4600 HD.

What can I do to improve performance?

**Comment by LogicalError** [comment]
Hmm .. the only thing I can think of that might be causing this is if it's performing a full rebuild several times per Undo. I'll look into it, thanks for reporting it

**Comment by MarisaLovesUsAll** [comment]
Just tried 1.307.
Better, but still a bit slow:
![bug](https://cloud.githubusercontent.com/assets/5061652/19454604/80a445f6-94c2-11e6-8ebf-9ecb7673d4e3.gif)

**Comment by LogicalError** [comment]
I'll see if I can improve things, but it'll be a lot of work, so it'll take some time

**Comment by LogicalError** [comment]
This should be fixed now, let me know if you run into any other issues
