### ISSUE TITLE
Layers of children get cleared on play / build

### ISSUE THREAD

**Issue by lazlo-bonin** [LogicalError/realtime-CSG-for-unity#293]
I've noticed layers of any child of any CSG model get assigned to that model's layer on play / build.

This is due to the AssignLayerToChildren call in MeshInstanceManager.OnBuild.

This causes plenty of issues in my setup though, where sometimes I will add non-CSG elements with specific layers as children of the CSG model.

So far it seems that disabilng the call doesn't do any harm, but I'm not sure if it could.

**Comment by LogicalError** [comment]
Can you try version 1.558, this should've been fixed there?
