### ISSUE TITLE
Incorrect width and height when generating boxes of smaller sizes

### ISSUE THREAD

**Issue by krisscox** [LogicalError/realtime-CSG-for-unity#295]
When using grid snapping to create boxes, the smaller the grid division the more innacurate the dimensions.

Sizes are perfect for 1, 0.5 and 0.25, but are incorrect when lower, e.g: 0.0625 becomes a height of 0.061999 and width of 0.063.

Using version 1.556 on Unity 2017.4.28f

![image](https://user-images.githubusercontent.com/13507466/61144014-aa0ff680-a4cb-11e9-9cc0-46b36dd562ad.png)

**Comment by krisscox** [comment]
Also tested with unity 2018.4.3f1 using asset store version of plugin, and the same issue occurs

**Comment by LogicalError** [comment]
Sorry, this is due to hardware limitations. It's not possible to have infinite precision in a finite amount of bits, so inaccuracies will unavoidably creep in :-/

**Comment by krisscox** [comment]
Rather than having the length divide every time, therefore hitting the issue of floating point precision, would it be possible to have preconfigured amounts instead? e.g:

1/2: 0.5
1/4: 0.25
1/8: 0.125
1/16: 0.0625
...

Or does the issue not lie in the division, but the way Unity handles its units?

**Comment by krisscox** [comment]
Having delved into the code, I can see that this thinking was a little naive of me - it has nothing to do with the halving of the float when pressing + and -, but to do with the mesh generation itself.

@LogicalError I wanted to add something that would do the following:
- Set the minimum division to 1/32
- When the mesh is generated loop through
- Snap each vertices Vector 3 coordinates to the nearest matching 1/32 float value (from a lookuip table perhaps)

Could you point me in the right direction to where I might start?
