### ISSUE TITLE
DllNotFoundException: RealtimeCSG[1.556].dll with Unity 2019.2.0f1

### ISSUE THREAD

**Issue by ianmasters** [LogicalError/realtime-CSG-for-unity#296]
I've noticed this has happened before and am guessing it's due to the dll having calls to either deprecated or removed functions. Just guessing.

This is on Windows but it also fails to load on Mac (can't recall the error message on Mac.)

Would it be possible to get a fix for this so we can move to 2019.2 ?
Thanks

**Comment by ianmasters** [comment]
Looks like we're dealing with abandonware here folks. Author has moved to another project. This looks like the end.

**Comment by VergilUa** [comment]
Yep, it seems like this is an issue with 2019.2; Got same one but with higher version:
> DllNotFoundException: RealtimeCSG[1.542]

> Looks like we're dealing with abandonware here folks. Author has moved to another project. This looks like the end.

I'm pretty sure author said that plugin support will still be served, just no new features will be added. Have patience.

**Comment by VergilUa** [comment]
Also:
![image](https://user-images.githubusercontent.com/24496266/62770621-0f8fdc80-baa4-11e9-81aa-737d478a62b2.png)

**Comment by ianmasters** [comment]
Thanks for those updates. I can wait for everything but patience! It's frustrating as RealtimeCSG is such a darn good tool. Few bugs here and there but update breakers are annoying. Anyhow, stuck on 2019.1 for now.

**Comment by LogicalError** [comment]
As mentioned on the forum, a workaround has been used to fix around this unity bug.
I'm annoyed by the update breakers as well, but it's outside my control unfortunately
