### ISSUE TITLE
Can't generate geometry anymore

### ISSUE THREAD

**Issue by enzi** [LogicalError/realtime-CSG-for-unity#3]
I've played around and produced 2 brushes. After the generation of the first brush I couldn't generate a new brush (free draw/cylinder). After a restart I could make the 2nd brush. Drawing onto this, broke it again and after another restart, generation completely stopped working in this scene.

The error is: "Could not create brush from given 2D shape". The shape I draw is 3-4 vertices, so triangle or box shaped.

Here's the scene:
[rCSG.zip](https://github.com/LogicalError/realtime-CSG-for-unity/files/437999/rCSG.zip)

@LogicalError Can you provide betas for code fixes? Going through the Unity process takes a lot of time.

**Comment by LogicalError** [comment]
Hi enzi, I think the problem has to do with a bug that makes it impossible to make convex shapes .. can you confirm this? 
I'm uploading a fix for that right as I'm typing this (might take a bit before Unity accepts my change though) ..

**Comment by enzi** [comment]
That was fast, I just wanted to edit that it seems that only convex is working. I think one of us has mixed concave/convex up, but either way, I think we're definitely talking about the same bug.

Cool if it's fixed. Unity takes some days, right?

**Comment by LogicalError** [comment]
I'd like to send you a fix, but I don't have any way to reach you currently .. 
(Unity asset store doesn't seem to show me who bought realtime CSG either, so can't look it up there)

**Comment by enzi** [comment]
I'll send you details to your gmail adress of my purchase so you can verify in the backend.

**Comment by LogicalError** [comment]
sent!

**Comment by enzi** [comment]
Thanks, issue solved.

**Comment by LogicalError** [comment]
great to hear!
