### ISSUE TITLE
Can't Turn Off Wireframe Mode

### ISSUE THREAD

**Issue by Dracalis** [LogicalError/realtime-CSG-for-unity#303]
Hi,

Realtime CSG seems really cool, but I'm having an issue where I can't turn off the wireframe mode. Clicking the button turned it on, but clicking it again won't turn it off. Am I missing something? This is in Unity 2019.2.19f1.

![Realtime CSG Wireframe](https://user-images.githubusercontent.com/11826812/74009546-0b585500-4949-11ea-8029-125c56886a91.gif)

**Comment by MrSlagovich** [comment]
Also getting this error. Did you manage to find a fix?

**Comment by Dracalis** [comment]
I haven't found a solution yet. I had to uninstall CSG to fix it.

**Comment by MrSlagovich** [comment]
@Dracalis i went to the plugins folder and deleted it and then re installed it but its still stuck in wireframe is there a certain way or file i need to delete

**Comment by stephenchildree** [comment]
I'm also having this issue. Even deleting and reinstalling RCSG it's still stuck in wireframe mode.

**Comment by Janooba** [comment]
Closing the scene view and opening a new one is a quick workaround to get things rendering normally again.

**Comment by Kerfuffles** [comment]
Is this still an issue with current versions of RCSG? I have not been able to reproduce this issue.
