### ISSUE TITLE
Normals of generated models with RealtimeCSG can have invalid values for the HDRP that will cause NaNs

### ISSUE THREAD

**Issue by VergilUa** [LogicalError/realtime-CSG-for-unity#305]
... and those are the source of the black screen flickering artifacts.

Just a heads-up. 
This is easily workarounded by setting model import settings of Normals to Calculate instead of Import.

I assume those are 0,0,0 normal vectors that will cause normalization to fail due to zero division, but I'm not 100% sure.

**Comment by LogicalError** [comment]
Sorry for the late reply, but do you have a repro for me?

**Comment by VergilUa** [comment]
Simplest repro for me was simply exporting generated models to FBX (after editing in mesh mode), and dropping them into the scene and entering play mode. 

Unfortunately I don't have them anymore.

**Comment by Kerfuffles** [comment]
Did this ever get resolved?

**Comment by Kerfuffles** [comment]
There have not been any other mentions of this issue from anyone else and no response from OP, so until a repro is provided or the information to repro is described with more accurate steps provided, I will mark this issue as closed.

Were the models exported from an external package after exporting using the export FBX function?
Were calculate normals/tangents turned off?
What version of unity?
What version of RealtimeCSG?
