### ISSUE TITLE
DllNotFoundException: RealtimeCSG[1_559]

### ISSUE THREAD

**Issue by Seungjusamlee** [LogicalError/realtime-CSG-for-unity#308]
It doesn't show up in any renderer. Help?

**Comment by LogicalError** [comment]
Close unity, delete the realtime CSG folder in your unity project and replace it with the one in this github repository, it should fix it.
Keep in mind it only works on Windows and Mac, what platform are you on?

**Comment by Seungjusamlee** [comment]
Linux, But i'll soon switch
