### ISSUE TITLE
alt+RMB rubberbands out of the dolly

### ISSUE THREAD

**Issue by laurentopia** [LogicalError/realtime-CSG-for-unity#310]
alt+RMB normally dollies the camera in and out  but when CSG window is up it rubberbands back out!

**Comment by LogicalError** [comment]
Can you give some more information? When does it "rubberband back out" exactly?

**Comment by cr4yz** [comment]
https://github.com/LogicalError/realtime-CSG-for-unity/issues/320 appears to be the same issue, I've commented the line of code causing it there.

**Comment by Kerfuffles** [comment]
Closing this issue in favor of #320, as it provides a visual example of the issue.
