### ISSUE TITLE
Surface selection on subtractive brushes no longer pickes the backfaces, but instead the invisible front faces.

### ISSUE THREAD

**Issue by Janooba** [LogicalError/realtime-CSG-for-unity#312]
Surface selection on subtractive brushes no longer pickes the backfaces, but instead the invisible front faces.

Steps to reproduce:

1. Create an additive cube.
2. Create a subtractive cube overlapping part of the additive cube.
3. Change to "Surfaces" mode and try to click one of the inner faces of the cube.

Video example:
https://thumbs.gfycat.com/AgonizingPersonalAnchovy-mobile.mp4

**Comment by LogicalError** [comment]
Thanks, fixed in 1.562!
I'll close this ticket when it's available from the asset store

**Comment by Kerfuffles** [comment]
Considering that it doesn't appear like the asset store version is going to be updated anymore, I'm going to go ahead and close this.
