### ISSUE TITLE
Drag and Drop Transparent Material Causes Unity Crash

### ISSUE THREAD

**Issue by AlexHetherington** [LogicalError/realtime-CSG-for-unity#314]
Fresh Unity project 2018.4.23f1

1) Create a unity plane
2) Create a realtimeCSG cube over the plane
3) Create a material with render mode set to transparent
4) Drag material over realtimeCSG face

Video: https://drive.google.com/file/d/1ZIzhAWkyOn3tDqlqHRD0jvvwdzghqSPU/view?usp=sharing

**Comment by LogicalError** [comment]
Sorry, this seems to be a Unity bug, please submit a bug report @ unity

**Comment by AlexHetherington** [comment]
https://issuetracker.unity3d.com/issues/unity-crashes-on-extendvisibleaschild-when-onsceneguidelegate-references-a-method-which-calls-handleutility-dot-pickgameobject

Is the related issue on Unity side

**Comment by LogicalError** [comment]
Thanks for the update!
