### ISSUE TITLE
RCSG generates duplicate collider meshes on unity 2018.4.xxxx

### ISSUE THREAD

**Issue by Kerfuffles** [LogicalError/realtime-CSG-for-unity#315]
#### Steps to reproduce:

1. Create CSGModel
2. Turn on show meshes
3. Create a brush
4. Force rebuild
5. Edit the brush
6. Observe the second collider mesh generated until force rebuild is done again

This happens 100% of the time. I'm using the VRChat SDK 3 and require using unity 2018.4.20f1. I am uncertain if this issue occurs on earlier versions of unity, but I *do* know this issue does not occur on 2019.XXXX

**Comment by LogicalError** [comment]
What version of realtime CSG is this? I cannot reproduce this on latest version
