### ISSUE TITLE
[Fix Available 1.308] Selected surfaces will be deselect

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#32]
Selected surfaces will be deselect when you click the material on the tool window. This problem not happen with the separated tool window.

I marked the problem points.
![material](https://cloud.githubusercontent.com/assets/7605365/19468273/6d3737f6-9550-11e6-91da-dc25e28a6484.jpg)

**Comment by LogicalError** [comment]
Right, seems as if the mouse clicks through the window.. I'll look at it when I'm back from a trip I'm on right now (only have my phone with me, no computer)

**Comment by LogicalError** [comment]
This is fixed in version 1.308 which is available on the update site ( http://prenominal.nl/updates/index.php )!
I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket
