### ISSUE TITLE
When arrows visible and i hold alt and rotate or drag camera it zooms out a lot

### ISSUE THREAD

**Issue by friuns2** [LogicalError/realtime-CSG-for-unity#320]
bug: when arrows visible and i hold alt and rotate or drag camera it zooms out a lot
Unity 2019.4.17f

https://user-images.githubusercontent.com/16543239/106351422-bdb8c300-62e4-11eb-948a-6ad641c319db.mp4

**Comment by cr4yz** [comment]
https://github.com/LogicalError/realtime-CSG-for-unity/blob/03adff579cc82167b2dd5d226ec89cd6745249fe/RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModes/Generators/Generator.Base.cs#L663 

Seems to be the code causing it.  I've commented it out

**Comment by Kerfuffles** [comment]
Does this issue still persist with the current version?

**Comment by Kerfuffles** [comment]
Fixed with #349

**Comment by Janooba** [comment]
Confirmed fixed in #349 using 2019.4.31f1 but it appears you cannot press F to focus on the block being generated. Minor but notable.
