### ISSUE TITLE
Having multiple Models

### ISSUE THREAD

**Issue by robclouth** [LogicalError/realtime-CSG-for-unity#322]
The tool seems to have issues with multiple Model objects in a scene. Generated brushes sometimes are added to the correct model, sometimes to a brand new Model in the scene. What decides which Model you're editing? I can't seem to figure it out. Editing a prefab in isolation doesn't help the issue.

**Comment by vncastanheira** [comment]
I'm experiencing this problem as well, currently trying to have a modal that will have brushes only for collisions.

**Comment by LogicalError** [comment]
In realtime csg, when you add a brush on top of another brush, the new brush is automatically added to the model of the other brush
Maybe that's what you're seeing?

**Comment by robclouth** [comment]
Thanks for replying. In that case it would be super handy to be able to lock editing to a certain model. It's quite frustrating as it is now because sometimes it creates a new model instead of adding it to the one you're currently editing. Perhaps when you're inside a prefab all brushes should only be added to that prefab.

**Comment by Kerfuffles** [comment]
#351
