### ISSUE TITLE
Intersection Operation does not work - both children disappear

### ISSUE THREAD

**Issue by DavidAntliff** [LogicalError/realtime-CSG-for-unity#324]
I'm working through the features and came to "Operations allow you to group things". I've created a new Model and added two default cube brushes. I offset one from the other slightly, so they overlap around one corner each. I then selected both and hit CTRL-G to create an Operation as the new parent of both cube brushes. Then I selected Intersection.

I had expected to see a smaller cubioid appear where the two cubes overlap, and the rest of each cube to become invisible. Instead, I just see two overlapping cubes.

I clicked "Rebuild your CSG meshes" and both cubes went completely invisible. They reappear if I change the Operation mode from Intersection to anything else. But still no overlap cuboid.

Is this behaving as expected? Am I doing something wrong? Or is this a bug?

I'm using version v1.562 with Unity 2020.3.3f1 on Win10.

**Comment by LogicalError** [comment]
Hi, what happened is that the two brushes in the group are added to each other, and then the combination of both brushes use intersection .. on nothing, so everything disappears
Instead set the group to additive, and the last brush within that group to intersection

**Comment by Kerfuffles** [comment]
@DavidAntliff Did this solve your problem?

**Comment by DavidAntliff** [comment]
Hi Daniel, thank you for checking in with me. I haven’t had a chance to revisit this yet, but next time I look to use CSG I’ll see what happens. Feel free to close this on the meantime if you want. Thanks again for the explanation.
________________________________
