### ISSUE TITLE
Missing assembly references

### ISSUE THREAD

**Issue by phil1025** [LogicalError/realtime-CSG-for-unity#326]
OS: Windows 7 SP2
Unity Version: 2020.3.15f2 Personal
IDE: Microsoft Visual Studio Community 2019 Version 16.9.4
       with Visual Studio Tools for Unity 4.9.1.0
Realtime CSG
- Imported Version 1.562 via Assetstore/Package Manager
- Imported latest realtime CSG from Github

Issue:
Most or all scripts cause errors "Missing assembly reference" in Visual Studio.
Visual Studio suggests to fix it: Add reference to 'Assembly-CSharp-Editor-firstpass' (never seen before, normally it would suggest "using ...")
This fixes the errors in VS, but the issue then persists in the Unity console. After restarting VS the errors appear there again aswell.
The Realtime CSG editor tools seem to work fine.

Error producing code (https://www.realtimecsg.com/documentation/brushMesh.html):
`
        BrushMesh cube = RealtimeCSG.Legacy.BrushFactory.CreateCube(Vector3.one);
        BrushMeshInstance cubeMeshInstance = BrushMeshInstance.Create(cube, 1);
`

Errors:
- Error	CS0234	The type or namespace name 'BrushFactory' does not exist in the namespace 'RealtimeCSG.Legacy' (are you missing an assembly reference?)
- Error	CS0246	The type or namespace name 'BrushMesh' could not be found (are you missing a using directive or an assembly reference?)
- Error	CS0234	The type or namespace name 'BrushMeshInstance' does not exist in the namespace 'RealtimeCSG.Foundation' (are you missing an assembly reference?)
- Error	CS0234	The type or namespace name 'BrushMeshInstance' does not exist in the namespace 'RealtimeCSG.Foundation' (are you missing an assembly reference?)

![realtimeCSG_ReferenceError](https://user-images.githubusercontent.com/17439980/128698769-295f8e4f-db97-4134-93d9-2e5ddd0fe782.PNG)

**Comment by ellie-fisher** [comment]
i'm also running into this issue

**Comment by Kerfuffles** [comment]
If you are still having this issue, make sure you are only importing the `Plugins/` directory, and not the entire repo.

**Comment by Kerfuffles** [comment]
> > If you are still having this issue, make sure you are only importing the `Plugins/` directory, and not the entire repo.
> 
> Thank you Daniel, I will try that!

Did this work for you?

**Comment by Kerfuffles** [comment]
This should no longer be an issue as of #340. Should be a drop-in plugin now.
