### ISSUE TITLE
[Question] Why is my subtraction brush turning blue?

### ISSUE THREAD

**Issue by wbn1883** [LogicalError/realtime-CSG-for-unity#33]
In Unity5.4.2f
![20161019162014](https://cloud.githubusercontent.com/assets/4012794/19511151/a31e6da8-9618-11e6-9981-8132e7ae5af8.png)

**Comment by Hisashimaru** [comment]
You can hide the blue surfaces from the right bottom menu of the scene view. Try disable "Show Invisible Surfaces".
![inv](https://cloud.githubusercontent.com/assets/7605365/19512248/efb1e21e-9625-11e6-9a9a-b4fae744d46d.jpg)

**Comment by LogicalError** [comment]
Yes, that is exactly right :)
