### ISSUE TITLE
Feet and inches are the wrong way around

### ISSUE THREAD

**Issue by killerlegs** [LogicalError/realtime-CSG-for-unity#336]
![image](https://user-images.githubusercontent.com/32152103/154866142-c970bfd1-fcb8-4941-b15a-aecfedfee136.png)
![image](https://user-images.githubusercontent.com/32152103/154866153-b061e019-f7d8-47d6-b307-c45c83833c7c.png)
![image](https://user-images.githubusercontent.com/32152103/154866164-4debe327-47cf-4547-b8f9-8b930d1d8dcb.png)

**Comment by killerlegs** [comment]
This is also wrong in the manual
![image](https://user-images.githubusercontent.com/32152103/155851249-07e6f9fc-eedc-4329-b419-b9a25afde761.png)

**Comment by LogicalError** [comment]
Fixed in latest version!
