### ISSUE TITLE
[Request] Can I use an existing mesh as a brush? 

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#34]
can I use other fbx or prefab model  as brush? 
hi,I just buy your plugin at store,
as far I want to know  can I use other fbx or prefab model  as brush?

**Comment by LogicalError** [comment]
No, at the moment there isn't a way to create a brush from a mesh..

**Comment by sonygod** [comment]
are you plant to do this in next version ?

**Comment by LogicalError** [comment]
I have plans to implement that eventually, but not right now.
It's actually kind of complicated to do this and there are a million ways to make mistakes

**Comment by sonygod** [comment]
current there is an tool call MeshMaker can do this thing  ,but there is lot's of bug.so I turn to this plugin .

**Comment by sonygod** [comment]
because I want to insert some window model by art's to wall,so that's why I want to this function .

**Comment by LogicalError** [comment]
well in this case there's no reason why you couldn't create your walls using CSG and then a mesh for the window frame

**Comment by sonygod** [comment]
hi ,I have a idea to make this possible ,
1.get the mesh Convex Hull vertex.[]
2.convert this  Vertex[] to your csg brush  Vertex[].
are there anything i missing? or wrong ?

current I hope there is an function can easy convert function step1  Vertex[] to convert csg bursh  Vertex[]

**Comment by LogicalError** [comment]
That only works if the original mesh is convex ... If I put that in there people will try to put every kind of mesh with it :-/

**Comment by sonygod** [comment]
right,but ,please support convex mesh first! 1.3.x?1.4.x?

**Comment by sonygod** [comment]
hi,I found this source do the same thing  that what I want 

https://github.com/karl-/pb_CSG/blob/master/Assets/CSG/Classes/CSG_Model.cs



but it's seem it's not so easy to implement to your csg system?

**Comment by LogicalError** [comment]
related to #137
