### ISSUE TITLE
Compatibility with "disabled Domain Reload"

### ISSUE THREAD

**Issue by andreiagmu** [LogicalError/realtime-CSG-for-unity#345]
Considering my project has Domain Reload disabled, for faster Play Mode iteration:
With the current version, if I add some CSG shapes in the scene, save the scene, enter Play Mode, then exit Play Mode.
After returning to the Unity Editor, the CSG shapes vanish from the scene.

After adding the `[RuntimeInitializeOnLoadMethod]` attribute above the `Clear()` method from `InternalCSGModelManager.Lifetime.cs`, the issue is fixed.

```
#region Clear
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
public static void Clear()
```

**Comment by Kerfuffles** [comment]
Looking through issues, it appears like this is a problem that has occurred in the past, with issues #307 and #299. Fixing this should probably also fix those two issues.
