### ISSUE TITLE
[Request] can I use free draw a no fill box but with custom border?

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#35]
can I use free draw brush to draw  a no fill box but with custom border? 

current I want to draw a box without fill ,I have to do 2 step.

**Comment by LogicalError** [comment]
do you mean a hollow shape?
that functionality doesn't (yet) exist no

**Comment by sonygod** [comment]
yes ,that 's what I want

**Comment by LogicalError** [comment]
I'll put it on my todo list!

**Comment by sonygod** [comment]
any news about this feature?

**Comment by LogicalError** [comment]
I haven't had time yet, sorry, I need to fix all the reported bugs first ..
.. in the meantime, a possible solution is that to use an additive brush + subtractive brush that's smaller than the additive brush
