### ISSUE TITLE
Surface Selection stops working if the cursor leaves boundary of the brush / 2021.3.0f1

### ISSUE THREAD

**Issue by alexjhetherington** [LogicalError/realtime-CSG-for-unity#354]
Reproducing 2021.3.0f1 personal. Not reproducing on 2019. 

Does not cause any large usability issues but makes it feel "slow"

Video:
https://user-images.githubusercontent.com/36995359/164752942-6b691a49-eaee-4daf-bf7d-72adfb5f4fe2.mov

Saved asset folder:
[Assets.zip](https://github.com/LogicalError/realtime-CSG-for-unity/files/8542403/Assets.zip)

**Comment by Kerfuffles** [comment]
Poking around with this, it appears that a repaint event isn't triggered properly for hover selection previews, causing the selection previews to appear sluggish or unresponsive.

**Comment by Janooba** [comment]
Not sure I fully understand the repro steps as the video link is broken now, but I can't seem to reproduce the issue with #349 so I'm happy saying it's fixed.
Tested on 2019.4.31f1 and 2020.3.35f1
