### ISSUE TITLE
When dragging a material over a surface in the scene view, the undo stack is spammed with undo states

### ISSUE THREAD

**Issue by Kerfuffles** [LogicalError/realtime-CSG-for-unity#355]
Bug is located here:
https://github.com/LogicalError/realtime-CSG-for-unity/blob/a3ccdb6d13be59bd7f9a31dfebfd7cd47d3f872c/Plugins/Editor/Scripts/View/DragAndDrop/SceneDragTool.Materials.cs#L564

Where the check is inverted from what it should be.
```csharp
(!modified)
{
    // etc...
}
```
should be
```csharp
(modified)
{
    // etc...
}
```

This will be fixed with other fixes in PR #349

**Comment by Janooba** [comment]
Confirmed fixed in #349 using 2019.4.31f1
