### ISSUE TITLE
'Missing meta file' errors for readme files

### ISSUE THREAD

**Issue by CrowbarSka** [LogicalError/realtime-CSG-for-unity#356]
**A number of errors frequently appear in the console (e.g. every time the asset database is refreshed).**

These errors relate to the readme and license files associated with this GitHub package and state that there are no meta files attached to them, although none should be expected.

The errors can be cleared and do not impact execution of the game, but are distracting and imply problems in the game code and should not appear.

**Unity version:** 2020.3.30f1
**Meta file setting:** Visible Meta Files

### Errors:

> Asset Packages/com.prenominal.realtimecsg/Icons.zip has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/LICENSE.md has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/Readme has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/README.md has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/Readme/Images has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/Readme/Images/house_view.png has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/Icons.zip has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/LICENSE.md has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/Readme has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/README.md has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/Readme/Images has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.prenominal.realtimecsg/Readme/Images/house_view.png has no meta file, but it's in an immutable folder. The asset will be ignored.

### Repro steps:

1. Create an empty project or open an existing project using the Unity version stated above.
2. Open the Package Manager window.
3. Click the "+" icon to add a package.
4. Select "Add package from git URL".
5. Paste the following URL and click Add: https://github.com/LogicalError/realtime-CSG-for-unity.git
6. Note the errors that appear in the console when the package finishes installing.
7. Note the same errors appearing often throughout regular use of the editor, sometimes if assets are reimported or the editor is restarted.

**Comment by Kerfuffles** [comment]
I have a fix for this in the pipe. It'll be included in #349.
For now, to fix this:
1) Pull a copy of RealtimeCSG into an empty project (Assets, not as a package)
2) Let unity import
3) Copy the .meta files for the files missing, and then copy them to the plugins folder of the project you wanted RealtimeCSG to be a package
