### ISSUE TITLE
Usage at runtime?

### ISSUE THREAD

**Issue by ghost** [LogicalError/realtime-CSG-for-unity#358]
I noticed the API documentation was rather forgotten which is kind of a regular occurrence for open source I've noticed.
Is there any plans to expand and better document how to implement and use Realtime CSG?

As a programmer of 25 years and am having trouble piecing this together. I also don't understand why it can't just be made to work nearly identical as it does in the editor, that would be a brilliant feature!

Curious if this area could get some love. Cheers!

**Comment by 0xF6** [comment]
Damn...
https://github.com/LogicalError/realtime-CSG-for-unity/issues/7#issuecomment-244211321

Zero count runtime csg libraries for unity...

**Comment by Kerfuffles** [comment]
As was stated, there are currently no plans to add runtime support. Runtime support is planned for [Chisel](https://github.com/RadicalCSG/Chisel.Prototype), but Chisel as a whole is currently still in early development, and not quite ready for production yet.
