### ISSUE TITLE
Which script actually performs the subtraction operation and returns the result mesh?

### ISSUE THREAD

**Issue by imineti** [LogicalError/realtime-CSG-for-unity#359]
Which script actually performs the subtraction operation between 2 meshes and returns the result mesh?
I am looking for this script because I want to repurpose it but I can't seem to find it, all I need for my game is the Boolean Operation and the result mesh.

I appreciate any help this would go towards completing my life long dream of a game I've always wanted to make.
Thanks in advance!

**Comment by Kerfuffles** [comment]
Unfortunately, it is not possible to use RCSG at runtime. You can look at how the native library is interfaced with by looking at the native folder, but you would need to implement your own tooling entirely. Runtime support is planned for [Chisel](https://github.com/RadicalCSG/Chisel.Prototype/), but it isn't ready for production yet. I apologize for how long it has taken to respond to this.
