### ISSUE TITLE
[Request Implemented 1.308] generate box can set default height and auto commit 

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#36]
feature request generate box can set default height and auto commit ?

![](http://pic33.nipic.com/20130911/11662412_111329118000_2.jpg)

**Comment by LogicalError** [comment]
if you create a shape and immediately press enter it will create the shape with a height of 1.
there's no way to set the default height (yet) though

**Comment by sonygod** [comment]
are there any easy way to defind custom height?

**Comment by LogicalError** [comment]
you can set the height manually in the tool window .. I don't think it remembers the height at the moment, but should be easy to implement.
I'm away on a trip right now though, so won't be able to implement that (remembering the heighr) until mid next week.

**Comment by LogicalError** [comment]
In version 1.308 which is available on the update site ( http://prenominal.nl/updates/index.php ) , it now stores the last used shape height as the default height. If you then make another 2D shape and press enter it'll create it at that default height!

I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment]
Let me know if that works for you

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket
