### ISSUE TITLE
Allow hidden surfaces to be selected

### ISSUE THREAD

**Issue by Kerfuffles** [LogicalError/realtime-CSG-for-unity#365]
This would allow any surfaces with the `Visible` flag set to off, to be selectable in surface mode. By default, if any surfaces have `Visible` set to off, you would have to select the entire brush and set the flags for the entire thing. This would be a small workflow improvement, and possibly a small time saver.

**Comment by Janooba** [comment]
Confirmed working in #349 using 2019.4.31f1 and 2020.3.35f1
