### ISSUE TITLE
Bottom bar cannot be clicked on upon popping out the tool window

### ISSUE THREAD

**Issue by butterfli3s** [LogicalError/realtime-CSG-for-unity#366]
**OS:** Windows 11 22H2
**RCSG version:** Git https://github.com/LogicalError/realtime-CSG-for-unity/commit/a3ccdb6d13be59bd7f9a31dfebfd7cd47d3f872c
**Unity version:** Reproduced on 2021.3.4f1, 2021.3.5f1, 2022.1.6f1

**Issue:** When the edit modes window is popped out into dockable window, the bottom bar in the scene cannot be clicked on. Upon bringing it back into the scene view the bottom bar becomes clickable again.

Example (showcased on Unity 2022.1.6f1)
![Unity_792Dx3mg0V](https://user-images.githubusercontent.com/68999258/175822111-191f0822-6845-4cff-a759-d2a88e47d759.gif)

**Comment by Kerfuffles** [comment]
Changing line 81 of  `RealtimeCSG/Plugins/Editor/Scripts/Control/Managers/SceneViewEventHandler.cs` from
```csharp
SceneViewBottomBarGUI.ShowGUI( sceneView );
```
to
```csharp
SceneViewBottomBarGUI.ShowGUI( sceneView, false );
```
fixes this bug. I'm curious as to when this change was reverted, as the fix existed previously.

**Comment by butterfli3s** [comment]
Been discussing this issue with Kerfuffles on Discord and I already implemented said fix in my RCSG build; that fixes it for me.

**Comment by Appleguysnake** [comment]
I have the same error in the latest version, and I don't see the fix mentioned above in the commit history. 
I manually implemented the fix and can confirm it does work though.
