### ISSUE TITLE
need to add 10 to the height for new unity

### ISSUE THREAD

**Issue by redheadgektor** [LogicalError/realtime-CSG-for-unity#367]
https://github.com/LogicalError/realtime-CSG-for-unity/blob/a3ccdb6d13be59bd7f9a31dfebfd7cd47d3f872c/Plugins/Editor/Scripts/View/GUI/SceneViewBottomBarGUI/SceneViewBottomBar.GUI.cs#L33

**Comment by Kerfuffles** [comment]
Please provide more details.
* Unity version
* RealtimeCSG version
* Proper description of the problem

**Comment by Kerfuffles** [comment]
It has been almost a month without reply. Going to close this until it has been responded to, as it does not have enough information about the problem.
