### ISSUE TITLE
Apple Silicon support?

### ISSUE THREAD

**Issue by DeviantXS** [LogicalError/realtime-CSG-for-unity#368]
I tried opening the Unity plugin and received RealtimeCSG[1_559].bundle error during CSG initialization, but upon revision I've realized there is no Apple Silicon/ARM64 support.

Could there be a chance to support Apple Silicon in the future? 

Thanks!

**Comment by Kerfuffles** [comment]
There is currently no plans for this. None of us trying to keep RealtimeCSG up to date have an Apple Silicon/ARM64 device to test/compile on as far as I know. The native part of the plugin isn't open source currently. [Chisel](https://github.com/RadicalCSG/Chisel.Prototype) (the successor to Sabre CSG, and RealtimeCSG) is going to be entirely C#, so should support any platform that Unity supports, but is currently still in early development, and won't be production ready for a while.
