### ISSUE TITLE
[Request] API documentation

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#37]
any API document ?

can you write some API documnet  for your script?
such like 

drawPologon ,drawline,drawbox

**Comment by LogicalError** [comment]
There is a very limited editor API at the moment; BrushFactory.CreateBrushFromPlanes
More functionality will be added later + documentation.
If you have specific needs, please let me know then I can make sure it'll work for you ...

**Comment by sonygod** [comment]
how to auto assingn box six size with difference materials or give one speical material API?

**Comment by LogicalError** [comment]
You can add an array of materials to BrushFactory.CreateBrushFromPlanes

**Comment by LogicalError** [comment]
There's some basic API documentation up at https://logicalerror.github.io/editor-api.html
It's a WIP and definitely needs improvement, but it's a start

**Comment by sonygod** [comment]
well ,I'll waiting for your complete document。

**Comment by LogicalError** [comment]
is there something specific you need?

**Comment by sonygod** [comment]
drawPologon ,drawline,drawbox
it's easy way to draw simple geometry such like plane,cube ,line, only input pamrm  points and Materials
