### ISSUE TITLE
[1.332] Convert to mesh instead of export to fbx and reimport to editor

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#38]
is that possible fast convert to mesh instead of explort to fbx and reimport to editor?

**Comment by LogicalError** [comment]
Not yet, but sounds like a good feature to have ..

**Comment by LogicalError** [comment]
I'll see if I can implement this within the next couple of days

**Comment by LogicalError** [comment]
This is fixed in version 1.332!
As usual this is available on the update site https://prenominal.nl/updates/
I'll close this ticket once this version is available from the asset store!
