### ISSUE TITLE
[Request] Add straight line feature?

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#39]
add straight line feature? current free-draw can consider add  shift+mouse Draw a straight line?

**Comment by sonygod** [comment]
I mean beyond free-draw ,can add an unclose space such like box line

**Comment by LogicalError** [comment]
Sounds like a good idea!

**Comment by sonygod** [comment]
I have done this. use free-draw and box draw combine,but seem no perfect interface.

**Comment by sonygod** [comment]
I will upload a small video in youtube.

**Comment by sonygod** [comment]
https://youtu.be/8wInUbSXpjU

**Comment by LogicalError** [comment]
Ah ok, I misunderstood you. I thought you wanted to have functionality where if, for example, you hold shift in free-draw your current line would automatically be axis-aligned.
But this is very useful too, but also a bit more work.

**Comment by sonygod** [comment]
you hold shift in free-draw your current line would automatically be axis-aligned.

How to detect the mouse and keyboard in your system at the same time press？

it's seem Api  Keys .IsKeyPressed()  Api not support this case.

**Comment by LogicalError** [comment]
There's Event.current.modifiers that let's you know when Shift, Control etc. are pressed or not.
Besides that there are keyboard events EventType.ValidateCommand, EventType.KeyDown, EventType.KeyUp with which you can determine when a key has been pressed and released
