### ISSUE TITLE
Add a way to close RealtimeCSG window

### ISSUE THREAD

**Issue by x8c8r** [LogicalError/realtime-CSG-for-unity#393]
As of now, as soon as you install the package you get the in-scene tool. And there is no way to close it, it just becomes a floating dock. Yes, you can dock it to a place like next to inspector so you don't have to remember about it as often, but it's stll highly inconvenient.

There should be a way to close it like any other window or tab, so it is no longer visible unless you explicitly want to have it open.

**Comment by Loupyboy** [comment]
Already possible (CTRL+F3 or via menu), please mark as completed or unnecessary.

**Comment by x8c8r** [comment]
> Already possible (CTRL+F3 or via menu), please mark as completed or unnecessary.

CTRL + F3 does work but I can't see any menu option or anything indicating that CTRL + F3 keybind even exists
