### ISSUE TITLE
Hiding/closing the tool

### ISSUE THREAD

**Issue by ChananX** [LogicalError/realtime-CSG-for-unity#396]
Hi
Very nice tool, but is there a way to completely close or hide it? I only manage to switch between a toolbar and a window. But I don't always want to see it on screen.

**Comment by Nanobrainiac** [comment]
Same. It's quite unfortunate that I cannot hide the tool and various editor enhancements when I don't need use of the tool.

**Comment by nukeandbeans** [comment]
CTRL+F3 toggles RCSG. There is also a menu item to do so.
