### ISSUE TITLE
"Could not create brush from given 2d shape" [FIX AVAILABLE]

### ISSUE THREAD

**Issue by gumbomasta** [LogicalError/realtime-CSG-for-unity#4]
This happens every time i try to draw a brush, default feature of the plugin.  What's happening here?  Can't even get building.

Using Unity 5.4.0f3 personal.

![2016-08-27 00_44_16-unity personal 64bit - untitled - level design controlla - pc mac linux sta](https://cloud.githubusercontent.com/assets/9627628/18025184/760c2e2a-6bef-11e6-8913-22099ce42ae5.png)

**Comment by LogicalError** [comment]
Hi, this is a known issue and there is already a fix available. Unfortunately it takes a while before it's accepted on the Asset store .. if you sent me an email (sander.vanrossen -at- gmail.com with your OR code (you should've received one when you bought realtime-CSG) I can send you the fixed version directly. Sorry for the inconvenience

**Comment by LogicalError** [comment]
Fix available on asset store
