### ISSUE TITLE
[Fix Available 1.313] "Setting the parent of a transform which resides in a prefab is disabled to prevent data corruption"

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#43]
Setting the parent of a transform which resides in a prefab is disabled to prevent data corruption.
UnityEngine.Transform:SetParent(Transform, Boolean)
RealtimeCSG.OperationsUtility:CreateGameObject(Transform, String, Boolean) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Helpers/OperationsUtility.cs:547)
RealtimeCSG.BaseShapeGenerator:GenerateBrushesFromPolygons(ShapePolygon[]) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/EditorWindows/BrushTools/Generators/GeneratorBase.cs:519)
RealtimeCSG.BoxGenerator:StartExtrudeMode(Boolean) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/EditorWindows/BrushTools/Generators/BoxGenerator.cs:241)
RealtimeCSG.BaseShapeGenerator:HandleHeightHandles() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/EditorWindows/BrushTools/Generators/GeneratorBase.cs:1024)
RealtimeCSG.BoxGenerator:HandleEditVerticesEvents() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/EditorWindows/BrushTools/Generators/BoxGenerator.cs:827)
RealtimeCSG.BaseShapeGenerator:HandleEvents() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/EditorWindows/BrushTools/Generators/GeneratorBase.cs:810)
RealtimeCSG.BoxGenerator:RealtimeCSG.IBrushGenerator.HandleEvents()
RealtimeCSG.GenerateBrushTool:HandleEvents() (at Assets/Plugins/RealtimeCSG/Editor/Scripts/EditorWindows/BrushTools/GenerateBrushTool.cs:185)
RealtimeCSG.CSGBrushEditorManager:OnSceneGUI(SceneView) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/EditorWindows/BrushEditorManager/CSGBrushEditorManager.cs:631)
RealtimeCSG.UnitySceneEventHandler:OnScene(SceneView) (at Assets/Plugins/RealtimeCSG/Editor

**Comment by LogicalError** [comment]
Can you tell me what you did when you got this error message? Also, what unity version are you using? Thanks

**Comment by sonygod** [comment]
I just want defined some prefab to reuse .
I did forgot what I do .
my unity version is 5.3.6f1

**Comment by LogicalError** [comment]
Well let me know if you're able to reproduce it ...

**Comment by LogicalError** [comment]
This issue is fixed in version 1.313 which is available on the update site!
( http://prenominal.nl/updates/index.php )

I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket

**Comment by LogicalError** [comment]
This version is now available on the asset store, so closing ticket
