### ISSUE TITLE
[Fix Available 1.314] export fbx will delete my other fbx model which inside csg child .

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#45]
export fbx will delete my other fbx model which inside csg child .

here is my cs model 

-Mode
 --Brush(1) [subtraction]
           ---myfbx(door) ()
  --Brush(2)

after export fbx,and myfbx node will be delete ,the result is not I want .

**Comment by sonygod** [comment]
![qq 20161026170403](https://cloud.githubusercontent.com/assets/748320/19719747/d9739538-9b9d-11e6-8a4b-220620411b4a.png)
![qq 20161026170450](https://cloud.githubusercontent.com/assets/748320/19719765/ea848936-9b9d-11e6-8af5-0c9f0d7c5db9.png)

**Comment by LogicalError** [comment]
Thanks for reporting this, I'll check it out tonight. 

Did you give the two exported fbx's different filenames?

**Comment by sonygod** [comment]
here more detail

the door fbx made by 3ds max,instead of csg model.

no ,one export is right,but don't destory the fbx model at scene.

**Comment by LogicalError** [comment]
Could you sent me the scene through email (you can find it at the top right corner of https://logicalerror.github.io/ ) so I can see this?

**Comment by sonygod** [comment]
I will send you  tonight!

**Comment by LogicalError** [comment]
Hi, I haven't received it yet, did you already sent it?

**Comment by sonygod** [comment]
will send today,

**Comment by sonygod** [comment]
https://logicalerror.github.io/
404? can not open

**Comment by LogicalError** [comment]
strange that you cannot access https://logicalerror.github.io/ it works just fine for me. Maybe github (that's where I host the stie) was down for a moment. I sent you an email

**Comment by LogicalError** [comment]
This issue is fixed in version 1.314 which is available on the update site!
( http://prenominal.nl/updates/index.php )

I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket

**Comment by LogicalError** [comment]
This version is now available on the asset store, so closing ticket
