### ISSUE TITLE
[1.315] Rotating UVs messes up normal and height maps

### ISSUE THREAD

**Issue by scatterlogical** [LogicalError/realtime-CSG-for-unity#47]
On certain surfaces, and when rotating a UV from it's original correct orientation, normal map shadows will rotate with the map, and height map parallax is incorrect.

Perhaps as a hint to a solution, I've noticed the same thing occurs in Procore's ProBuilder, but is correctable by enabling world space UVs, then the normal and height maps are corrected even after turning worldspace UVs off again.

**Comment by LogicalError** [comment]
Hi, I'm not entirely sure what you mean with "normal map shadows will rotate with the map" .. could you provide some screenshots maybe?

**Comment by LogicalError** [comment]
I tried rotating a surface with a normal mapped material on it and I didn't see anything out of the ordinary .. it would help if you could provide me some screenshots, a recording or a test scene that shows your problems. Test scenes can be sent to my email address which you can find on the top right corner of https://logicalerror.github.io/

**Comment by LogicalError** [comment]
Ok, seem to be some tangent issues. I'll try to find some time soon to fix this

**Comment by LogicalError** [comment]
This is fixed in version 1.315 which is available on the update site ( http://prenominal.nl/updates/index.php )!
I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment]
This version is now available on the asset store, so closing ticket
