### ISSUE TITLE
[Fix Available] Split mode doesn't work with Clip tool

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#48]
Clip tool doesn't split brushes, and it's making a invisible brush.

RealtimeCSG 1.308

**Comment by LogicalError** [comment]
Confirmed, thanks for reporting. I'll get a fix out asap

**Comment by LogicalError** [comment]
This issue is fixed in version 1.309 which is available on the update site 
( http://prenominal.nl/updates/index.php )
I will close this ticket when it's available on the asset store

**Comment by Hisashimaru** [comment]
I forgot report about how to make invisible brush.
![gif2](https://cloud.githubusercontent.com/assets/7605365/19752353/908f002e-9c37-11e6-93dd-dd9d6ad27aff.gif)

**Comment by LogicalError** [comment]
Ah, ok :-/ Thanks for reporting this

**Comment by LogicalError** [comment]
This issue is fixed in version 1.312 which is available on the update site!
( http://prenominal.nl/updates/index.php )
I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket
