### ISSUE TITLE
why I have to buy additional licenses again?

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#49]
why I have to buy uy additional licenses?

I had pay for this plugins at store.why why I have to buy uy additional licenses again?

**Comment by LogicalError** [comment]
Additional licenses? Are you refering to the "license per seat" (license per person) thing?
Is that really so unreasonable?
Windows, Maya, 3ds-max, Photoshop, Unity3d etc all require licenses per person .. for some of these you have to pay on a monthly basis as well...
I worked on this for 2 years before releasing it, one year full time. I made a significant investment in this that I probably will never earn back..
Is 50$ (per person that uses it) really that much compared to all the other costs while making a game?

**Comment by sonygod** [comment]
I said I  already bought  your plugin at store in Oct 20 2016,and need buy again?

**Comment by sonygod** [comment]
![qq 20161027135242](https://cloud.githubusercontent.com/assets/748320/19755996/3e5bfaa4-9c4c-11e6-95ff-de400451a9ee.png)

**Comment by sonygod** [comment]
![qq 20161027135442](https://cloud.githubusercontent.com/assets/748320/19756038/888499d8-9c4c-11e6-86a9-c0e685286ecf.png)

**Comment by sonygod** [comment]
is that unity store issue?

**Comment by LogicalError** [comment]
Yes that sounds like a unity store issue ..
If you bought it then it's yours.. no need to buy it again
