### ISSUE TITLE
[Fixed 1.350] Drag and drop materials to mesh objects

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#50]
Drag and drop a material to a mesh object doesn't work. 
1. Open new scene
2. Create a 3D object(box, sphere, cylinder....)
3. Drag and drop a material to the 3D object

RealtimeCSG 1.309

**Comment by LogicalError** [comment]
Hmm, I can't seem to be able to reproduce this ..
Can you try deleting your Assets/Plugins/RealtimeCSG folder while unity is closed, and re-installing RealtimeCSG 1.309?

**Comment by LogicalError** [comment]
Also, what unity version are you working with?

**Comment by Hisashimaru** [comment]
I've tried re-installing RealtimeCSG 1.309, but still doesn't work. 

I'm using Unity 5.4.2f1

**Comment by sonygod** [comment]
there's any problem in unity 5.3.6f1,work great!

**Comment by LogicalError** [comment]
Ok I'll try it again tonight with that Unity version..
You're dragging your material directly onto your brush in the scene, right?
And nothing happens?

**Comment by Hisashimaru** [comment]
Not a brush. Dragging a material directly onto unity's mesh object.

**Comment by LogicalError** [comment]
Oh, you mean a completely different mesh?? Ok, I'll look into it. Thanks for reporting this

**Comment by sonygod** [comment]
oh!really!

**Comment by LogicalError** [comment]
This issue is fixed in version 1.310 which is available on the update site 
( http://prenominal.nl/updates/index.php )
I will close this ticket when it's available on the asset store

**Comment by Hisashimaru** [comment]
Thanks for the updates!!

You can almost fix this issue. Drag and drop materials doesn't work after dragging on brushes.
![gif](https://cloud.githubusercontent.com/assets/7605365/19791649/091e9c40-9cfe-11e6-9b8b-7bfbb01a0381.gif)

**Comment by LogicalError** [comment]
This issue is fixed in version 1.313 which is available on the update site !
( http://prenominal.nl/updates/index.php )

I will close this ticket when it's available on the asset store

**Comment by sonygod** [comment]
can't  assign material to brush again?

version 1.314

**Comment by sonygod** [comment]
got it !
when there are some mesh on the same position as the brush ,they can't assign brush material.
will you fixed that?

**Comment by sonygod** [comment]
[video](https://youtu.be/aiooyNeF56E)

**Comment by Hisashimaru** [comment]
@sonygod 
Yeah, your right. I did't notice that!
Thanks for the video, but your video is private, and we can't watch it.

**Comment by LogicalError** [comment]
In the video it's a canvas, does this only happen for gui elements or also for "meshes"?

**Comment by LogicalError** [comment]
This has been fixed in version 1.350. Which can be downloaded from https://prenominal.nl/updates/
This ticket will be closed when this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available from the asset store, so I'm closing this ticket
