### ISSUE TITLE
[Question] what does a Plane mean in your csg system

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#51]
There is a conceptual problem,
what's mean Plane in your csg system?
what's the relationship between Plane and brush and Surface?

**Comment by LogicalError** [comment]
A plane is a mathematical plane, so it's an infinite 2D surface in 3D space.

Brushes are defined by the intersection of multiple planes.

In the code Surfaces and Texgens are basically the same thing, it's a bit messy and I need to clean this up, but it basically contains the plane, information on how to generate the texture coordinates, it's smoothing group and other flags like if it's discarded.
