### ISSUE TITLE
[Question] ask for Algorithm in your csg 

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#52]
![qq 20161028151154](https://cloud.githubusercontent.com/assets/748320/19797937/a4d377a6-9d20-11e6-872d-f977ac11690b.png)

 static int[,] graph =
            {
                {1,5},{5,2},{2,7},{7,3},{7,6},{5,6},{1,4},{4,3}
            };

how to csg use subtraction auto cut to two piece array like 

{1,4,3,7,6,5,1}
{5,6,7,2}

**Comment by LogicalError** [comment]
You mean, how to do this from code?
If you create your brushes using BrushFactory.CreateBrushFromPlanes, the second brush needs to be set as subtractive
MyBrush.OperationType = CSGOperationType.Subtractive;

You'll need to add both brushes as a child of a model, the second Subtractive brush needs to be added after the first (Additive) brush.

BrushFactory.CreateBrushFromPlanes needs a list of planes to be created, so it won't work on array of 2D points .. if you need that, let me know and I'll add more functionality to BrushFactory.CreateBrushFromPlanes for you

**Comment by sonygod** [comment]
add more functionality to BrushFactory.CreateBrushFromPlanes  include 2d will be pleasure!

**Comment by LogicalError** [comment]
All right, I created a ticket for this here: #57
