### ISSUE TITLE
[1.332] Missing discarded/trigger textures when switching scene in editor

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#53]
This video should explain the issue. I've noticed this happen on the 'discarded surface' and 'trigger' textures. Also to note they reload fine after I double click the scene to make it the main/active one.

https://www.youtube.com/watch?v=c9DCn_51oi0

**Comment by LogicalError** [comment]
Hmm, OK it shouldn't be showing the discarded surfaces and triggers for non-active scenes ..
At least that was the intention ..
Do you need to see the triggers / discarded surfaces for non-active scenes?

**Comment by Drexen** [comment]
I would prefer to have it show those surfaces for non-active scenes (unless otherwise set to hidden)

**Comment by LogicalError** [comment]
That might be complicated to do since right now only the surfaces for the current scene are being processed .. but I'll see if I can find a way to do this

**Comment by LogicalError** [comment]
This is fixed in version 1.332!
As usual this is available on the update site https://prenominal.nl/updates/
I'll close this ticket once this version is available from the asset store!
