### ISSUE TITLE
Directional lighting and discarded surfaces

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#54]
![Example](http://i.imgur.com/QYasoDQ.jpg)

In the example above I have a room with a directional light in the scene. Ideally I want the room to be unlit and the outer surfaces to be discarded as they will never be seen and should not be rendered. Is there a better way to go about this or can discarded surfaces be changed to block light rays?

**Comment by LogicalError** [comment]
Right now the only way to do this is by putting these discarded surfaces in another (csg) model, select it and set Cast Shadows to "Shadows only", then you won't need to discard them .. they won't be rendered, but they will still cast shadows..

**Comment by Drexen** [comment]
I found a solution for this. A property of the CSG Model script under Cast Shadows I can set it to "Two Sided", now surfaces with normals away from the directional light also catch light rays. You had programmed a solution all along!

**Comment by LogicalError** [comment]
Ah, didn't realize that that's what you wanted. Glad that that works for
you :)
