### ISSUE TITLE
[Fix Available 1.314] Can't flip brushes after slicing and removing polygons

### ISSUE THREAD

**Issue by HandsomeHank** [LogicalError/realtime-CSG-for-unity#55]
So I've noticed this a few times now.  I've been cutting cylinders in order to get the custom semi-rounded shapes I want.  I've noticed that if I slice one I often times cannot flip it along any axis any more.  This is a big deal for me because I have a lot of level to build and I will need to make use of a lot of rounded edges.  At this point it is far too late for me to switch back to probuilder and it has its own issues with rounded objects anyway.  If there were quarter round or half round meshes premade it would probably help.  It never happens on a cylinder that hasn't been sliced.

**Comment by LogicalError** [comment]
Ol, thanks for reporting this issue, I'll look into it

**Comment by LogicalError** [comment]
This issue is fixed in version 1.314 which is available on the update site!
( http://prenominal.nl/updates/index.php )

I will close this ticket when it's available on the asset store

**Comment by HandsomeHank** [comment]
It does indeed seem to be fixed.  Thanks.

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket

**Comment by LogicalError** [comment]
wait, this is version 1.314, on the asset store we're at 1.312, so shouldn't close it yet.

**Comment by LogicalError** [comment]
This version is now available on the asset store, so closing ticket
