### ISSUE TITLE
[Bug] UVs and mesh export

### ISSUE THREAD

**Issue by HandsomeHank** [LogicalError/realtime-CSG-for-unity#56]
So I've been hard at work with this for a while now and I have a question/concern.  When I extrude faces I notice that the UV's on the new objects do not always align.  I like to keep my textures as clean as possible in case I have to do any manual editing in Photoshop.  I've been trying to align them with the face tools but some of them just aren't going to line up well.  What options am I looking at here, aside from manually editing UV's on an ex[ported object?  I have 3DS but I'd prefer to avoid full retopology.

**Comment by LogicalError** [comment]
Hi, could you provide me with a test case so I can see where this goes wrong exactly? 
Preferabily with screenshots? 
Thanks for reporting this

**Comment by HandsomeHank** [comment]
I rebuilt the brushes that wouldn't line up and everything seems to be working now.  Next time it happens I will save the UV for you.  

On a related note.  I just started editing out my unused faces and have discovered that about 1/3 the time I cannot select and discard just one face.  Upon discarding any face, all faces are discarded.  This is kind of a big issue because I need a lot of architecture.  I hope I am just doing it wrong but I can't figure out how.

**Comment by LogicalError** [comment]
Ok, well let me know if you encounter this problem again ...

As for the selection thing, it's probably related to #59 .. when you select a brush all it's sides are automatically selected, but it's too hard to see at the moment so you might not notice ...

**Comment by HandsomeHank** [comment]
So here is what I think is happening.  When I have an object selected and enter faces mode, like you said, the entire object is selected.  Once that happens there is no way to deselect the brush normally.  Deselecting the object in the hierarchy or clicking on the face of another object still leave the brush fully selected in the faces mode.  The one way I have fixed it is by selecting the face of another object and disabling the texture on that face and then enabling it again.

**Comment by LogicalError** [comment]
Ok, I'll improve the surface selection workflow.
Locking a brush to another face? Aside from snapping to the grid there is no mechanism for that.
But perhaps there should be .. it would be very useful
Maybe something where if you hold a key while dragging it'll place the object you're moving on the surface behind the object/mouse cursor

**Comment by HandsomeHank** [comment]
Yeah, that could work. Sometimes I have an edge at a precise angle and when extruding of the surface the snap points don't match up with the rotation of the object.  I'll have to un-rotate the base object and then rotate it again to get the objects to snap together properly.  It works for now (usually) but if I could switch the grid to be based on the face of an object as I model it would be invaluable.

**Comment by LogicalError** [comment]
I've made request tickets for the dragging (#134) and for the selection issue (#135) since both kind of got lost in this ticket. As for the actual bug you mentioned in this ticket .. I haven't been able to reproduce it or anyone else has mentioned it .. maybe it was related to #47 ?
For the time being I'm going to mark this as unreproducable

**Comment by LogicalError** [comment]
Hi, Has this problem been fixed for you?
