### ISSUE TITLE
[Question] how to apply two Materials to this case? may be a bug

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#58]
[Question] how to apply two Materials to this case?

--Model
 ----brush1
-----brush2  [ subtraction]
I can't asign two Materals to brush1  because they share one material.

how can I do that? and How can I get that two spilit piecies brush  in one brush1 at code?

**Comment by sonygod** [comment]
![qq 20161031204026](https://cloud.githubusercontent.com/assets/748320/19854867/4327b1aa-9fac-11e6-863e-a32728a3e281.png)

![20161031203456](https://cloud.githubusercontent.com/assets/748320/19854878/4f0e4f60-9fac-11e6-8eea-037ae7890581.png)

**Comment by LogicalError** [comment]
You'll have to do this:

--Model
----brush1A [addition part 1]
----brush1B [addition part 2]
----brush2 [ subtraction]

Since everything is dynamic it's not feasible to assign materials on the sides of the brush, for instance, if you move the subtractive brush everything changes ...

**Comment by sonygod** [comment]
you mean I have to clone brush1 to brush1a ,brush1b?

**Comment by sonygod** [comment]
can you give a small video on youtube to this?

**Comment by sonygod** [comment]
this feature is very important to me for current project 
because I have to cut  a plane to pieces to became each room floor.
could you give me the simple way to do this? or sent me a video?

**Comment by LogicalError** [comment]
You can clip brush1 and split it into two pieces, then you can give an unique material to both pieces ..

**Comment by sonygod** [comment]
good,but how to call clip api at code?

**Comment by LogicalError** [comment]
Ah, I didn't realize you where doing this from code!
In this case you'll need to create two brushes instead of one .. :-/
In the meantime I'll see if I can add functionality to split brushes to the API

**Comment by sonygod** [comment]
right,but it's seem current clip function only support line cut but instead Polygon Clipp?
will you add this feature? for Irregular cut?

**Comment by LogicalError** [comment]
you mean cut against all the sides of a brush?

**Comment by sonygod** [comment]
![qq 20161028151154](https://cloud.githubusercontent.com/assets/748320/19797937/a4d377a6-9d20-11e6-872d-f977ac11690b.png)

I want to cut from 5 to 6 and then 6 to 7 ,to create two brush

first  5 -6 -7 2
second 1-5-6-7-3-4

**Comment by LogicalError** [comment]
you could just create three brushes
first 5-6-7-2
second 4-1-5-6-A
third 6-7-3-A

where A is a point in between 4 and 3

All brushes need to be convex, so an L shape cannot be a brush.

**Comment by sonygod** [comment]
sorry to heard that . it's seem current only way to do is create three brushes insteadof cut a brush to pieces
..

**Comment by LogicalError** [comment]
Even if you cut your brush, you'd still end up with 3 brushes .. only convex brushes are supported.

Adding support for non-convex brushes makes everything exponentially more complicated

You can group the "second" and "third" brushes under a gameobject with an CSGOperation component with selectOnChild set; it'll behave as if it's a single object

**Comment by sonygod** [comment]
so ,I have to use the other way to find out the points 5-2-6-7,and   1-5-6-7-3-4,then reused free-draw 
to draw this  Irregular  shape.
