### ISSUE TITLE
[1.315] Hard to see surface selected

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#59]
A small nit-pick but I feel it is hard to see what surfaces you have selected. Maybe apply a transparent mask over the whole faces that are selected in addition to highlighting the faces edges?

**Comment by LogicalError** [comment]
Strange, I'm pretty sure I commented on this. I guess I forgot to save it.

But yes, you're right, it's hard to see. It's hard to find a good balance between not getting in the way of seeing the surface and making it clear enough to see what you're selecting. I'll see if I can improve this.
Thanks for reporting this

**Comment by LogicalError** [comment]
This is improved in version 1.315 which is available on the update site ( http://prenominal.nl/updates/index.php )!
Let me know what you think

**Comment by LogicalError** [comment]
This version is now available on the asset store, so closing ticket
