### ISSUE TITLE
[Request] Placing non-brush prefabs onto brush surfaces

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#61]
Normal prefabs(Not a CSG prefab) can't placing on brush surfaces with dragging from assets window. Placing objects on surfaces is very useful for level editing. I request this feature :)

**Comment by LogicalError** [comment]
Sounds like a useful feature, thanks for the suggestion!

**Comment by LogicalError** [comment]
This is implemented in version 1.406, which can be found on the support website ( https://prenominal.nl/updates/ )
I will close this ticket once this version is available from the asset store
