### ISSUE TITLE
[Fix Available 1.313] Errors when modifying geometry

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#64]
https://www.youtube.com/watch?v=hI2UIAmNnjA

surface_index (5) >= surface_count (5), base-mesh not generated properly

IndexOutOfRangeException: Array index is out of range.
RealtimeCSG.ControlMeshState.UpdateHandles (InternalRealtimeCSG.ControlMesh controlMesh, UnityEngine.Vector3[] vertices) (at Assets/Plugins/RealtimeCSG/Editor/Scripts/EditorWindows/ControlMeshState.cs:379)

**Comment by LogicalError** [comment]
Okay, that shouldn't be happening.
I'll take a look at it
Again, thanks for the feedback!

**Comment by LogicalError** [comment]
This issue is fixed in version 1.313 which is available on the update site !
( http://prenominal.nl/updates/index.php )

I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket

**Comment by LogicalError** [comment]
This version is now available on the asset store, so closing ticket
