### ISSUE TITLE
Where is the R-CSG editor code entrance?

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#65]
Where is the R-CSG editor code entrance?

I want to do some modify function such  open/close for r-csg?

how to do this?

**Comment by LogicalError** [comment]
You want to run some code when realtime CSG starts up and shuts down? Is that what you mean?
There isn't a clear start/stop place since Unity doesn't have a clear point to do that either .. lots of edge cases and workarounds
What do you need it for?
