### ISSUE TITLE
Import RealtimeCSG.dll: Access is denied.

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#66]
![Import error](http://i.imgur.com/moVIcnX.png)

I always get this error when importing new versions of RealtimeCSG. Any insight into why and if its an issue?

**Comment by LogicalError** [comment]
Unfortunately that's a unity thing. You can't update the dll while Unity is using it.
This means you need to delete it outside of Unity, then start Unity & then update..

**Comment by Drexen** [comment]
Thanks for the info!
