### ISSUE TITLE
[1.326] Splitting multiple objects should retain selection of all selected objects

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#69]
If i select multiple objects and split them (keeping both parts) I only retain selection of one half of the split. It would be great if all the new objects are selected.

**Comment by LogicalError** [comment]
Sure, should be a simple thing to do

**Comment by LogicalError** [comment]
This is now implemented in version 1.326!
It can be downloaded from https://prenominal.nl/updates/
I'll close this ticket once this version is available on the asset store
