### ISSUE TITLE
Subtraction in builds (realtime)

### ISSUE THREAD

**Issue by Zaicheg** [LogicalError/realtime-CSG-for-unity#7]
Hello.

I can do subtract models in the application builds in realtime? 
To which platforms (WebGL, Android, ...)?

Example of code:
```
void Update()
{
	if (Input.GetKeyDown(KeyCode.K))
	{
		GameObject bigGameObject = Instantiate(...);
		GameObject smallGameObject = Instantiate(...);
		Mesh resultMesh = CSG.Substract(bigGameObject, smallGameObject);
		bigGameObject.GetComponent<MeshRenderer>().mesh = resultMesh;
	}
}
```

Example of use:
There is a room with six walls and the floor plane. It is necessary to trim the plane on the wall to get the correct form the floor.

**Comment by LogicalError** [comment]
Hi @Zaicheg right now there is no runtime support, only editor support. At some point I'm definitely going to add runtime support, but I just haven't gotten there yet..
