### ISSUE TITLE
[Requesst] Selecting objects in a 2D view

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#70]
It would be great if I could select objects in a 2D view by selecting on an edge. Currently selection in a 2D view is done via a raycast which is an issue if a ceiling is covering a bunch of geometry in a room. Just a thought.

**Comment by LogicalError** [comment]
Hi,
Did you know you can cycle through all the objects beneath your mouse by clicking multiple times?

**Comment by Drexen** [comment]
Good point. Didn't realise that was a feature. Thanks
