### ISSUE TITLE
[Question]how to use BrushFactory.CreateBrushFromPlanes?

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#74]
how to use BrushFactory.CreateBrushFromPlanes? any example about that ?

ex.
there are six  free point on a plane ,how to use BrushFactory.CreateBrushFromPlanes to draw a Polygon 2d ?

` CSGBrush CreateBrushFromPlanes(Transform parent, string brushName, UnityEngine.Plane[] planes, Vector3[] tangents = null, Vector3[] binormals = null, Material[] materials = null, Matrix4x4[] textureMatrices = null, TextureMatrixSpace textureMatrixSpace = TextureMatrixSpace.WorldSpace)`

**Comment by LogicalError** [comment]
A brush is always 3D, so you can't make a 2D shape with it ..
But if you want to make a 3D shape from a 2D shape, you can create the points that make up a surface of your convex shape by taking 3 points of every polygon on your shape and calculating a plane with it and create an array with those planes.

Then you can call:
CSGBrush myBrush = BrushFactor.CreateBrushFromPlanes(parentTransform, "myBrushName", myPlanes);
(all other parameters are optional)

**Comment by sonygod** [comment]
where is the vertex array input?

include in myPlanes? 
CSGBrush myBrush = BrushFactor.CreateBrushFromPlanes(parentTransform, "myBrushName", myPlanes);

I hope there are easy function call CreateBrushFromVertex and give vertex array and height  parms 

BrushFactor.CreateBrushFromVertex(parentTransform, "myBrushName", vertexArray,height);

**Comment by LogicalError** [comment]
That method hasn't been added yet to the brushfactory, but there is already a ticket for that: #57
The CreateBrushFromPlanes calculates the vertices as the intersection points of all the planes
