### ISSUE TITLE
[Request] draw L shape and Line support?

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#75]
[L shape](https://www.google.com/search?q=L+shape&newwindow=1&biw=1536&bih=764&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiClLLJ3JrQAhUBqJQKHT5FAwIQsAQIHQ)

 public bool AddVertex(Vector3 position, CSGBrush brush, CSGPlane plane, bool onGeometry, bool reAdd = false)
        {
            if (vertices.Length > 1)
            {
                if ((vertices[vertices.Length - 1] - position).sqrMagnitude < MathConstants.EqualityEpsilonSqr)
                {
                    return false;
                }
                if ((vertices[0] - position).sqrMagnitude < MathConstants.EqualityEpsilonSqr)
                {
                    return false;
                }
            }
            ArrayUtility.Add(ref vertices, position);
            ArrayUtility.Add(ref vertexSelectionState, SelectState.None);
            ArrayUtility.Add(ref edgeSelectionState, SelectState.None);
            ArrayUtility.Add(ref edgeSubdivision, SubdivisionState.None);

            ArrayUtility.Add(ref onGeometryVertices, onGeometry);
            ArrayUtility.Add(ref onPlaneVertices, plane);
            ArrayUtility.Add(ref onBrushVertices, brush);

            ArrayUtility.Add(ref edgeMaterials, MaterialUtility.WallMaterial);
            ArrayUtility.Add(ref edgeTexgens, new TexGen(edgeMaterials.Length - 1));

            var len = 1;
            if (vertices.Length > 2&&!reAdd)
            {
                //
                var list = new List<Vector3>();
                var c = vertices[vertices.Length - 1];
                var b = vertices[vertices.Length - 2];
                var a = vertices[vertices.Length - 3];
                var r = GeometryUtility.CounterClockwise(c, b, a);
                var a1 = Vector3.zero;
                var a2 = Vector3.zero;
                var b1 = Vector3.zero;
                var b2 = Vector3.zero;
                var c1 = Vector3.zero;
                var c2 = Vector3.zero;

                var ab = b - a;
                var cb = b - c;

                var ba = a - b;
                var bc = c - b;

                //
               var o = Vector3.Angle(ba, bc);

                var t = len/Mathf.Sin(o*Mathf.Deg2Rad);

                var bx = ab.normalized*t;
                var by = cb.normalized*t;

                b1 = b + bx + by;
                // b1 = new 
                //Quaternion.Euler(0, 0, 45) * (b + t * len) / Mathf.Cos(45 * Mathf.Deg2Rad); ;
                // b2 = b - new Vector3(len, len, 0);
                //Quaternion.Euler(0, 0, -(90 + 45)) * (b + t * len) / Mathf.Cos( 45* Mathf.Deg2Rad); ;

                b2 = b - bx - by;
                a1 = a + cb.normalized*t;
                a2 = a - cb.normalized*t;

                c1 = c + ab.normalized*t;
                c2 = c - ab.normalized*t;

                list.AddRange(new List<Vector3>() {c,c2,b2,a2,a,a1,b1,c1,c});
                //  list.AddRange(new List<Vector3>() { b,b1 });

                ArrayUtility.Clear(ref vertices);

              //  vertices = list.ToArray();

                for (int i = 0; i < list.Count; i++)
                {
                    AddVertex(list[i], brush,plane, onGeometry, true);

                }
                return true;

            }

            return false;

     

            //Debug.Log(position + " " + brush.name);
        }

I don't know how to draw more than one L shape and line at one progress.

**Comment by sonygod** [comment]
[`video`](https://www.youtube.com/watch?v=aiooyNeF56E)

I just combine other plugin to implement this feature。

**Comment by LogicalError** [comment]
I'm not entirely sure what you mean here .. didn't you already request a line drawing tool in another ticket?

**Comment by sonygod** [comment]
yes,it's repeat！
