### ISSUE TITLE
[Question]could not create brush from given 2d shape

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#76]
hi,I just have some vertex point use other tool genrateed.

"(135.1, 243.0, 0.0)"
"(335.1, 239.3, 0.0)"
"(334.9, 229.3, 0.0)"
"(134.9, 233.0, 0.0)"

public bool AddVertex(Vector3 position, CSGBrush brush, CSGPlane plane, bool onGeometry)

what's CSGPlane plane?

how to use in free-draw setting outline2d 

`        private void OnUpdate(Vector3[] vertex)
           {

           
             Cancel();
           var list=new List<Vector3>();
            list.AddRange(vertex);
           list.Add(vertex[0]);//is this ok?
         
            for (int i = 0; i < list.Count; i++)
            {
                settings.AddVertex(list[i], null, buildPlane, false);
              
            }
           // HandleCreateVerticesEvents2();

          ///  HotKeyReleased();
           Commit();

        }`

after call this function. throw some tip 

could not create brush from given 2d shape?

how to fixed my code ?

**Comment by LogicalError** [comment]
a csgplane is my own internal plane implementation since Unity's plane implementation is not serializable (it's not saved with an object). the function expects the plane on which all the points lie.
keep in mind that this is an internal method that may change some time in the future ..
