### ISSUE TITLE
[Fixed] Can't stop vertex snapping

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#77]
Reproduction steps:
1. Select a mesh object(not a csg brush)
2. Press the V key

RealtimeCSG 1.314
Unity 5.4.2f2

**Comment by LogicalError** [comment]
I'll look into it, thanks for reporting

**Comment by LogicalError** [comment]
To end building a shape, you can release the V key (which is broken somehow), but you can also move the final point on the first point (closing the loop) and that should still work

**Comment by LogicalError** [comment]
Just confirmed that "releasing the V key" doesn't work when drawing a shape on a brush, but still works on when drawing the shape on the grid (oddly enough)

**Comment by Hisashimaru** [comment]
Oh, you found other problem ;)
Actually my report is about Unity's vertex snapping mode. Sorry for confusing you.
![gif](https://cloud.githubusercontent.com/assets/7605365/20201307/53a9dec6-a7fa-11e6-9fe6-26956274ed43.gif)

**Comment by LogicalError** [comment]
Ok, yes, that's something very different ;)
I'll look into this

**Comment by LogicalError** [comment]
Related to #107

**Comment by LogicalError** [comment]
A temporary workaround until I fix this: disable realtime CSG using control-F3 (available in 1.326 and up) while moving a mesh and turn it back on (using, again, control-F3) afterwards

**Comment by LogicalError** [comment]
This has been fixed in version 1.350 (key changed to X). Which can be downloaded from https://prenominal.nl/updates/
This ticket will be closed when this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available from the asset store, so I'm closing this ticket
