### ISSUE TITLE
[1.315] Serious Console Stop Error!!

### ISSUE THREAD

**Issue by Cyber2017** [LogicalError/realtime-CSG-for-unity#78]
Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/MeshInstanceManager.cs(27,27): error CS0104: `SceneUtility' is an ambiguous reference between `RealtimeCSG.SceneUtility' and `UnityEngine.SceneManagement.SceneUtility'

Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/MeshInstanceManager.cs(584,31): error CS0104: `SceneUtility' is an ambiguous reference between `RealtimeCSG.SceneUtility' and `UnityEngine.SceneManagement.SceneUtility'

Hello... this comes up in version 1.312 , 1.314
Oh, I'm trying this on Unity 5.5b11

**Comment by Cyber2017** [comment]
WorkAround Available? k and.....

**Comment by LogicalError** [comment]
No I'm going to fix it, I just meant that until I have the fix for you, you can do what I described before

**Comment by Cyber2017** [comment]
Where exactly did you describe before? I didn't see any info...

**Comment by LogicalError** [comment]
Oh, seems like my original comment disappeared .. :(

So the workaround is to simply rename all occurrences SceneUtility in realtime CSG with RealtimeCSG.SceneUtility ..

**Comment by Cyber2017** [comment]
Oh ok.. lol I see now... Ya I was looking everywhere but thanks, I'll try that.. So, is it just this "MeshInstanceManager.cs" script I need to edit?

**Comment by LogicalError** [comment]
It's possible that you might need to do this in a couple of other files, but I think editing MeshInstanceManager.cs should be enough

**Comment by Cyber2017** [comment]
K, I just had to edit 5 lines in the "MeshInstanceManager.cs" script.. Magic! everything is perfect! Thanks for the quick Fix.. :)

**Comment by LogicalError** [comment]
np!

**Comment by LogicalError** [comment]
This is fixed in version 1.315 which is available on the update site ( http://prenominal.nl/updates/index.php )!
I will close this ticket when it's available on the asset store

**Comment by Cyber2017** [comment]
That was quick! :) Thanks for the Awesome support..

**Comment by LogicalError** [comment]
You're welcome :) This version is now available on the asset store, so closing ticket
