### ISSUE TITLE
[1.316] Keep brush tag and name and layer after explore fbx?

### ISSUE THREAD

**Issue by sonygod** [LogicalError/realtime-CSG-for-unity#91]
Keep brush (if all brush with difference materials )tag and name and layer after explore fbx?
don't use same name "mesh" +index ,I hope they can keep  the original brush some information。

**Comment by LogicalError** [comment]
The meshes aren't created per brush, but per material .. so it's not possible to match a brush to a mesh.
Tags aren't a problem, I'll copy those

**Comment by LogicalError** [comment]
Ok, tags are now copied, naming now uses the material names used on the meshes .. hopefully that's better
This can be found in version 1.316 which can be found on the update site ( http://prenominal.nl/updates/index.php )
I'll close this ticket when this version is on the asset store

**Comment by LogicalError** [comment]
This version is now available on the asset store, so closing ticket
