### ISSUE TITLE
[1.319] Rigidbody component must be on parent prefab...

### ISSUE THREAD

**Issue by Cyber2017** [LogicalError/realtime-CSG-for-unity#94]
Hello.. K I've discovered today that any prefabs made with Realtime CSG must have Rigidbody attached or the attached script throws error on each prefab I remove it from when runtime. Normally no problem but it Fracs up my triggers inside the models that I need my own Rigidbody for trigger. Is there any way to disable this problem without painfully removing all the scripts from each prefab?
This would suck totally lol

**Comment by Cyber2017** [comment]
It seems I have a solution..
1/ I made a seperate Folder: Prefabs_EDIT
2/ Cloned and Moved all prefabs into that
3/ I took any Realtime csg scripts off the prefabs used in my game scene, and the rigidbody off my static objects. This way I can still remodel any time needed :)

**Comment by LogicalError** [comment]
I'm not entirely sure if I understand .. are you saying you don't want CSG models to have any rigidbodies, because you have a parent object that already has a rigidbody?

**Comment by Cyber2017** [comment]
Most of my prefabs are Static (12m x 12m x 12m) Maze blocks... I only use rigidbody mainly if I have a trigger (box collider) to trigger an event. So, if there's already a rigidbody from Realtime CSG on parent than it conflicts with the child (zone trigger).. Luckily most of my zone triggers are seperate in it's own _Trigger folder..

**Comment by Cyber2017** [comment]
However, if there's a Rigidbody on all my 100 Maze blocks? Imagine the extra physics overhead this would create.. Although they are set "Is Kinematic" by Realtime CSG, there was some weird conflicts everytime my player ran into a trigger zone.. Anyhow, I'd like to see a way if.... we could keep the models just as you've got them but the script throws an error if we remove the rigidbody from the prefab (when we hit run in editor).. Hope this clarifies somewhat.. Great work on the improvements; features. :D

**Comment by Cyber2017** [comment]
All seems fine... Looks like I missed a few settings that we're enabled by "Default" on the "CSG Model" script..
Now should be good. Thanks! :D

**Comment by LogicalError** [comment]
Ok cool :)
So if I understand correctly it was a setting on the model that wasn't set correctly?
Do you think there's something I could improve to make things clearer?

**Comment by Cyber2017** [comment]
I thought everything was ok but I get the odd:
MissingComponentException: There is no 'Rigidbody' attached to the "Test" game object, but a script is trying to access it.
You probably need to add a Rigidbody to the game object "Test". Or your script needs to check if the component is attached before using it.
InternalRealtimeCSG.MeshInstanceManager.OnBuild () (at Assets/Plugins/RealtimeCSG/Editor/Scripts/Managers/MeshInstanceManager.cs:1039)

This is only if I uncheck:
All 3 settings under Physics: the "CSG Model" script. Oh the settings you have are very easy to find, I didn't really realize how important they were..

**Comment by LogicalError** [comment]
Fixed in 1.319 which you can find on the update site https://prenominal.nl/updates/ !
I'll close this ticket when this version is available on the asset store

**Comment by Cyber2017** [comment]
Kewl ! Thanks for the Fixx.. :)
I'll try this out tonight..
