### ISSUE TITLE
[Working Now] Grid Snapping "Not Working"/Unity 5.5b11

### ISSUE THREAD

**Issue by Cyber2017** [LogicalError/realtime-CSG-for-unity#95]
Not sure if it's just me but I tried to make a model and I couldn't get the grid snapping to work... Tried lot's of different stuff but no luck.. Oh well. Also the grid doesn't show through the objects, just around the outside.. I gather this asset hasn't been tested on the New Unity 5.5 beta?
However it's awesome! still in my books :D

**Comment by Cyber2017** [comment]
[Edited: November 12/2016.]
Correction: It's working.. Not sure why but now it's working great :D

**Comment by Cyber2017** [comment]
Again, this Version 1.315 is working very Well in Unity 5.5b11 / The only issue so far is I can't see any Grid Lines on the Model, only just see them around the Model..

**Comment by LogicalError** [comment]
I'll look into it, thanks for reporting

**Comment by LogicalError** [comment]
Did you turn on/off the snapping perhaps?

**Comment by LogicalError** [comment]
Ok, I'm going to close this ticket then if you say it's working now. Let me know if this issue comes back
