### ISSUE TITLE
[Bug] Unable to select brushes

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#96]
You can't select brushes, If Unity's object behind your selected brush.

RealtimeCSG 1.316
Unity 5.4.2f2

**Comment by Hisashimaru** [comment]
I think the latest report of #50 is a similar cause.

**Comment by LogicalError** [comment]
Hi, In which edit mode is this? All of them? I know that in surface edit mode selecting non brushes doesn't work well

**Comment by Hisashimaru** [comment]
The problem happens in object mode and mesh edit mode.

**Comment by LogicalError** [comment]
I'll look into it, thanks for reporting

**Comment by LogicalError** [comment]
related to #109 perhaps?

**Comment by LogicalError** [comment]
Fixed in version 1.351. Which can be downloaded from https://prenominal.nl/updates/
This ticket will be closed when this version is available from the asset store

**Comment by LogicalError** [comment]
This version is now available from the asset store, so I'm closing this ticket
