### ISSUE TITLE
[Compliment] It's beautiful!

### ISSUE THREAD

**Issue by jccreszMinecraft** [LogicalError/realtime-CSG-for-unity#98]
I'm a developer who has worked solely in Valve's Source Tools, Hammer, because I like that workflow based on a grid. Now that I've found this, I believe I can say hello to new technologies!

Thank you for making this!

**Comment by LogicalError** [comment]
Thanks! and .. you're welcome :)
If you have any suggestions or issues, please let me know :)

**Comment by jccreszMinecraft** [comment]
I do believe I have one suggestion: a VMF import/export tool, of course related to my current working space.

**Comment by LogicalError** [comment]
Importing / exporting should be do-able, although R-CSG does not (yet) support displacement mapping & Unity's lighting doesn't support custom falloff etc.

**Comment by LogicalError** [comment]
I made a ticket for this #117 :)

**Comment by jccreszMinecraft** [comment]
Probably shouldn't say in a "dead" ticket but would it be possible to bring this to Unreal?

**Comment by LogicalError** [comment]
Kind of impossible for me considering I work for Unity :)

**Comment by HeadClot** [comment]
Hey @jccreszMinecraft - My advice would be as follow get hammUEr from Itch.io or the Unreal Marketplace. Export as a .VMF and then import with hammUEr.

That would be my advice. :)
